// English
export const en = {
  translation: {
    en: 'English',
    zh: '简体中文',
    ja: '日本語',
    ko: '한국어',
    fr: 'Français',
    es: 'Español',
    pt: 'Português',
    de: 'Deutsch',
    vn: 'Tiếng Việt',
    preference: 'Preference',
    disable_button_vibration: 'Disable button vibration',
    back: 'Back',
    language: 'Language',
    app_theme: 'App Theme',
    system: 'System',
    dark: 'Dark',
    light: 'Light',
    settings: 'Settings',
    backup_and_security: 'Backup & Security',
    manage_wallet: 'Manage Wallet',
    profile: 'Profile',
    app_preferences: 'App Preferences',
    notifications: 'Notifications',
    help_support: 'Help & Support',
    about_my_doge: 'About My Doge',
    admin: 'Admin',
    i_cloud: 'iCloud',
    cloud: 'cloud',
    youve_backed_up_to: 'You’ve backed up to',
    you_havent_created_a_cloud_backup: 'You haven’t created a Cloud Backup',
    manage: 'Manage',
    backup: 'Backup',
    view_seed_phrase: 'View Seed Phrase',
    pin: 'PIN',
    back_up_to: 'Back up to',
    back_up_your_wallet: 'Back up your wallet',
    back_up_your_wallet_description:
      'Save your wallet to the cloud and protect it with a password. You can also write down your Seed Phrase or copy it to a password manager.',
    pin_description:
      'If your forget your PIN, you will need to restore your wallet from a backup.',
    change_pin: 'Change PIN',
    your_pin_is_required:
      'Your PIN is required to make payments and perform sensitive actions.',
    use_fingerprint: 'Use Fingerprint/Face ID',
    ask_every_time_i_open_the_app: 'Ask every time I open the app',
    this_will_remove_all_wallet:
      'This will remove all wallet related data from your device.',
    delete_wallet: 'Delete Wallet',
    sign_in_to_the_dogeverse: 'Sign in to the Dogeverse',
    dogeverse_intro_description:
      'Claim Your DogeTag, find friends, receive payments with your link, and engage with content in the Dogeverse.',
    sign_in: 'Sign in',
    sign_in_description:
      'Your phone number is only used to sign in and will not be made public.',
    create_account_description:
      'Join the Dogeverse and connect with a huge network of Shibes.',
    send_verification: 'Send Verification',
    verify_your_phone_number: 'Verify Your Phone Number',
    enter_the_code_sent_to: 'Enter the code sent to',
    resend_code: 'Resend Code',
    wrong_number: 'Wrong Number',
    confirm_code: 'Confirm Code',
    youve_entered_the_verse: 'You’ve entered the Verse',
    youre_now_ready_to_explore_the_dogeverse:
      'You’re now ready to explore the Dogeverse!',
    lets_go: 'Let’s go!',
    edit_profile: 'Edit Profile',
    social_connect: 'Social Connect',
    profile_privacy: 'Profile Privacy',
    profile_is_public: 'Profile is Public',
    show_wallet_address_and_tip_button: 'Show wallet address and Tip button',
    preferences: 'Preferences',
    confirm_x_tips: 'Confirm 𝕏 Tips',
    tips_received: 'Tips Received',
    new_followers: 'New Followers',
    new_memes: 'New Memes',
    about_mydoge: 'About MyDoge',
    terms_of_use: 'Terms of Use',
    privacy_policy: 'Privacy Policy',
    share_mydoge: 'Share MyDoge',
    visit_our_website: 'Visit Our Website',
    settings_and_support: 'Settings and Support',
    connect_twitch: 'Connect Twitch',
    connect_x: 'Connect 𝕏',
    create_a_post: 'Create a Post',
    following: 'Following',
    followers: 'Followers',
    recent_activity: 'Recent Activity',
    history: 'History',
    price: 'Price',
    usd: 'USD',
    txs: 'TXs',
    hr: 'hr',
    send: 'Send',
    receive: 'Receive',
    buy: 'Buy',
    scan: 'Scan',
    from: 'From',
    to: 'To',
    note: 'Note',
    timestamp: 'Timestamp',
    confirmations: 'Confirmations',
    tx_hash: 'TX Hash',
    tx_hash_copied: 'Transaction hash copied',
    note_copied: 'Note copied',
    address_copied: 'Address copied',
    wallet: 'Wallet',
    dogeverse: 'Dogeverse',
    shop: 'Shop',
    receive_doge: 'Receive Doge',
    send_doge: 'Send Doge',
    confirm_transaction: 'Confirm Transaction',
    scan_qr_code: 'Scan QR Code',
    new_post: 'New Post',
    send_doge_alert_box_message:
      'You can send DOGE to your friends, enter a wallet address or a MyDoge username',
    wallet_address_or_username: 'Wallet address or username',
    saved_addresses: 'Saved Addresses',
    add_new: 'Add New',
    sending_to: 'Sending to',
    save: 'Save',
    saved: 'Saved',
    balance: 'Balance',
    max: 'Max',
    next: 'Next',
    network_fee: 'Network Fee',
    max_tx_size_warning:
      'WARNING: Max transaction size reached. This is the most you can send at once.',
    confirm_transaction_warning:
      'Always double check who you are sending to before confirming. Never send to an exchange withdrawal address. Dogecoin transactions can not be reversed!',
    add_note: 'Add Note',
    wallet_address: 'Wallet Address',
    wallet_label: 'Wallet Label',
    save_changes: 'Save Changes',
    save_address: 'Save Address',
    enter_new_PIN: 'Enter new PIN',
    confirm_new_pin: 'Confirm new PIN',
    enter_new_PIN_description: 'Enter your new PIN for your MyDoge wallet',
    enter_old_PIN: 'Enter old PIN',
    enter_old_PIN_description: 'Enter your old PIN for your MyDoge wallet',
    forgot_PIN: 'Forgot PIN',
    confirm: 'Confirm',
    biometrics_confirmation:
      'Do you want to use biometrics to unlock your wallet?',
    use_biometrics: 'Use Biometrics',
    dismiss: 'Dismiss',
    remove_wallet_data_description:
      ' This will remove all wallet related data from your device.',
    delete_profile_forever: 'Delete your MyDoge Profile forever',
    sign_out: 'Sign Out',
    delete_wallet_confirmation: 'Hey! Are you sure?',
    remove_wallet_description:
      'Your current wallet will be removed from this app, however it will always exist on the blockchain.',
    remove_profile_assets_description:
      'Your user profile and assets will be removed and deleted permanently. This action cannot be undone.',
    wallet_recovery_description: ' You can ONLY recover this wallet with your',
    seed_phrase: 'SEED PHRASE',
    no_seed_phrase: 'MyDoge does not have your seed phrase.',
    understand_continue: 'I understand, continue',
    enter: 'Enter',
    Delete: 'Delete',
    erase_wallet: 'to erase your wallet',
    and_profile_data: 'and profile data',
    message: 'Message',
    username: 'Username',
    edit: 'Edit',
    new_address: 'New Address',
    your_seed_phrase: 'Your Seed Phrase ✍️',
    save_seed_phrase_instructions:
      ' Save these words, in order. Write them down and keep them somewhere safe, or copy them to a password manager.',
    seed_phrase_warning:
      'Your Seed Phrase is the key to your wallet. Anyone with this phrase can access your funds. Tap to learn more',
    copy: 'Copy',
    hide: 'Hide',
    show: 'Show',
    screenshot_detected: 'Screenshot detected',
    screenshot_warning:
      'Screenshots or other digital copies of your seed phrase could leak to a third party.',
    okay: 'Okay',
    seed_phrase_importance: 'How important is my Seed Phrase?',
    seed_phrase_explanation:
      'Anyone with your Seed Phrase can access your funds. Do not share your Seed Phrase with anyone. MyDoge does not save your Seed Phrase for you. Should your device be damaged, lost or stolen, or otherwise inaccessible, your Seed Phrase is the only way to recover your wallet.',
    send_receive_tips_x: 'Send and receive tips via 𝕏',
    read_mydogetip_faq: 'Read the MyDogeTip FAQ',
    connect_with_x: 'Connect with 𝕏',
    start_receive_tips_twitch: 'Start receiving tips on Twitch',
    visit_mydogetv_twitch: 'Visit MyDogeTV on Twitch for more info',
    connect_with_twitch: 'Connect with Twitch',
    screen_not_exist: "This screen doesn't exist.",
    go_to_home_screen: 'Go to Home Screen',
    gift_cards: 'Gift Cards',
    backup_wallet: 'Back up your new wallet',
    backup_required: 'A backup is required to secure your funds',
    why_backups_important: 'Why are backups important?',
    learn_about_backups: 'Tap to learn about backups',
    backup_to: 'Backup to',
    save_wallet_to_cloud:
      ' Save your wallet to the cloud and protect it with a password',
    write_on_paper: 'Write on paper',
    write_down_seed_phrase:
      'Write down your Seed Phrase or save it in a password manager',
    why_backups_important_description:
      'Self-custody means that nobody else can access your funds, not even the MyDoge team. A backup is the only way to restore your wallet if your device is damaged, lost or stolen, or erased.',
    choose_password: 'Choose a password',
    use_memorable_password:
      'Please use a password you can remember. Longer passwords are more secure.',
    more_secure_password:
      'Please use a password you can remember. Longer passwords are more secure.',
    lose_password_lose_backup:
      'If you lose this password you will lose your wallet backup.',
    password: 'Password',
    confirm_password: 'Confirm Password',
    confirm_backup: 'Confirm Backup',
    overwrite_backup_title: 'Overwrite existing backup?',
    existing_wallet_overwrite_prompt:
      'You have an existing wallet previously backed up to the cloud. Do you want to overwrite it?',
    overwrite_backup: 'Overwrite backup',
    import_existing_wallet: 'Import existing wallet',
    unknown_cloud_error: 'Unknown Cloud Error',
    unknown_cloud_error_body:
      'There was an unknown error while backing up to the cloud.',
    try_again_or_notify_support: 'Please try again or notify MyDoge support.',
    enter_recovery_password: 'Enter Recovery Password',
    enter_cloud_password_description:
      'Enter the password you used to store your seed phrase on the cloud',
    import_wallet: 'Import wallet',
    imported_wallet_title: 'You’ve imported your wallet',
    imported_wallet_success: 'You’ve successfully imported your wallet!',
    secure_new_wallet: 'Secure your new wallet',
    set_pin: 'Set a 6-digit PIN',
    reenter_pin: 'Re-enter 6-digit PIN_LENGTH',
    pin_payment_note: "You'll need your PIN to send payments",
    use_biometric: 'Use Fingerprint/Face ID',
    ask_every_time: 'Ask every time I open the app',
    create_pin: 'Create PIN',
    confirm_pin: 'Confirm PIN',
    choose_dogeverse_username: 'Choose a DogeTag',
    dogeverse_link: 'Your web link will be',
    continue: 'Continue',
    dogeverse_entry_title: 'You’ve entered the verse',
    dogeverse_entry_body: 'You’re now ready to explore the Dogeverse!',
    manual_backup_title: 'Write down Seed Phrase',
    save_words_order:
      'Save these words, in order. Write them down and keep them somewhere safe, or copy them to a password manager.',
    seed_phrase_key:
      'Your Seed Phrase is the key to your wallet. Anyone with this phrase can access your funds. Tap to learn more',
    written_down: 'I’ve written it down',
    screenshot_alert:
      'Screenshots or other digital copies of your Seed Phrase could leak to a third party.',
    seed_phrase_access:
      ' Anyone with your Seed Phrase can access your funds. Do not share your Seed Phrase with anyone. MyDoge does not save your Seed Phrase for you. Should your device be damaged, lost or stolen, or otherwise inaccessible, your Seed Phrase is the only way to recover your wallet.',
    icloud_backup: 'iCloud Backup',
    cloud_backup: 'Cloud Backup',
    dont_lose_wallet: 'Don’t lose your wallet!',
    save_online_backup: 'Save an online backup to',
    icloud: 'iCloud',
    google_drive: 'Google Drive',
    do_this_later: 'I’ll do this later',
    confirm_seed_phrase: 'Confirm seed phrase',
    select_correct_word:
      'Please select the correct word in each position from the list below.',
    enter_seed_phrase: 'Enter Seed Phrase',
    enter_seed_phrase_instructions:
      'Enter your 12 word Seed Phrase to restore your existing wallet',
    paste: 'Paste',
    restore_wallet: 'Restore Wallet',
    wallet_imported: 'Wallet imported!',
    wallet_imported_body: 'Your wallet is ready to use.',
    restore_existing_wallet: 'Restore your existing wallet',
    restore_existing_wallet_instructions:
      ' So you’ve got a wallet already? Let’s bring it back up then!',
    restore_from: 'Restore from',
    restore_from_cloud_description: 'Restore your wallet from your',
    restore_with_seed_phrase: 'Restore with a seed phrase',
    restore_with_seed_phrase_description:
      'Use your seed phrase to Restore an existing MyDoge wallet',
    no_cloud_backup: 'No Cloud Backup',
    no_cloud_backup_body:
      'Cloud backup not found. Please restore from a seed phrase, or create a new wallet',
    create_wallet: 'Create a wallet',
    already_have_wallet: ' I already have a wallet',
    buy_send_receive_dogecoin: 'Buy, Send & Receive Dogecoin',
    send_doge_tips:
      'Send Doge tips on 𝕏, store your Doge safely, and be your own bank',
    shop_gift_cards_apparel: 'Shop Gift Cards and Apparel',
    buy_gift_cards:
      'Buy gift cards with Dogecoin, or shop the latest Doge Fashion',
    enter_the_dogeverse: 'Enter the Dogeverse',
    claim_dogtag:
      'Claim Your DogeTag, find friends, receive payments with your link, and share memes',
    so_much_tip: 'So Tip, Much Wow!',
    success: 'Success',
    sent_doge: 'You’ve sent',
    some_doge: 'some Doge!',
    total: 'Total',
    done: 'Done',
    shop_with_doge: 'Shop with Doge',
    oops: 'Oops!',
    no_comments_yet: 'No comments yet',
    to_post_a_comment: 'to post a comment',
    your_comment: 'Your comment',
    post: 'Post',
    delete: 'Delete',
    enable_push_notifications: 'Enable Push Notifications?',
    get_notifications_for_tips: 'Get notifications for Tips and Messages',
    no_thanks: 'No thanks',
    open_settings: 'Open Settings',
    swipe_for_more: 'Swipe up for more',
    transaction_confirmation_alert:
      'Always double check who you are sending to before confirming. Never send to an exchange withdrawal address. Dogecoin transactions can not be reversed!',
    clear_amount: 'Clear Amount',
    set_amount: 'Set Amount',
    save_qr: 'Save QR',
    WALLET_ADDRESS: 'WALLET ADDRESS',
    dogetag_link: 'DOGETAG LINK',
    no_access_camera: 'No access to camera',
    enable_camera_access_ios: 'Enable camera access for MyDoge',
    grant_camera_permission_android: 'Please grant camera permission to MyDoge',
    scan_qr_payment: 'Scan QR code to make a payment',
    select_image: 'Select Image',
    find_friends_heading: 'Find Friends on MyDoge',
    find_friends_description:
      'Allow contact access and make it easy to find friends and contacts on MyDoge.',
    find_friends_button: 'Find Friends',
    later_button: 'I’ll do this later',
    own_address_error: 'You cannot send to your own address',
    invalid_address_error: 'Invalid address',
    results_title: 'Results',
    all: 'All',
    pending: 'Pending',
    enter_pin: 'Enter PIN',
    enter_pin_to_confirm: 'Enter your Wallet Pin to confirm',
    welcome_back: 'Welcome back',
    enter_wallet_pin: 'Enter your Wallet PIN',
    forgot_pin: 'Forgot PIN',
    forgot_pin_title: 'Forgot PIN',
    forgot_pin_body: 'Do you want to use biometrics to unlock your wallet?',
    share: 'Share',
    address_copied_to_clipboard: 'Address copied to clipboard',
    follows_you: 'Follows You',
    official_mydoge_profile: 'Official MyDoge Profile',
    official_mydoge_commerce_profile: 'Official MyDoge Commerce Profile',
    official_foundation_profile: 'Official Foundation Profile',
    follow_back: 'Follow Back',
    follow: 'Follow',
    tip: 'Tip',
    share_profile: 'Share Profile',
    unfollow: 'Unfollow',
    unblock: 'Unblock',
    block_or_report: 'Block or Report',
    copy_profile_url: 'Copy Profile URL',
    memes_error: 'Error loading memes. Please go back and try again.',
    user_profile_hidden: 'User profile is hidden',
    error_loading_profile:
      'Error loading profile. Please go back and try again.',
    uid_not_specified: 'Error: uid not specified. Please notify support.',
    block_or_report_description:
      'MyDoge will review all reported profiles for any activity against our guidelines. You can also block the profile to stop seeing their posts.',
    nevermind: 'Nevermind',
    report: 'Report',
    block: 'Block',
    unblock_user: 'Unblock User?',
    unblock_user_description:
      'This will unblock the user and you will continue to see their posts.',
    you_have_no_posts_yet: 'You have no posts yet',
    no_posts_yet: 'No posts yet',
    amount: 'Amount',
    custom: 'Custom',
    add_a_message: 'Add a message',
    find_friends: 'Find friends',
    cancel: 'Cancel',
    i_understand_continue: 'I understand, continue',
    hey_are_you_sure: 'Hey! Are you sure?',
    delete_backup_confirmation:
      'Once you delete this backup, you lose your cloud backup, this action cannot be undone',
    all_transactions: 'All Transactions',
    pending_transactions: 'Pending Transactions',
    view_on: 'View on',
    invoice_id_copied: 'Invoice ID copied',
    gift_card: 'Gift Card',
    invoice_id: 'Invoice ID',
    support: 'Support',
    phone_number: 'Phone number',
    whatsapp_verification_notice:
      'A verification code will be sent to your phone via WhatsApp',
    via_whatsapp: 'via WhatsApp',
    you_may_not_have_backed_up_your_wallet:
      'You have an existing backup on the cloud, but you may not have backed up your current wallet.',
    signed_in_as: 'Signed in as',
    sign_in_to_restore_backup: 'Sign in to restore backup',
    sign_in_with_google: 'Sign in with Google',
  },
};
