export const es = {
  translation: {
    en: "English",
    zh: "简体中文",
    ja: "日本語",
    ko: "한국어",
    fr: "Français",
    es: "Español",
    pt: "Português",
    de: "Deutsch",
    preference: "Preferencia",
    disable_button_vibration: "Desactivar botón de vibración",
    back: "Atrás",
    language: "Idioma",
    app_theme: "Tema de la aplicación",
    system: "Sistema",
    dark: "Oscuro",
    light: "Brillante",
    settings: "Configuración",
    backup_and_security: "Seguridad y archivo",
    manage_wallet: "Administrar billetera",
    profile: "Perfil",
    app_preferences: "Preferencias de la aplicación",
    notifications: "Notificaciones",
    help_support: "Apoyo",
    about_my_doge: "Acerca de MyDoge",
    admin: "Administración",
    i_cloud: "iCloud",
    cloud: "Nube",
    youve_backed_up_to: "Hiciste una copia de seguridad en",
    you_havent_created_a_cloud_backup:
      "No has hecho una copia de seguridad en la nube",
    manage: "Administrar",
    backup: "Respaldar",
    view_seed_phrase: "Ver frase semilla",
    pin: "PIN",
    back_up_to: "Archivar en",
    back_up_your_wallet: "Crea una copia de seguridad de tu billetera",
    back_up_your_wallet_description:
      "Guarda tu billetera en la nube y protégela con una contraseña. También puedes escribir tu frase semilla o copiarla en un administrador de contraseñas.",
    pin_description:
      "Si olvidas tu PIN, deberás restaurar tu billetera desde una copia de seguridad.",
    change_pin: "Cambiar PIN",
    your_pin_is_required:
      "Se requiere tu PIN para realizar pagos y acciones confidenciales.",
    use_fingerprint: "Usar huella digital/Face ID",
    ask_every_time_i_open_the_app: "Preguntar cada vez que abro la aplicación",
    this_will_remove_all_wallet:
      "Esto eliminará todos los datos relacionados con la billetera de tu dispositivo.",
    delete_wallet: "Eliminar billetera",
    sign_in_to_the_dogeverse: "Iniciar sesión de Dogeverse",
    dogeverse_intro_description:
      "Reclama tu DogeTag, encuentra amigos, recibe pagos con tu enlace e interactúa con el contenido de Dogeverse.",
    sign_in: "Iniciar sesión",
    sign_in_description:
      "Tu número de teléfono sólo se utiliza para iniciar sesión y no se hará público.",
    create_account_description:
      "Únete a Dogeverse y conecta con una enorme red de Shibes.",
    send_verification: "Enviar verificación",
    verify_your_phone_number: "Verifica tu número de teléfono",
    enter_the_code_sent_to: "Introduce el código enviado a",
    resend_code: "Reenviar codigo",
    wrong_number: "Número incorrecto",
    confirm_code: "Confirmar código",
    youve_entered_the_verse: "Has entrado en el verso",
    youre_now_ready_to_explore_the_dogeverse:
      "¡Ya estás listo para explorar el Dogeverse!",
    lets_go: "¡Vamos!",
    edit_profile: "Editar perfil",
    social_connect: "Conectar redes sociales",
    profile_privacy: "Privacidad del perfil",
    profile_is_public: "El perfil es público",
    show_wallet_address_and_tip_button:
      "Mostrar dirección de billetera y botón de propina",
    preferences: "Preferencias",
    confirm_x_tips: "Confirmar Propianas en 𝕏",
    tips_received: "Propinas recibidas",
    new_followers: "Nuevos seguidores",
    new_memes: "Nuevos Memes",
    about_mydoge: "Acerca de MyDoge",
    terms_of_use: "Condiciones de uso",
    privacy_policy: "Política de privacidad",
    share_mydoge: "Compartir MyDoge",
    visit_our_website: "Visita nuestro sitio web",
    settings_and_support: "Configuración y soporte",
    connect_twitch: "Conectar Twitch",
    connect_x: "Conectar 𝕏",
    create_a_post: "Crear una publicación",
    following: "Siguiendo",
    followers: "Seguidores",
    recent_activity: "Actividad reciente",
    history: "Historia",
    price: "Precio",
    usd: "USD",
    txs: "impuestos",
    hr: "hora",
    send: "Enviar",
    receive: "Recibir",
    buy: "Comprar",
    scan: "Escanear",
    from: "De",
    to: "A",
    note: "Nota",
    timestamp: "Marca de tiempo",
    confirmations: "Confirmaciones",
    tx_hash: "Hash de Transacción",
    tx_hash_copied: "Hash de transacción copiado",
    note_copied: "Nota copiada",
    address_copied: "Dirección copiada",
    wallet: "Billetera",
    dogeverse: "Dogeverso",
    shop: "Tienda",
    receive_doge: "Recibir Doge",
    send_doge: "Enviar Doge",
    confirm_transaction: "Confirmar transacción",
    scan_qr_code: "Escanear código QR",
    new_post: "Nueva publicación",
    send_doge_alert_box_message:
      "Puedes enviar DOGE a tus amigos, ingresa una dirección de billetera o un nombre de usuario de MyDoge",
    wallet_address_or_username: "Dirección de billetera o nombre de usuario",
    saved_addresses: "Direcciones guardadas",
    add_new: "Agregar nueva",
    sending_to: "Enviando a",
    save: "Guardar",
    saved: "Guardado",
    balance: "Balance",
    max: "máx.",
    next: "Próximo",
    network_fee: "Tarifa de red",
    max_tx_size_warning:
      "ADVERTENCIA: Se alcanzó el límite máximo de transacción. Esto es lo máximo que puedes enviar a la vez.",
    confirm_transaction_warning:
      "Siempre verifica a quién le estás enviando antes de confirmar. Nunca envíes a una dirección de retiro de Exchange. ¡Las transacciones de Dogecoin no se pueden revertir!",
    add_note: "Añadir nota",
    wallet_address: "Dirección de billetera",
    wallet_label: "Etiqueta de billetera",
    save_changes: "Guardar cambios",
    save_address: "Guardar dirección",
    enter_new_PIN: "Ingresar un nuevo PIN",
    confirm_new_pin: "Confirmar nuevo PIN",
    enter_new_PIN_description: "Ingresa tu nuevo PIN para tu billetera MyDoge",
    enter_old_PIN: "Introduce el PIN antiguo",
    enter_old_PIN_description:
      "Ingresa tu antiguo PIN para tu billetera MyDoge",
    forgot_PIN: "Olvidé mi PIN",
    confirm: "Confirmar",
    biometrics_confirmation:
      "¿Quieres utilizar datos biométricos para desbloquear tu billetera?",
    use_biometrics: "Utilizar biométricos",
    dismiss: "Descartar",
    remove_wallet_data_description:
      " Esto eliminará todos los datos relacionados con la billetera de tu dispositivo.",
    delete_profile_forever: "Elimina tu perfil MyDoge para siempre",
    sign_out: "Desconectar",
    delete_wallet_confirmation: "¡Ey! ¿Estás seguro?",
    remove_wallet_description:
      "Tu billetera actual se eliminará de esta aplicación; sin embargo, siempre existirá en la cadena de bloques.",
    remove_profile_assets_description:
      "Tu perfil de usuario y tus activos se eliminarán permanentemente. Esta acción no se puede deshacer.",
    wallet_recovery_description: " SÓLO puedes recuperar esta billetera con tu",
    seed_phrase: "FRASE SEMILLA",
    no_seed_phrase: "MyDoge no tiene tu frase semilla.",
    understand_continue: "Entiendo, continuar.",
    enter: "Ingresar",
    Delete: "Eliminar",
    erase_wallet: "para eliminar tu billetera",
    and_profile_data: "y datos de perfil",
    message: "Mensaje",
    username: "Nombre de usuario",
    edit: "Editar",
    new_address: "Nueva dirección",
    your_seed_phrase: "Tu frase semilla ✍️",
    save_seed_phrase_instructions:
      " Guarda estas palabras en orden. Anótalas y guárdalas en un lugar seguro, o cópialas en un administrador de contraseñas.",
    seed_phrase_warning:
      "Tu frase semilla es la clave de tu billetera. Cualquier persona con esta frase puede acceder a tus fondos. Toca para aprender más",
    copy: "Copiar",
    hide: "Esconder",
    show: "Mostrar",
    screenshot_detected: "Captura de pantalla detectada",
    screenshot_warning:
      "Las capturas de pantalla u otras copias digitales de tu frase semilla podrían filtrarse a un tercero.",
    okay: "Okay",
    seed_phrase_importance: "¿Qué importancia tiene mi frase semilla?",
    seed_phrase_explanation:
      "Cualquier persona con tu frase semilla puede acceder a tus fondos. No compartas tu frase semilla con nadie. MyDoge no guarda tu frase semilla. En caso de que tu dispositivo se dañe, se pierda o sea robado, o de otra manera sea inaccesible, tu Frase Semilla es la única forma de recuperar tu billetera.",
    send_receive_tips_x: "Envía y recibe propinas vía 𝕏",
    read_mydogetip_faq: "Lee las preguntas frecuentes de MyDogeTip",
    connect_with_x: "Conecta 𝕏",
    start_receive_tips_twitch: "Empieza a recibir propinas en Twitch",
    visit_mydogetv_twitch:
      "Visita MyDogeTV en Twitch para obtener más información",
    connect_with_twitch: "Conecta Twitch",
    screen_not_exist: "Esta pantalla no existe.",
    go_to_home_screen: "Ir a la pantalla de inicio",
    gift_cards: "Tarjetas de regalo",
    backup_wallet: "Hacer un archivo de seguridad de tu nueva billetera",
    backup_required:
      "Se requiere un archivo de seguridad para proteger tus fondos",
    why_backups_important: "¿Por qué son importantes l0s archivos de seguridad?",
    learn_about_backups:
      "Toca para obtener información sobre los archivos de seguridad",
    backup_to: "Respaldar a",
    save_wallet_to_cloud:
      " Guarda tu billetera en la nube y protégela con una contraseña",
    write_on_paper: "Escribir en papel",
    write_down_seed_phrase:
      "Escribe tu frase semilla o guárdala en un administrador de contraseñas",
    why_backups_important_description:
      "La autocustodia significa que nadie más puede acceder a tus fondos, ni siquiera el equipo de MyDoge. Un archivo de seguridad es la única forma de restaurar tu billetera si tu dispositivo se daña, se pierde, se lo roban o se borra.",
    choose_password: "Elige una contraseña",
    use_memorable_password:
      "Usa una contraseña que puedas recordar. Las contraseñas más largas son más seguras.",
    more_secure_password:
      "Usa una contraseña que pueda recordar. Las contraseñas más largas son más seguras.",
    lose_password_lose_backup:
      "Si pierdes esta contraseña, perderás el archivo de seguridad de tu billetera.",
    password: "Contraseña",
    confirm_password: "confirmar Contraseña",
    confirm_backup: "Confirmar archivo de seguridad",
    overwrite_backup_title: "¿Sobreescribir el archivo de seguridad existente?",
    existing_wallet_overwrite_prompt:
      "Tienes una billetera existente previamente respaldada en la nube. ¿Quieres sobreescribirla?",
    overwrite_backup: "Sobreescribir archivo de seguridad",
    import_existing_wallet: "Importar billetera existente",
    unknown_cloud_error: "Error de nube desconocido",
    unknown_cloud_error_body:
      "Se produjo un error desconocido al realizar el archivo de seguridad en la nube.",
    try_again_or_notify_support:
      "Inténtalo de nuevo o notifica al soporte de MyDoge.",
    enter_recovery_password: "Ingresa la contraseña de recuperación",
    enter_cloud_password_description:
      "Ingresa la contraseña que se utilizó para almacenar tu frase semilla en la nube",
    import_wallet: "Importar billetera",
    imported_wallet_title: "Has importado tu billetera",
    imported_wallet_success: "¡Has importado exitosamente tu billetera!",
    secure_new_wallet: "Asegura tu nueva billetera",
    set_pin: "Establecer un PIN de 6 dígitos",
    reenter_pin: "Vuelve a ingresar un PIN de 6 dígitos",
    pin_payment_note: "Necesitarás tu PIN para enviar pagos",
    use_biometric: "Usar huella digital/Face ID",
    ask_every_time: "Preguntar cada vez que abro la aplicación",
    create_pin: "Crear PIN",
    confirm_pin: "Confirmar PIN",
    choose_dogeverse_username: "Elige una etiqueta DogeTag",
    dogeverse_link: "Tu enlace web será",
    continue: "Continuar",
    dogeverse_entry_title: "Has entrado en el dogeverse",
    dogeverse_entry_body: "¡Ya estás listo para explorar Dogeverse!",
    manual_backup_title: "Escribe la frase semilla",
    save_words_order:
      "Guarda estas palabras en orden. Anótalas y guárdalas en un lugar seguro, o cópialas en un administrador de contraseñas.",
    seed_phrase_key:
      "Tu frase semilla es la clave de tu billetera. Cualquier persona con esta frase puede acceder a tus fondos. Toca para aprender más",
    written_down: "Lo escribí",
    screenshot_alert:
      "Las capturas de pantalla u otras copias digitales de tu frase inicial podrían filtrarse a un tercero.",
    seed_phrase_access:
      " Cualquier persona con tu frase inicial puede acceder a tus fondos. No compartas tu frase semilla con nadie. MyDoge no guarda tu frase semilla por ti. En caso de que tu dispositivo se dañe, se pierda o sea robado, o de otra manera sea inaccesible, tu Frase Semilla es la única forma de recuperar tu billetera.",
    icloud_backup: "Copia de seguridad de iCloud",
    cloud_backup: "Copia de seguridad en la nube",
    dont_lose_wallet: "¡No pierdas tu billetera!",
    save_online_backup: "Guarda una copia de seguridad en línea en",
    icloud: "iCloud",
    google_drive: "Google Drive",
    do_this_later: "Haré esto más tarde",
    confirm_seed_phrase: "Confirmar frase semilla",
    select_correct_word:
      "Selecciona la palabra correcta en cada posición de la lista a continuación.",
    enter_seed_phrase: "Ingresa la frase semilla",
    enter_seed_phrase_instructions:
      "Ingresa tu frase semilla de 12 palabras para restaurar tu billetera existente",
    paste: "Pegar",
    restore_wallet: "Restaurar billetera",
    wallet_imported: "¡Billetera importada!",
    wallet_imported_body: "Tu billetera está lista para usar.",
    restore_existing_wallet: "Restaura tu billetera existente",
    restore_existing_wallet_instructions:
      " ¿Entonces ya tienes una billetera? ¡Volvamos a subirlo entonces!",
    restore_from: "Restaurar desde",
    restore_from_cloud_description: "Restaura tu billetera desde tu",
    restore_with_seed_phrase: "Restaurar con una frase semilla",
    restore_with_seed_phrase_description:
      "Usa tu frase semilla para restaurar una billetera MyDoge existente",
    no_cloud_backup: "No hay copias de seguridad en la nube",
    no_cloud_backup_body:
      "No se encontró la copia de seguridad en la nube. Restaura desde una frase semilla o crea una nueva billetera",
    create_wallet: "Crear una billetera",
    already_have_wallet: " ya tengo una billetera",
    buy_send_receive_dogecoin: "Compra, envía y recibe Dogecoin",
    send_doge_tips:
      "Envía propinas de Doge con 𝕏, almacena tu Doge de forma segura y sé tu propio banco",
    shop_gift_cards_apparel: "Comprar tarjetas de regalo y ropa",
    buy_gift_cards:
      "Compra tarjetas de regalo con Dogecoin o compre lo último en moda Doge",
    enter_the_dogeverse: "Entra en el Dogeverse",
    claim_dogtag:
      "Reclama tu DogeTag, encuentra amigos, recibe pagos con tu enlace y comparte memes",
    so_much_tip: "Una propina, ¡guau!",
    success: "Éxito",
    sent_doge: "Enviaste DOGE",
    some_doge: "¡algunos DOGE!",
    total: "Total",
    done: "Hecho",
    shop_with_doge: "Comprar con Doge",
    oops: "¡Ups!",
    no_comments_yet: "Sin comentarios aún",
    to_post_a_comment: "Para publicar un comentario",
    your_comment: "Tu comentario",
    post: "Correo",
    delete: "Borrar",
    enable_push_notifications: "¿Habilitar notificaciones automáticas?",
    get_notifications_for_tips:
      "Recibir notificaciones de propinas y mensajes",
    no_thanks: "No, gracias",
    open_settings: "Configuración abierta",
    swipe_for_more: "Desliza hacia arriba para más",
    transaction_confirmation_alert:
      "Siempre verifica a quién le está enviando antes de confirmar. Nunca envíes a una dirección de retiro de Exchange. ¡Las transacciones de Dogecoin no se pueden revertir!",
    clear_amount: "Borrar cantidad",
    set_amount: "Establecer cantidad",
    save_qr: "Guardar QR",
    WALLET_ADDRESS: "DIRECCIÓN DE BILLETERA",
    dogetag_link: "ENLACE DE DOGETAG",
    no_access_camera: "No se pudo acceder a la cámara",
    enable_camera_access_ios: "Habilitar el acceso a la cámara para MyDoge",
    grant_camera_permission_android:
      "Por favor, concede permiso de cámara a MyDoge",
    scan_qr_payment: "Escanea el código QR para realizar un pago",
    select_image: "Seleccionar imagen",
    find_friends_heading: "Encuentra amigos en MyDoge",
    find_friends_description:
      "Permite el acceso a los contactos y facilita la búsqueda de amigos y contactos en MyDoge.",
    find_friends_button: "Encontrar amigos",
    later_button: "Haré esto más tarde",
    own_address_error: "No puedes enviar a tu propia dirección.",
    invalid_address_error: "Dirección inválida",
    results_title: "Resultados",
    all: "Todo",
    pending: "Pendiente",
    enter_pin: "Ingresa tu PIN",
    enter_pin_to_confirm: "Ingresa tu PIN de Wallet para confirmar",
    welcome_back: "Bienvenido de nuevo",
    enter_wallet_pin: "Ingresa tu PIN",
    forgot_pin: "Olvidé mi PIN",
    forgot_pin_title: "Olvidé mi PIN",
    forgot_pin_body:
      "¿Quieres utilizar datos biométricos para desbloquear tu billetera?",
    share: "Compartir",
    address_copied_to_clipboard: "Dirección copiada al portapapeles",
    follows_you: "Te sigue",
    official_mydoge_profile: "Perfil oficial de MyDoge",
    official_mydoge_commerce_profile: "Perfil comercial oficial de MyDoge",
    official_foundation_profile: "Perfil oficial de la Fundación",
    follow_back: "Seguir también",
    follow: "Seguir",
    tip: "Propina",
    share_profile: "Compartir perfil",
    unfollow: "Dejar de seguir",
    unblock: "Desbloquear",
    block_or_report: "Bloquear o reportar",
    copy_profile_url: "Copiar URL del perfil",
    memes_error:
      "Error al cargar memes. Por favor, regresa y vuelve a intentarlo.",
    user_profile_hidden: "El perfil de usuario está oculto",
    error_loading_profile:
      "Error al cargar el perfil. Por favor, regresa y vuelve a intentarlo.",
    uid_not_specified:
      "Error: uid no especificado. Por favor notifica al soporte.",
    block_or_report_description:
      "MyDoge revisará todos los perfiles reportados para detectar cualquier actividad que incumpla con nuestras pautas. También puedes bloquear el perfil para dejar de ver sus publicaciones.",
    nevermind: "No importa",
    report: "Reportar",
    block: "Bloquear",
    unblock_user: "¿Desbloquear usuario?",
    unblock_user_description:
      "Esto desbloqueará al usuario y seguirás viendo sus publicaciones.",
    you_have_no_posts_yet: "Aún no tienes publicaciones",
    no_posts_yet: "Aún no hay publicaciones",
    amount: "Cantidad",
    custom: "Personalizado",
    add_a_message: "Añade un mensaje",
    find_friends: "Encontrar amigos",
    cancel: "Cancelar",
    i_understand_continue: "Entiendo, continúa.",
    hey_are_you_sure: "¡Ey! ¿Está seguro?",
    delete_backup_confirmation:
      "Una vez que elimines esta copia de seguridad, perderás tu copia de seguridad en la nube, esta acción no se puede deshacer",
    all_transactions: "Todas las transacciones",
    pending_transactions: "Transacciones pendientes",
  },
};
