export const es = {
  translation: {
    en: 'English',
    zh: '简体中文',
    ja: '日本語',
    ko: '한국어',
    fr: 'Français',
    es: 'Español',
    pt: 'Português',
    preference: 'Preferencia',
    disable_button_vibration: 'Desactivar la vibración del botón',
    back: 'Atrás',
    language: 'Idioma',
    app_theme: 'Tema de la aplicación',
    system: 'Sistema',
    dark: 'Oscuro',
    light: 'Luz',
    settings: 'Ajustes',
    backup_and_security: 'Copia de seguridad y seguridad',
    manage_wallet: 'Administrar billetera',
    profile: 'Perfil',
    app_preferences: 'Preferencias de la aplicación',
    notifications: 'Notificaciones',
    help_support: 'Servicio de asistencia',
    about_my_doge: 'Acerca de mi dux',
    admin: 'Administración',
    i_cloud: 'iCloud',
    cloud: 'nube',
    youve_backed_up_to: 'Has hecho una copia de seguridad de',
    you_havent_created_a_cloud_backup:
      'No has creado una copia de seguridad en la nube',
    manage: 'Administrar',
    backup: 'Respaldo',
    view_seed_phrase: 'Ver frase inicial',
    pin: 'ALFILER',
    back_up_to: 'Respalda a',
    back_up_your_wallet: 'Haga una copia de seguridad de su billetera',
    back_up_your_wallet_description:
      'Guarde su billetera en la nube y protéjala con una contraseña. También puede escribir su frase inicial o copiarla en un administrador de contraseñas.',
    pin_description:
      'Si olvida su PIN, deberá restaurar su billetera desde una copia de seguridad.',
    change_pin: 'Cambiar PIN',
    your_pin_is_required:
      'Se requiere su PIN para realizar pagos y realizar acciones confidenciales.',
    use_fingerprint: 'Usar huella digital/identificación facial',
    ask_every_time_i_open_the_app: 'Preguntar cada vez que abro la aplicación',
    this_will_remove_all_wallet:
      'Esto eliminará todos los datos relacionados con la billetera de su dispositivo.',
    delete_wallet: 'Eliminar billetera',
    sign_in_to_the_dogeverse: 'Iniciar sesión en Dogeverse',
    dogeverse_intro_description:
      'Reclama tu DogeTag, encuentra amigos, recibe pagos con tu enlace e interactúa con el contenido de Dogeverse.',
    sign_in: 'Iniciar sesión',
    sign_in_description:
      'Su número de teléfono sólo se utiliza para iniciar sesión y no se hará público.',
    create_account_description:
      'Únase a Dogeverse y conéctese con una enorme red de Shibes.',
    send_verification: 'Enviar verificación',
    verify_your_phone_number: 'Verifica tu numero de telefono',
    enter_the_code_sent_to: 'Introduce el código enviado a',
    resend_code: 'Reenviar codigo',
    wrong_number: 'Número equivocado',
    confirm_code: 'Confirma código',
    youve_entered_the_verse: 'Has entrado en el verso',
    youre_now_ready_to_explore_the_dogeverse:
      '¡Ya estás listo para explorar Dogeverse!',
    lets_go: '¡Vamos!',
    edit_profile: 'Editar perfil',
    social_connect: 'Conexión social',
    profile_privacy: 'Privacidad del perfil',
    profile_is_public: 'El perfil es público',
    show_wallet_address_and_tip_button:
      'Mostrar dirección de billetera y botón de propina',
    preferences: 'Preferencias',
    confirm_x_tips: 'Confirmar 𝕏 Consejos',
    tips_received: 'Propinas recibidas',
    new_followers: 'Nuevos seguidores',
    new_memes: 'Nuevos Memes',
    about_mydoge: 'Acerca de MyDoge',
    terms_of_use: 'Condiciones de uso',
    privacy_policy: 'política de privacidad',
    share_mydoge: 'Compartir MyDoge',
    visit_our_website: 'Visite nuestro sitio web',
    settings_and_support: 'Configuración y soporte',
    connect_twitch: 'Conectar contracción',
    connect_x: 'Conectate 𝕏',
    create_a_post: 'Crear una publicación',
    following: 'Siguiente',
    followers: 'Seguidores',
    recent_activity: 'Actividad reciente',
    history: 'Historia',
    price: 'Precio',
    usd: 'Dólar estadounidense',
    txs: 'TX',
    hr: 'hora',
    send: 'Enviar',
    receive: 'Recibir',
    buy: 'Comprar',
    scan: 'Escanear',
    from: 'De',
    to: 'A',
    note: 'Nota',
    timestamp: 'Marca de tiempo',
    confirmations: 'Confirmaciones',
    tx_hash: 'Hash TX',
    tx_hash_copied: 'Hash de transacción copiado',
    note_copied: 'Nota copiada',
    address_copied: 'Dirección copiada',
    wallet: 'Billetera',
    dogeverse: 'Dogeverso',
    shop: 'Comercio',
    receive_doge: 'Recibir Doge',
    send_doge: 'enviar dux',
    confirm_transaction: 'Confirmar transacción',
    scan_qr_code: 'Escanear código QR',
    new_post: 'Nueva publicación',
    send_doge_alert_box_message:
      'Puedes enviar DOGE a tus amigos, ingresar una dirección de billetera o un nombre de usuario de MyDoge',
    wallet_address_or_username: 'Dirección de billetera o nombre de usuario',
    saved_addresses: 'Direcciones guardadas',
    add_new: 'Agregar nuevo',
    sending_to: 'Enviando a',
    save: 'Ahorrar',
    saved: 'Salvado',
    balance: 'Balance',
    max: 'máx.',
    next: 'Próximo',
    network_fee: 'Tarifa de red',
    max_tx_size_warning:
      'ADVERTENCIA: Se alcanzó el tamaño máximo de transacción. Esto es lo máximo que puedes enviar a la vez.',
    confirm_transaction_warning:
      'Siempre verifique a quién le está enviando antes de confirmar. Nunca envíe a una dirección de retiro de Exchange. ¡Las transacciones de Dogecoin no se pueden revertir!',
    add_note: 'Añadir la nota',
    wallet_address: 'Dirección de billetera',
    wallet_label: 'Etiqueta de billetera',
    save_changes: 'Guardar cambios',
    save_address: 'Guardar dirección',
    enter_new_PIN: 'Ingrese un nuevo PIN',
    confirm_new_pin: 'Confirmar nuevo PIN',
    enter_new_PIN_description: 'Ingrese su nuevo PIN para su billetera MyDoge',
    enter_old_PIN: 'Introduce el PIN antiguo',
    enter_old_PIN_description:
      'Ingrese su antiguo PIN para su billetera MyDoge',
    forgot_PIN: 'Olvidé mi PIN',
    confirm: 'Confirmar',
    biometrics_confirmation:
      '¿Quieres utilizar datos biométricos para desbloquear tu billetera?',
    use_biometrics: 'Utilice la biometría',
    dismiss: 'Despedir',
    remove_wallet_data_description:
      ' Esto eliminará todos los datos relacionados con la billetera de su dispositivo.',
    delete_profile_forever: 'Elimina tu perfil MyDoge para siempre',
    sign_out: 'Desconectar',
    delete_wallet_confirmation: '¡Ey! ¿Está seguro?',
    remove_wallet_description:
      'Su billetera actual se eliminará de esta aplicación; sin embargo, siempre existirá en la cadena de bloques.',
    remove_profile_assets_description:
      'Su perfil de usuario y sus activos se eliminarán y eliminarán permanentemente. Esta acción no se puede deshacer.',
    wallet_recovery_description: ' SÓLO puedes recuperar esta billetera con tu',
    seed_phrase: 'FRASE SEMILLA',
    no_seed_phrase: 'MyDoge no tiene su frase inicial.',
    understand_continue: 'Entiendo, continúa.',
    enter: 'Ingresar',
    Delete: 'Borrar',
    erase_wallet: 'para borrar tu billetera',
    and_profile_data: 'y datos de perfil',
    message: 'Mensaje',
    username: 'Nombre de usuario',
    edit: 'Editar',
    new_address: 'Nueva direccion',
    your_seed_phrase: 'Tu frase semilla ✍️',
    save_seed_phrase_instructions:
      ' Guarde estas palabras en orden. Anótelos y guárdelos en un lugar seguro, o cópielos en un administrador de contraseñas.',
    seed_phrase_warning:
      'Tu frase inicial es la clave de tu billetera. Cualquier persona con esta frase puede acceder a sus fondos. Toca para aprender más',
    copy: 'Copiar',
    hide: 'Esconder',
    show: 'Espectáculo',
    screenshot_detected: 'Captura de pantalla detectada',
    screenshot_warning:
      'Las capturas de pantalla u otras copias digitales de su frase inicial podrían filtrarse a un tercero.',
    okay: 'Bueno',
    seed_phrase_importance: '¿Qué importancia tiene mi frase semilla?',
    seed_phrase_explanation:
      'Cualquier persona con su frase inicial puede acceder a sus fondos. No compartas tu frase semilla con nadie. MyDoge no guarda su frase inicial por usted. En caso de que su dispositivo se dañe, se pierda o sea robado, o de otra manera sea inaccesible, su Frase Semilla es la única forma de recuperar su billetera.',
    send_receive_tips_x: 'Envía y recibe propinas vía 𝕏',
    read_mydogetip_faq: 'Lea las preguntas frecuentes de MyDogeTip',
    connect_with_x: 'Conéctate con 𝕏',
    start_receive_tips_twitch: 'Empieza a recibir consejos en Twitch',
    visit_mydogetv_twitch:
      'Visita MyDogeTV en Twitch para obtener más información',
    connect_with_twitch: 'Conéctate con Twitch',
    screen_not_exist: 'Esta pantalla no existe.',
    go_to_home_screen: 'Ir a la pantalla de inicio',
    gift_cards: 'Tarjetas de regalo',
    backup_wallet: 'Haga una copia de seguridad de su nueva billetera',
    backup_required:
      'Se requiere una copia de seguridad para proteger sus fondos',
    why_backups_important: '¿Por qué son importantes las copias de seguridad?',
    learn_about_backups:
      'Toca para obtener información sobre las copias de seguridad',
    backup_to: 'Respalda a',
    save_wallet_to_cloud:
      ' Guarde su billetera en la nube y protéjala con una contraseña',
    write_on_paper: 'escribir en papel',
    write_down_seed_phrase:
      'Escriba su frase inicial o guárdela en un administrador de contraseñas',
    why_backups_important_description:
      'La autocustodia significa que nadie más puede acceder a sus fondos, ni siquiera el equipo de MyDoge. Una copia de seguridad es la única forma de restaurar su billetera si su dispositivo se daña, se pierde, se lo roban o se borra.',
    choose_password: 'Elije una contraseña',
    use_memorable_password:
      'Utilice una contraseña que pueda recordar. Las contraseñas más largas son más seguras.',
    more_secure_password:
      'Utilice una contraseña que pueda recordar. Las contraseñas más largas son más seguras.',
    lose_password_lose_backup:
      'Si pierde esta contraseña, perderá la copia de seguridad de su billetera.',
    password: 'Contraseña',
    confirm_password: 'confirmar Contraseña',
    confirm_backup: 'Confirmar copia de seguridad',
    overwrite_backup_title: '¿Sobrescribir la copia de seguridad existente?',
    existing_wallet_overwrite_prompt:
      'Tiene una billetera existente previamente respaldada en la nube. ¿Quieres sobreescribirlo?',
    overwrite_backup: 'Sobrescribir copia de seguridad',
    import_existing_wallet: 'Importar billetera existente',
    unknown_cloud_error: 'Error de nube desconocido',
    unknown_cloud_error_body:
      'Se produjo un error desconocido al realizar la copia de seguridad en la nube.',
    try_again_or_notify_support:
      'Inténtelo de nuevo o notifique al soporte de MyDoge.',
    enter_recovery_password: 'Ingrese la contraseña de recuperación',
    enter_cloud_password_description:
      'Ingrese la contraseña que utilizó para almacenar su frase inicial en la nube',
    import_wallet: 'Importar billetera',
    imported_wallet_title: 'Has importado tu billetera',
    imported_wallet_success: '¡Has importado exitosamente tu billetera!',
    secure_new_wallet: 'Asegure su nueva billetera',
    set_pin: 'Establecer un PIN de 6 dígitos',
    reenter_pin: 'Vuelva a ingresar PIN_LENGTH de 6 dígitos',
    pin_payment_note: 'Necesitará su PIN para enviar pagos',
    use_biometric: 'Usar huella digital/identificación facial',
    ask_every_time: 'Preguntar cada vez que abro la aplicación',
    create_pin: 'Crear PIN',
    confirm_pin: 'confirmar PIN',
    choose_dogeverse_username: 'Elija una etiqueta DogeTag',
    dogeverse_link: 'Su enlace web será',
    continue: 'Continuar',
    dogeverse_entry_title: 'Has entrado en el verso',
    dogeverse_entry_body: '¡Ya estás listo para explorar Dogeverse!',
    manual_backup_title: 'Escriba la frase inicial',
    save_words_order:
      'Guarde estas palabras en orden. Anótelos y guárdelos en un lugar seguro, o cópielos en un administrador de contraseñas.',
    seed_phrase_key:
      'Tu frase inicial es la clave de tu billetera. Cualquier persona con esta frase puede acceder a sus fondos. Toca para aprender más',
    written_down: 'lo he escrito',
    screenshot_alert:
      'Las capturas de pantalla u otras copias digitales de su frase inicial podrían filtrarse a un tercero.',
    seed_phrase_access:
      ' Cualquier persona con su frase inicial puede acceder a sus fondos. No compartas tu frase semilla con nadie. MyDoge no guarda su frase inicial por usted. En caso de que su dispositivo se dañe, se pierda o sea robado, o de otra manera sea inaccesible, su Frase Semilla es la única forma de recuperar su billetera.',
    icloud_backup: 'Copia de seguridad de iCloud',
    cloud_backup: 'Respaldo en la nube',
    dont_lose_wallet: '¡No pierdas tu billetera!',
    save_online_backup: 'Guarde una copia de seguridad en línea en',
    icloud: 'iCloud',
    google_drive: 'Google Drive',
    do_this_later: 'haré esto más tarde',
    confirm_seed_phrase: 'Confirmar frase inicial',
    select_correct_word:
      'Seleccione la palabra correcta en cada posición de la lista a continuación.',
    enter_seed_phrase: 'Ingrese la frase inicial',
    enter_seed_phrase_instructions:
      'Ingrese su frase inicial de 12 palabras para restaurar su billetera existente',
    paste: 'Pegar',
    restore_wallet: 'Restaurar billetera',
    wallet_imported: 'Cartera importada!',
    wallet_imported_body: 'Tu billetera está lista para usar.',
    restore_existing_wallet: 'Restaura tu billetera existente',
    restore_existing_wallet_instructions:
      ' ¿Entonces ya tienes una billetera? ¡Volvamos a subirlo entonces!',
    restore_from: 'Restaurar desde',
    restore_from_cloud_description: 'Restaura tu billetera desde tu',
    restore_with_seed_phrase: 'Restaurar con una frase inicial',
    restore_with_seed_phrase_description:
      'Utilice su frase inicial para restaurar una billetera MyDoge existente',
    no_cloud_backup: 'Sin copia de seguridad en la nube',
    no_cloud_backup_body:
      'No se encontró la copia de seguridad en la nube. Restaure desde una frase inicial o cree una nueva billetera',
    create_wallet: 'crear una billetera',
    already_have_wallet: ' ya tengo una billetera',
    buy_send_receive_dogecoin: 'Compre, envíe y reciba Dogecoin',
    send_doge_tips:
      'Envía consejos de Doge sobre 𝕏, almacena tu Doge de forma segura y sé tu propio banco',
    shop_gift_cards_apparel: 'Comprar tarjetas de regalo y ropa',
    buy_gift_cards:
      'Compre tarjetas de regalo con Dogecoin o compre lo último en moda Doge',
    enter_the_dogeverse: 'Entra en el Dogeverse',
    claim_dogtag:
      'Reclama tu DogeTag, encuentra amigos, recibe pagos con tu enlace y comparte memes',
    so_much_tip: 'Así que consejo, ¡guau!',
    success: 'Éxito',
    sent_doge: 'has enviado',
    some_doge: '¡algunos dux!',
    total: 'Total',
    done: 'Hecho',
    shop_with_doge: 'Comprar con Doge',
    oops: '¡Ups!',
    no_comments_yet: 'Sin comentarios aún',
    to_post_a_comment: 'para publicar un comentario',
    your_comment: 'Tu comentario',
    post: 'Correo',
    delete: 'Borrar',
    enable_push_notifications: '¿Habilitar notificaciones automáticas?',
    get_notifications_for_tips:
      'Recibir notificaciones de sugerencias y mensajes',
    no_thanks: 'No, gracias',
    open_settings: 'Configuración abierta',
    swipe_for_more: 'Desliza hacia arriba para más',
    transaction_confirmation_alert:
      'Siempre verifique a quién le está enviando antes de confirmar. Nunca envíe a una dirección de retiro de Exchange. ¡Las transacciones de Dogecoin no se pueden revertir!',
    clear_amount: 'Borrar cantidad',
    set_amount: 'Fijar cantidad',
    save_qr: 'Guardar QR',
    WALLET_ADDRESS: 'DIRECCIÓN DE BILLETERA',
    dogetag_link: 'ENLACE DE DOGETAG',
    no_access_camera: 'Sin acceso a la cámara',
    enable_camera_access_ios: 'Habilitar el acceso a la cámara para MyDoge',
    grant_camera_permission_android:
      'Por favor, conceda permiso de cámara a MyDoge',
    scan_qr_payment: 'Escanea el código QR para realizar un pago',
    select_image: 'Seleccionar imagen',
    find_friends_heading: 'Encuentra amigos en MyDoge',
    find_friends_description:
      'Permita el acceso a los contactos y facilite la búsqueda de amigos y contactos en MyDoge.',
    find_friends_button: 'Encontrar amigos',
    later_button: 'haré esto más tarde',
    own_address_error: 'No puedes enviar a tu propia dirección.',
    invalid_address_error: 'Dirección inválida',
    results_title: 'Resultados',
    all: 'Todo',
    pending: 'Pendiente',
    enter_pin: 'Ingrese su PIN',
    enter_pin_to_confirm: 'Ingresa tu PIN de Wallet para confirmar',
    welcome_back: 'Bienvenido de nuevo',
    enter_wallet_pin: 'Ingrese su PIN de billetera',
    forgot_pin: 'Olvidé mi PIN',
    forgot_pin_title: 'Olvidé mi PIN',
    forgot_pin_body:
      '¿Quieres utilizar datos biométricos para desbloquear tu billetera?',
    share: 'Compartir',
    address_copied_to_clipboard: 'Dirección copiada al portapapeles',
    follows_you: 'Te sigue',
    official_mydoge_profile: 'Perfil oficial de MyDoge',
    official_mydoge_commerce_profile: 'Perfil comercial oficial de MyDoge',
    official_foundation_profile: 'Perfil oficial de la Fundación',
    follow_back: 'Seguir de nuevo',
    follow: 'Seguir',
    tip: 'Consejo',
    share_profile: 'Compartir perfil',
    unfollow: 'Dejar de seguir',
    unblock: 'Desatascar',
    block_or_report: 'Bloquear o informar',
    copy_profile_url: 'Copiar URL del perfil',
    memes_error:
      'Error al cargar memes. Por favor, regrese y vuelva a intentarlo.',
    user_profile_hidden: 'El perfil de usuario está oculto',
    error_loading_profile:
      'Error al cargar el perfil. Por favor, regrese y vuelva a intentarlo.',
    uid_not_specified:
      'Error: uid no especificado. Por favor notifique al soporte.',
    block_or_report_description:
      'MyDoge revisará todos los perfiles reportados para detectar cualquier actividad que cumpla con nuestras pautas. También puedes bloquear el perfil para dejar de ver sus publicaciones.',
    nevermind: 'No importa',
    report: 'Informe',
    block: 'Bloquear',
    unblock_user: '¿Desbloquear usuario?',
    unblock_user_description:
      'Esto desbloqueará al usuario y seguirás viendo sus publicaciones.',
    you_have_no_posts_yet: 'Aún no tienes publicaciones',
    no_posts_yet: 'Aún no hay publicaciones',
    amount: 'Cantidad',
    custom: 'Costumbre',
    add_a_message: 'Añade un mensaje',
    find_friends: 'Encontrar amigos',
    cancel: 'Cancelar',
    i_understand_continue: 'Entiendo, continúa.',
    hey_are_you_sure: '¡Ey! ¿Está seguro?',
    delete_backup_confirmation:
      'Una vez que elimines esta copia de seguridad, perderás tu copia de seguridad en la nube, esta acción no se puede deshacer',
    all_transactions: 'Todas las transacciones',
    pending_transactions: 'transacciones pendientes',
  },
};
