export const fr = {
  translation: {
    en: `English`,
    zh: `简体中文`,
    ja: `日本語`,
    ko: `한국어`,
    fr: `Français`,
    es: `Español`,
    pt: `Português`,
    de: `Deutsch`,
    vn: "Tiếng Việt",
    preference: `Préférence`,
    disable_button_vibration: `Désactiver la vibration des boutons`,
    back: `Retour`,
    language: `Langue`,
    app_theme: `Thème de l'application`,
    system: `Système`,
    dark: `Sombre`,
    light: `Lumière`,
    settings: `Paramètres`,
    backup_and_security: `Sauvegarde et sécurité`,
    manage_wallet: `Gérer le porte-monnaie`,
    profile: `Profil`,
    app_preferences: `Préférences de l'application`,
    notifications: `Notifications`,
    help_support: `Support d'aide`,
    about_my_doge: `À propos de Mon Doge`,
    admin: `Administrateur`,
    i_cloud: `iCloud`,
    cloud: `cloud`,
    youve_backed_up_to: `Vous avez sauvegardé`,
    you_havent_created_a_cloud_backup: `Vous n'avez pas créé de sauvegarde cloud`,
    manage: `Gérer`,
    backup: `Sauvegarde`,
    view_seed_phrase: `Afficher la phrase racine`,
    pin: `ÉPINGLE`,
    back_up_to: `Sauvegarder`,
    back_up_your_wallet: `Sauvegardez votre portefeuille`,
    back_up_your_wallet_description: `Enregistrez votre portefeuille dans le cloud et protégez-le avec un mot de passe. Vous pouvez également écrire votre phrase de départ ou la copier dans un gestionnaire de mots de passe.`,
    pin_description: `Si vous oubliez votre code PIN, vous devrez restaurer votre portefeuille à partir d'une sauvegarde.`,
    change_pin: `Changer le code PIN`,
    your_pin_is_required: `Votre code PIN est requis pour effectuer des paiements et effectuer des actions sensibles.`,
    use_fingerprint: `Utiliser l'empreinte digitale/l'identification faciale`,
    ask_every_time_i_open_the_app: `Demander à chaque fois que j'ouvre l'application`,
    this_will_remove_all_wallet: `Cela supprimera toutes les données liées au portefeuille de votre appareil.`,
    delete_wallet: `Supprimer le portefeuille`,
    sign_in_to_the_dogeverse: `Connectez-vous au Dogeverse`,
    dogeverse_intro_description: `Réclamez votre DogeTag, trouvez des amis, recevez des paiements avec votre lien et interagissez avec le contenu du Dogeverse.`,
    sign_in: `Se connecter`,
    sign_in_description: `Votre numéro de téléphone sert uniquement à vous connecter et ne sera pas rendu public.`,
    create_account_description: `Rejoignez le Dogeverse et connectez-vous à un vaste réseau de Shibes.`,
    send_verification: `Envoyer la vérification`,
    verify_your_phone_number: `Vérifiez votre numéro de téléphone`,
    enter_the_code_sent_to: `Entrez le code envoyé à`,
    resend_code: `Renvoyer le code`,
    wrong_number: `Mauvais numéro`,
    confirm_code: `Confirmer le code`,
    youve_entered_the_verse: `Vous êtes entré dans le verset`,
    youre_now_ready_to_explore_the_dogeverse: `Vous êtes maintenant prêt à explorer le Dogeverse !`,
    lets_go: `Allons-y!`,
    edit_profile: `Editer le profil`,
    social_connect: `Connexion sociale`,
    profile_privacy: `Confidentialité du profil`,
    profile_is_public: `Le profil est public`,
    show_wallet_address_and_tip_button: `Afficher l'adresse du portefeuille et le bouton Pourboire`,
    preferences: `Préférences`,
    confirm_x_tips: `Confirmer 𝕏 Conseils`,
    tips_received: `Pourboires reçus`,
    new_followers: `Nouveaux abonné`,
    new_memes: `Nouveaux mèmes`,
    about_mydoge: `À propos de MyDoge`,
    terms_of_use: `Conditions d'utilisation`,
    privacy_policy: `politique de confidentialité`,
    share_mydoge: `Partager MonDoge`,
    visit_our_website: `Visitez notre site Internet`,
    settings_and_support: `Paramètres et assistance`,
    connect_twitch: `Connectez votre compte Twitch`,
    connect_x: `Connectez votre compte 𝕏`,
    create_a_post: `Créer une publication`,
    following: `Suivi`,
    followers: `Abonnés`,
    recent_activity: `Activité récente`,
    history: `Historique`,
    price: `Prix`,
    usd: `USD`,
    txs: `TX`,
    hr: `heure`,
    send: `Envoyer`,
    receive: `Recevoir`,
    buy: `Acheter`,
    scan: `Analyse`,
    from: `Depuis`,
    to: `À`,
    note: `Note`,
    timestamp: `Horodatage`,
    confirmations: `Confirmation`,
    tx_hash: `Hachage TX`,
    tx_hash_copied: `Hachage de transaction copié`,
    note_copied: `Remarque copiée`,
    address_copied: `Adresse copiée`,
    wallet: `Porte-monnaie`,
    dogeverse: `Dogeverse`,
    shop: `Boutique`,
    receive_doge: `Recevoir Doge`,
    send_doge: `Envoyer Doge`,
    confirm_transaction: `Confirmer la transaction`,
    scan_qr_code: `Scanner le code QR`,
    new_post: `Nouveau poste`,
    send_doge_alert_box_message: `Vous pouvez envoyer DOGE à vos amis, saisir une adresse de portefeuille ou un nom d'utilisateur MyDoge`,
    wallet_address_or_username: `Adresse du portefeuille ou nom d'utilisateur`,
    saved_addresses: `Adresses enregistrées`,
    add_new: `Ajouter un nouveau`,
    sending_to: `Envoi à`,
    save: `Sauvegarder`,
    saved: `Enregistré`,
    balance: `Solde`,
    max: `Max.`,
    next: `Suivant`,
    network_fee: `Frais de réseau`,
    max_tx_size_warning: `AVERTISSEMENT : Taille maximale de la transaction atteinte. C'est le maximum que vous puissiez envoyer en une seule fois.`,
    confirm_transaction_warning: `Vérifiez toujours à qui vous envoyez avant de confirmer. N’envoyez jamais à une adresse de retrait d’échange. Les transactions Dogecoin ne peuvent pas être annulées !`,
    add_note: `Ajouter une note`,
    wallet_address: `Adresse du portefeuille`,
    wallet_label: `Étiquette de portefeuille`,
    save_changes: `Sauvegarder les modifications`,
    save_address: `Enregistrer l'adresse`,
    enter_new_PIN: `Entrez le nouveau code PIN`,
    confirm_new_pin: `Confirmer le nouveau code PIN`,
    enter_new_PIN_description: `Entrez votre nouveau code PIN pour votre portefeuille MyDoge`,
    enter_old_PIN: `Entrez l'ancien code PIN`,
    enter_old_PIN_description: `Entrez votre ancien code PIN pour votre portefeuille MyDoge`,
    forgot_PIN: `Code PIN oublié`,
    confirm: `Confirmer`,
    biometrics_confirmation: `Voulez-vous utiliser la biométrie pour déverrouiller votre portefeuille ?`,
    use_biometrics: `Utiliser la biométrie`,
    dismiss: `Rejeter`,
    remove_wallet_data_description: ` Cela supprimera toutes les données liées au portefeuille de votre appareil.`,
    delete_profile_forever: `Supprimez définitivement votre profil MyDoge`,
    sign_out: `Se déconnecter`,
    delete_wallet_confirmation: `Hé! Es-tu sûr?`,
    remove_wallet_description: `Votre portefeuille actuel sera supprimé de cette application, mais il existera toujours sur la blockchain.`,
    remove_profile_assets_description: `Votre profil utilisateur et vos actifs seront supprimés et supprimés définitivement. Cette action ne peut pas être annulée.`,
    wallet_recovery_description: ` Vous pouvez UNIQUEMENT récupérer ce portefeuille avec votre`,
    seed_phrase: `LA PHRASE RACINE`,
    no_seed_phrase: `MyDoge n'a pas votre phrase de départ.`,
    understand_continue: `Je comprends, continue`,
    enter: `Entrer`,
    Delete: `Supprimer`,
    erase_wallet: `pour effacer ton portefeuille`,
    and_profile_data: `et données de profil`,
    message: `Message`,
    username: `Nom d'utilisateur`,
    edit: `Modifier`,
    new_address: `Nouvelle adresse`,
    your_seed_phrase: `Votre phrase de départ ✍️`,
    save_seed_phrase_instructions: ` Gardez ces mots, dans l'ordre. Notez-les et conservez-les dans un endroit sûr, ou copiez-les dans un gestionnaire de mots de passe.`,
    seed_phrase_warning: `Votre phrase de départ est la clé de votre portefeuille. Toute personne possédant cette phrase peut accéder à vos fonds. Appuyez pour en savoir plus`,
    copy: `Copie`,
    hide: `Cacher`,
    show: `Afficher`,
    screenshot_detected: `Capture d'écran détectée`,
    screenshot_warning: `Des captures d'écran ou d'autres copies numériques de votre phrase de départ pourraient être divulguées à un tiers.`,
    okay: `D'accord`,
    seed_phrase_importance: `Quelle est l’importance de ma phrase de départ ?`,
    seed_phrase_explanation: `Toute personne possédant votre phrase de départ peut accéder à vos fonds. Ne partagez votre phrase de départ avec personne. MyDoge ne sauvegarde pas votre phrase de départ pour vous. Si votre appareil est endommagé, perdu, volé ou autrement inaccessible, votre phrase de départ est le seul moyen de récupérer votre portefeuille.`,
    send_receive_tips_x: `Envoyez et recevez des conseils via 𝕏`,
    read_mydogetip_faq: `Lire la FAQ MyDogeTip`,
    connect_with_x: `Connectez-vous avec 𝕏`,
    start_receive_tips_twitch: `Commencez à recevoir des pourboire sur Twitch`,
    visit_mydogetv_twitch: `Visitez MyDogeTV sur Twitch pour plus d'informations`,
    connect_with_twitch: `Connectez-vous avec Twitch`,
    screen_not_exist: `Cet écran n'existe pas.`,
    go_to_home_screen: `Aller à l'écran d'accueil`,
    gift_cards: `Cartes cadeaux`,
    backup_wallet: `Sauvegardez votre nouveau portefeuille`,
    backup_required: `Une sauvegarde est nécessaire pour sécuriser vos fonds`,
    why_backups_important: `Pourquoi les sauvegardes sont-elles importantes ?`,
    learn_about_backups: `Appuyez pour en savoir plus sur les sauvegardes`,
    backup_to: `Sauvegarder`,
    save_wallet_to_cloud: ` Enregistrez votre portefeuille dans le cloud et protégez-le avec un mot de passe`,
    write_on_paper: `Écrire sur papier`,
    write_down_seed_phrase: `Notez votre phrase de départ ou enregistrez-la dans un gestionnaire de mots de passe`,
    why_backups_important_description: `L'auto-garde signifie que personne d'autre ne peut accéder à vos fonds, pas même l'équipe MyDoge. Une sauvegarde est le seul moyen de restaurer votre portefeuille si votre appareil est endommagé, perdu, volé ou effacé.`,
    choose_password: `Choisissez un mot de passe`,
    use_memorable_password: `Veuillez utiliser un mot de passe dont vous vous souvenez. Les mots de passe plus longs sont plus sécurisés.`,
    more_secure_password: `Veuillez utiliser un mot de passe dont vous vous souvenez. Les mots de passe plus longs sont plus sécurisés.`,
    lose_password_lose_backup: `Si vous perdez ce mot de passe, vous perdrez la sauvegarde de votre portefeuille.`,
    password: `Mot de passe`,
    confirm_password: `Confirmez le mot de passe`,
    confirm_backup: `Confirmer la sauvegarde`,
    overwrite_backup_title: `Écraser la sauvegarde existante ?`,
    existing_wallet_overwrite_prompt: `Vous disposez d'un portefeuille existant préalablement sauvegardé sur le cloud. Voulez-vous l'écraser ?`,
    overwrite_backup: `Écraser la sauvegarde`,
    import_existing_wallet: `Importer un portefeuille existant`,
    unknown_cloud_error: `Erreur cloud inconnue`,
    unknown_cloud_error_body: `Une erreur inconnue s'est produite lors de la sauvegarde sur le cloud.`,
    try_again_or_notify_support: `Veuillez réessayer ou informer l'assistance MyDoge.`,
    enter_recovery_password: `Entrez le mot de passe de récupération`,
    enter_cloud_password_description: `Entrez le mot de passe que vous avez utilisé pour stocker votre phrase de départ sur le cloud`,
    import_wallet: `Importer un portefeuille`,
    imported_wallet_title: `Vous avez importé votre portefeuille`,
    imported_wallet_success: `Vous avez importé avec succès votre portefeuille !`,
    secure_new_wallet: `Sécurisez votre nouveau portefeuille`,
    set_pin: `Définir un code PIN à 6 chiffres`,
    reenter_pin: `Saisissez à nouveau le code PIN_LENGTH à 6 chiffres.`,
    pin_payment_note: `Vous aurez besoin de votre code PIN pour envoyer des paiements`,
    use_biometric: `Utiliser l'empreinte digitale/l'identification faciale`,
    ask_every_time: `Demander à chaque fois que j'ouvre l'application`,
    create_pin: `Créer un code PIN`,
    confirm_pin: `Confirmer le code PIN`,
    choose_dogeverse_username: `Choisissez un DogeTag`,
    dogeverse_link: `Votre lien Web sera`,
    continue: `Continuer`,
    dogeverse_entry_title: `Vous avez entré le verset`,
    dogeverse_entry_body: `Vous êtes maintenant prêt à explorer le Dogeverse !`,
    manual_backup_title: `Écrivez la phrase de départ`,
    save_words_order: `Gardez ces mots, dans l'ordre. Notez-les et conservez-les dans un endroit sûr, ou copiez-les dans un gestionnaire de mots de passe.`,
    seed_phrase_key: `Votre phrase de départ est la clé de votre portefeuille. Toute personne possédant cette phrase peut accéder à vos fonds. Appuyez pour en savoir plus`,
    written_down: `je l'ai écrit`,
    screenshot_alert: `Des captures d'écran ou d'autres copies numériques de votre phrase de départ pourraient être divulguées à un tiers.`,
    seed_phrase_access: ` Toute personne possédant votre phrase de départ peut accéder à vos fonds. Ne partagez votre phrase de départ avec personne. MyDoge ne sauvegarde pas votre phrase de départ pour vous. Si votre appareil est endommagé, perdu, volé ou autrement inaccessible, votre phrase de départ est le seul moyen de récupérer votre portefeuille.`,
    icloud_backup: `Sauvegarde iCloud`,
    cloud_backup: `Sauvegarde sur le cloud`,
    dont_lose_wallet: `Ne perdez pas votre portefeuille !`,
    save_online_backup: `Enregistrez une sauvegarde en ligne sur`,
    icloud: `iCloud`,
    google_drive: `Google Drive`,
    do_this_later: `je ferai ça plus tard`,
    confirm_seed_phrase: `Confirmer la phrase de départ`,
    select_correct_word: `Veuillez sélectionner le mot correct à chaque position dans la liste ci-dessous.`,
    enter_seed_phrase: `Entrez la phrase de départ`,
    enter_seed_phrase_instructions: `Entrez votre phrase de départ de 12 mots pour restaurer votre portefeuille existant`,
    paste: `Pâte`,
    restore_wallet: `Restaurer le portefeuille`,
    wallet_imported: `Portefeuille importé !`,
    wallet_imported_body: `Votre portefeuille est prêt à être utilisé.`,
    restore_existing_wallet: `Restaurez votre portefeuille existant`,
    restore_existing_wallet_instructions: ` Alors tu as déjà un portefeuille ? Remontons-le alors !`,
    restore_from: `Restauration à partir de`,
    restore_from_cloud_description: `Restaurez votre portefeuille depuis votre`,
    restore_with_seed_phrase: `Restaurer avec une phrase de départ`,
    restore_with_seed_phrase_description: `Utilisez votre phrase de départ pour restaurer un portefeuille MyDoge existant`,
    no_cloud_backup: `Pas de sauvegarde cloud`,
    no_cloud_backup_body: `Sauvegarde cloud introuvable. Veuillez restaurer à partir d'une phrase de départ ou créer un nouveau portefeuille`,
    create_wallet: `Créer un portefeuille`,
    already_have_wallet: ` J'ai déjà un portefeuille`,
    buy_send_receive_dogecoin: `Achetez, envoyez et recevez du Dogecoin`,
    send_doge_tips: `Envoyez des conseils Doge sur 𝕏, stockez votre Doge en toute sécurité et soyez votre propre banque`,
    shop_gift_cards_apparel: `Achetez des cartes-cadeaux et des vêtements`,
    buy_gift_cards: `Achetez des cartes-cadeaux avec Dogecoin ou achetez la dernière Doge Fashion`,
    enter_the_dogeverse: `Entrez dans le Dogeverse`,
    claim_dogtag: `Réclamez votre DogeTag, trouvez des amis, recevez des paiements avec votre lien et partagez des mèmes`,
    so_much_tip: `Alors pourboire, beaucoup Wow !`,
    success: `Succès`,
    sent_doge: `Vous avez envoyé`,
    some_doge: `un Doge !`,
    total: `Total`,
    done: `Fait`,
    shop_with_doge: `Achetez avec Doge`,
    oops: `Oops!`,
    no_comments_yet: `aucun commentaire pour l'instant`,
    to_post_a_comment: `poster un commentaire`,
    your_comment: `Votre commentaire`,
    post: `Poste`,
    delete: `Supprimer`,
    enable_push_notifications: `Activer les notifications push ?`,
    get_notifications_for_tips: `Recevoir des notifications pour les conseils et les messages`,
    no_thanks: `Non merci`,
    open_settings: `Ouvrir les paramètres`,
    swipe_for_more: `Faites glisser votre doigt vers le haut pour en savoir plus`,
    transaction_confirmation_alert: `Vérifiez toujours à qui vous envoyez avant de confirmer. N’envoyez jamais à une adresse de retrait d’échange. Les transactions Dogecoin ne peuvent pas être annulées !`,
    clear_amount: `Effacer le montant`,
    set_amount: `Fixer le montant`,
    save_qr: `Enregistrer le code QR`,
    WALLET_ADDRESS: `ADRESSE DU PORTEFEUILLE`,
    dogetag_link: `LIEN DOGETAG`,
    no_access_camera: `Pas d'accès à la caméra`,
    enable_camera_access_ios: `Activer l'accès à la caméra pour MyDoge`,
    grant_camera_permission_android: `Veuillez accorder l'autorisation de caméra à MyDoge`,
    scan_qr_payment: `Scannez le code QR pour effectuer un paiement`,
    select_image: `Sélectionnez une image`,
    find_friends_heading: `Trouver des amis sur MyDoge`,
    find_friends_description: `Autorisez l'accès aux contacts et facilitez la recherche d'amis et de contacts sur MyDoge.`,
    find_friends_button: `Retrouver des amis`,
    later_button: `je ferai ça plus tard`,
    own_address_error: `Vous ne pouvez pas envoyer à votre propre adresse`,
    invalid_address_error: `Adresse invalide`,
    results_title: `Résultats`,
    all: `Tous`,
    pending: `En attente`,
    enter_pin: `Entrez le code PIN`,
    enter_pin_to_confirm: `Entrez votre code PIN de portefeuille pour confirmer`,
    welcome_back: `Content de te revoir`,
    enter_wallet_pin: `Entrez votre code PIN de portefeuille`,
    forgot_pin: `Code PIN oublié`,
    forgot_pin_title: `Code PIN oublié`,
    forgot_pin_body: `Voulez-vous utiliser la biométrie pour déverrouiller votre portefeuille ?`,
    share: `Partager`,
    address_copied_to_clipboard: `Adresse copiée dans le presse-papiers`,
    follows_you: `Vous suit`,
    official_mydoge_profile: `Profil officiel MyDoge`,
    official_mydoge_commerce_profile: `Profil officiel de MyDoge Commerce`,
    official_foundation_profile: `Profil officiel de la Fondation`,
    follow_back: `Suivre`,
    follow: `Suivre`,
    tip: `Conseil`,
    share_profile: `Partager le profil`,
    unfollow: `Ne plus suivre`,
    unblock: `Débloquer`,
    block_or_report: `Bloquer ou signaler`,
    copy_profile_url: `Copier l'URL du profil`,
    memes_error: `Erreur lors du chargement des mèmes. Veuillez revenir en arrière et réessayer.`,
    user_profile_hidden: `Le profil utilisateur est masqué`,
    error_loading_profile: `Erreur de chargement du profil. Veuillez revenir en arrière et réessayer.`,
    uid_not_specified: `Erreur : UID non spécifié. Veuillez en informer le support.`,
    block_or_report_description: `MyDoge examinera tous les profils signalés pour toute activité contraire à nos directives. Vous pouvez également bloquer le profil pour ne plus voir leurs publications.`,
    nevermind: `Pas grave`,
    report: `Rapport`,
    block: `Bloc`,
    unblock_user: `Débloquer l'utilisateur?`,
    unblock_user_description: `Cela débloquera l'utilisateur et vous continuerez à voir ses publications.`,
    you_have_no_posts_yet: `Vous n'avez pas encore de messages`,
    no_posts_yet: `Pas encore de messages`,
    amount: `Montant`,
    custom: `Coutume`,
    add_a_message: `Ajouter un message`,
    find_friends: `Retrouver des amis`,
    cancel: `Annuler`,
    i_understand_continue: `Je comprends, continue`,
    hey_are_you_sure: `Hé! Es-tu sûr?`,
    delete_backup_confirmation: `Une fois que vous supprimez cette sauvegarde, vous perdez votre sauvegarde cloud, cette action ne peut pas être annulée`,
    all_transactions: `toutes transactions`,
    pending_transactions: `Transactions en attente`,
    view_on: "Voir sur", // View on
    invoice_id_copied: "Rechnungsnummer kopiert", // Invoice ID copied
    gift_card: "Geschenkkarte", // Gift Card
    invoice_id: "Rechnungsnummer", // Invoice ID
    support: "Unterstützung", // Support
    phone_number: "Telefonnummer", // Phone number
    whatsapp_verification_notice:
      "Über WhatsApp wird ein Bestätigungscode an Ihr Telefon gesendet", // A verification code will be sent to your phone via WhatsApp
    via_whatsapp: "per WhatsApp", // via WhatsApp
    you_may_not_have_backed_up_your_wallet:
      "Sie haben ein vorhandenes Backup in der Cloud, aber möglicherweise haben Sie Ihr aktuelles Wallet nicht gesichert.", // You have an existing backup on the cloud, but you may not have backed up your current wallet.
  },
};
