export const ko = {
  translation: {
    en: `English`,
    zh: `简体中文`,
    ja: `日本語`,
    ko: `한국어`,
    fr: `Français`,
    es: `Español`,
    pt: `Português`,
    de: `Deutsch`,
    preference: `선호`,
    disable_button_vibration: `버튼 진동 비활성화`,
    back: `뒤쪽에`,
    language: `언어`,
    app_theme: `앱 테마`,
    system: `체계`,
    dark: `어두운`,
    light: `빛`,
    settings: `설정`,
    backup_and_security: `백업 및 보안`,
    manage_wallet: `지갑 관리`,
    profile: `프로필`,
    app_preferences: `앱 환경설정`,
    notifications: `알림`,
    help_support: `도움말 및 지원`,
    about_my_doge: `내 총독 소개`,
    admin: `관리자`,
    i_cloud: `아이클라우드`,
    cloud: `구름`,
    youve_backed_up_to: `다음 날짜에 백업하셨습니다.`,
    you_havent_created_a_cloud_backup: `클라우드 백업을 생성하지 않았습니다.`,
    manage: `관리하다`,
    backup: `지원`,
    view_seed_phrase: `시드 문구 보기`,
    pin: `핀`,
    back_up_to: `백업 대상:`,
    back_up_your_wallet: `지갑을 백업하세요`,
    back_up_your_wallet_description: `지갑을 클라우드에 저장하고 비밀번호로 보호하세요. 또한 시드 문구를 적어두거나 비밀번호 관리자에 복사할 수도 있습니다.`,
    pin_description: `PIN을 잊어버린 경우 백업에서 지갑을 복원해야 합니다.`,
    change_pin: `PIN 변경`,
    your_pin_is_required: `결제하고 민감한 작업을 수행하려면 PIN이 필요합니다.`,
    use_fingerprint: `지문/얼굴 ID 사용`,
    ask_every_time_i_open_the_app: `앱을 열 때마다 묻습니다.`,
    this_will_remove_all_wallet: `이렇게 하면 기기에서 지갑 관련 데이터가 모두 삭제됩니다.`,
    delete_wallet: `지갑 삭제`,
    sign_in_to_the_dogeverse: `도지버스에 로그인하세요`,
    dogeverse_intro_description: `DogeTag를 요청하고, 친구를 찾고, 링크로 결제를 받고, Dogeverse의 콘텐츠에 참여하세요.`,
    sign_in: `로그인`,
    sign_in_description: `귀하의 전화번호는 로그인에만 사용되며 공개되지 않습니다.`,
    create_account_description: `Dogeverse에 가입하고 Shibes의 거대한 네트워크에 연결하세요.`,
    send_verification: `확인 보내기`,
    verify_your_phone_number: `전화번호 확인`,
    enter_the_code_sent_to: `전송된 코드를 입력하세요.`,
    resend_code: `코드 재전송`,
    wrong_number: `잘못된 번호`,
    confirm_code: `코드 확인`,
    youve_entered_the_verse: `당신은 구절을 입력했습니다`,
    youre_now_ready_to_explore_the_dogeverse: `이제 Dogeverse를 탐험할 준비가 되었습니다!`,
    lets_go: `갑시다!`,
    edit_profile: `프로필 수정`,
    social_connect: `소셜 연결`,
    profile_privacy: `프로필 개인정보 보호`,
    profile_is_public: `프로필이 공개됨`,
    show_wallet_address_and_tip_button: `지갑 주소 및 팁 버튼 표시`,
    preferences: `환경설정`,
    confirm_x_tips: `𝕏 팁 확인`,
    tips_received: `팁을 받았습니다`,
    new_followers: `새로운 추종자`,
    new_memes: `새로운 밈`,
    about_mydoge: `마이도지 소개`,
    terms_of_use: `이용약관`,
    privacy_policy: `개인 정보 정책`,
    share_mydoge: `MyDoge 공유`,
    visit_our_website: `우리 홈페이지에 방문 해주세요`,
    settings_and_support: `설정 및 지원`,
    connect_twitch: `트위치 연결`,
    connect_x: `연결𝕏`,
    create_a_post: `게시물 작성`,
    following: `수행원`,
    followers: `추종자`,
    recent_activity: `최근 활동`,
    history: `역사`,
    price: `가격`,
    usd: `USD`,
    txs: `TX`,
    hr: `시간`,
    send: `보내다`,
    receive: `받다`,
    buy: `구입하다`,
    scan: `주사`,
    from: `에서`,
    to: `에게`,
    note: `메모`,
    timestamp: `타임스탬프`,
    confirmations: `확인`,
    tx_hash: `TX 해시`,
    tx_hash_copied: `거래 해시가 복사되었습니다.`,
    note_copied: `메모가 복사되었습니다.`,
    address_copied: `주소가 복사되었습니다`,
    wallet: `지갑`,
    dogeverse: `도지버스`,
    shop: `가게`,
    receive_doge: `총독을 받다`,
    send_doge: `총독 보내기`,
    confirm_transaction: `거래 확인`,
    scan_qr_code: `QR 코드 스캔`,
    new_post: `새로운 게시물`,
    send_doge_alert_box_message: `DOGE를 친구에게 보내거나 지갑 주소 또는 MyDoge 사용자 이름을 입력할 수 있습니다.`,
    wallet_address_or_username: `지갑 주소 또는 사용자 이름`,
    saved_addresses: `저장된 주소`,
    add_new: `새로운 걸 더하다`,
    sending_to: `다음으로 보내는 중`,
    save: `구하다`,
    saved: `저장됨`,
    balance: `균형`,
    max: `맥스`,
    next: `다음`,
    network_fee: `네트워크 수수료`,
    max_tx_size_warning: `경고: 최대 트랜잭션 크기에 도달했습니다. 한 번에 보낼 수 있는 최대 한도입니다.`,
    confirm_transaction_warning: `확인하기 전에 항상 누구에게 보내는지 다시 확인하세요. 절대 거래소 출금 주소로 보내지 마세요. Dogecoin 거래는 되돌릴 수 없습니다!`,
    add_note: `메모를 추가`,
    wallet_address: `지갑 주소`,
    wallet_label: `지갑 라벨`,
    save_changes: `변경 사항을 저장하다`,
    save_address: `주소 저장`,
    enter_new_PIN: `새 PIN을 입력하세요.`,
    confirm_new_pin: `새 PIN 확인`,
    enter_new_PIN_description: `MyDoge 지갑에 대한 새 PIN을 입력하세요.`,
    enter_old_PIN: `이전 PIN을 입력하세요.`,
    enter_old_PIN_description: `MyDoge 지갑의 이전 PIN을 입력하세요.`,
    forgot_PIN: `PIN을 잊어버렸습니다`,
    confirm: `확인하다`,
    biometrics_confirmation: `생체 인식을 사용하여 지갑을 잠금 해제하시겠습니까?`,
    use_biometrics: `생체 인식 사용`,
    dismiss: `해고하다`,
    remove_wallet_data_description: ` 이렇게 하면 기기에서 지갑 관련 데이터가 모두 삭제됩니다.`,
    delete_profile_forever: `MyDoge 프로필을 영원히 삭제하세요`,
    sign_out: `로그아웃`,
    delete_wallet_confirmation: `여기요! 확실합니까?`,
    remove_wallet_description: `현재 지갑은 이 앱에서 제거되지만 블록체인에는 항상 존재합니다.`,
    remove_profile_assets_description: `귀하의 사용자 프로필과 자산이 제거되고 영구적으로 삭제됩니다. 이 작업은 취소할 수 없습니다.`,
    wallet_recovery_description: ` 귀하는 귀하의 지갑으로만 이 지갑을 복구할 수 있습니다.`,
    seed_phrase: `씨앗 문구`,
    no_seed_phrase: `MyDoge에는 귀하의 시드 문구가 없습니다.`,
    understand_continue: `이해합니다. 계속하세요.`,
    enter: `입력하다`,
    Delete: `삭제`,
    erase_wallet: `지갑을 지우려고`,
    and_profile_data: `및 프로필 데이터`,
    message: `메시지`,
    username: `사용자 이름`,
    edit: `편집하다`,
    new_address: `새 주소`,
    your_seed_phrase: `당신의 씨앗 문구 ✍️`,
    save_seed_phrase_instructions: ` 이 단어들을 순서대로 저장하세요. 적어서 안전한 곳에 보관하거나 비밀번호 관리자에 복사하세요.`,
    seed_phrase_warning: `귀하의 시드 문구는 지갑의 열쇠입니다. 이 문구를 아는 사람은 누구나 귀하의 자금에 접근할 수 있습니다. 자세히 알아보려면 탭하세요.`,
    copy: `복사`,
    hide: `숨다`,
    show: `보여주다`,
    screenshot_detected: `스크린샷이 감지되었습니다.`,
    screenshot_warning: `시드 문구의 스크린샷이나 기타 디지털 사본이 제3자에게 유출될 수 있습니다.`,
    okay: `좋아요`,
    seed_phrase_importance: `내 씨앗 문구는 얼마나 중요합니까?`,
    seed_phrase_explanation: `귀하의 시드 문구를 아는 사람은 누구나 귀하의 자금에 접근할 수 있습니다. 귀하의 시드 문구를 누구와도 공유하지 마십시오. MyDoge는 귀하의 시드 문구를 저장하지 않습니다. 귀하의 장치가 손상되거나, 분실 또는 도난당하거나, 기타 접근이 불가능할 경우, 귀하의 시드 문구가 귀하의 지갑을 복구할 수 있는 유일한 방법입니다.`,
    send_receive_tips_x: `𝕏을(를) 통해 팁 보내기 및 받기`,
    read_mydogetip_faq: `MyDogeTip FAQ 읽기`,
    connect_with_x: `𝕏와 연결`,
    start_receive_tips_twitch: `Twitch에서 팁 받기 시작`,
    visit_mydogetv_twitch: `자세한 내용은 Twitch의 MyDogeTV를 방문하세요.`,
    connect_with_twitch: `트위치와 연결`,
    screen_not_exist: `이 화면은 존재하지 않습니다.`,
    go_to_home_screen: `홈 화면으로 이동`,
    gift_cards: `기프트 카드`,
    backup_wallet: `새 지갑을 백업하세요`,
    backup_required: `자금을 보호하려면 백업이 필요합니다`,
    why_backups_important: `백업이 중요한 이유는 무엇입니까?`,
    learn_about_backups: `백업에 대해 알아보려면 탭하세요.`,
    backup_to: `백업 위치`,
    save_wallet_to_cloud: ` 지갑을 클라우드에 저장하고 비밀번호로 보호하세요`,
    write_on_paper: `종이에 쓰다`,
    write_down_seed_phrase: `시드 문구를 적어두거나 비밀번호 관리자에 저장하세요`,
    why_backups_important_description: `자기 관리권은 MyDoge 팀을 포함하여 누구도 귀하의 자금에 접근할 수 없음을 의미합니다. 백업은 장치가 손상되거나 분실 또는 도난당하거나 지워진 경우 지갑을 복원할 수 있는 유일한 방법입니다.`,
    choose_password: `비밀번호를 선택하세요`,
    use_memorable_password: `기억할 수 있는 비밀번호를 사용해주세요. 비밀번호가 길수록 더 안전합니다.`,
    more_secure_password: `기억할 수 있는 비밀번호를 사용해주세요. 비밀번호가 길수록 더 안전합니다.`,
    lose_password_lose_backup: `이 비밀번호를 분실하면 지갑 백업이 손실됩니다.`,
    password: `비밀번호`,
    confirm_password: `비밀번호 확인`,
    confirm_backup: `백업 확인`,
    overwrite_backup_title: `기존 백업을 덮어쓰시겠습니까?`,
    existing_wallet_overwrite_prompt: `이전에 클라우드에 백업된 기존 지갑이 있습니다. 덮어쓰시겠습니까?`,
    overwrite_backup: `백업 덮어쓰기`,
    import_existing_wallet: `기존 지갑 가져오기`,
    unknown_cloud_error: `알 수 없는 클라우드 오류`,
    unknown_cloud_error_body: `클라우드에 백업하는 중에 알 수 없는 오류가 발생했습니다.`,
    try_again_or_notify_support: `다시 시도하거나 MyDoge 지원팀에 알려주십시오.`,
    enter_recovery_password: `복구 비밀번호를 입력하세요`,
    enter_cloud_password_description: `클라우드에 시드 문구를 저장하는 데 사용한 비밀번호를 입력하세요`,
    import_wallet: `지갑 가져오기`,
    imported_wallet_title: `지갑을 가져왔습니다.`,
    imported_wallet_success: `지갑을 성공적으로 가져왔습니다!`,
    secure_new_wallet: `새 지갑을 안전하게 보호하세요`,
    set_pin: `6자리 PIN을 설정하세요`,
    reenter_pin: `6자리 PIN_LENGTH를 다시 ​​입력하세요.`,
    pin_payment_note: `지불금을 보내려면 PIN이 필요합니다.`,
    use_biometric: `지문/얼굴 ID 사용`,
    ask_every_time: `앱을 열 때마다 묻습니다.`,
    create_pin: `PIN 생성`,
    confirm_pin: `PIN 확인`,
    choose_dogeverse_username: `DogeTag 선택`,
    dogeverse_link: `귀하의 웹 링크는 다음과 같습니다.`,
    continue: `계속하다`,
    dogeverse_entry_title: `당신은 구절을 입력했습니다`,
    dogeverse_entry_body: `이제 Dogeverse를 탐험할 준비가 되었습니다!`,
    manual_backup_title: `씨앗 문구를 적어보세요`,
    save_words_order: `이 단어들을 순서대로 저장하세요. 적어서 안전한 곳에 보관하거나 비밀번호 관리자에 복사하세요.`,
    seed_phrase_key: `귀하의 시드 문구는 지갑의 열쇠입니다. 이 문구를 아는 사람은 누구나 귀하의 자금에 접근할 수 있습니다. 자세히 알아보려면 탭하세요.`,
    written_down: `적어놨어요`,
    screenshot_alert: `귀하의 Seed Phrase의 스크린샷이나 기타 디지털 사본이 제3자에게 유출될 수 있습니다.`,
    seed_phrase_access: ` 귀하의 시드 문구를 아는 사람은 누구나 귀하의 자금에 접근할 수 있습니다. 귀하의 시드 문구를 누구와도 공유하지 마십시오. MyDoge는 귀하의 시드 문구를 저장하지 않습니다. 귀하의 장치가 손상되거나, 분실 또는 도난당하거나, 기타 접근이 불가능할 경우, 귀하의 시드 문구가 귀하의 지갑을 복구할 수 있는 유일한 방법입니다.`,
    icloud_backup: `아이클라우드 백업`,
    cloud_backup: `클라우드 백업`,
    dont_lose_wallet: `지갑을 잃지 마세요!`,
    save_online_backup: `온라인 백업을 다음 위치에 저장하세요.`,
    icloud: `아이클라우드`,
    google_drive: `구글 드라이브`,
    do_this_later: `나중에 할게`,
    confirm_seed_phrase: `시드 문구 확인`,
    select_correct_word: `아래 목록에서 각 위치에 맞는 단어를 선택하세요.`,
    enter_seed_phrase: `시드 문구 입력`,
    enter_seed_phrase_instructions: `기존 지갑을 복원하려면 12단어 시드 문구를 입력하세요.`,
    paste: `반죽`,
    restore_wallet: `지갑 복원`,
    wallet_imported: `지갑을 수입했어요!`,
    wallet_imported_body: `지갑을 사용할 준비가 되었습니다.`,
    restore_existing_wallet: `기존 지갑을 복원하세요`,
    restore_existing_wallet_instructions: ` 그럼 지갑은 이미 갖고 계시나요? 그럼 다시 가져오자!`,
    restore_from: `다음에서 복원`,
    restore_from_cloud_description: `귀하의 지갑을 복원하십시오.`,
    restore_with_seed_phrase: `시드 문구로 복원`,
    restore_with_seed_phrase_description: `시드 문구를 사용하여 기존 MyDoge 지갑을 복원하세요.`,
    no_cloud_backup: `클라우드 백업 없음`,
    no_cloud_backup_body: `클라우드 백업을 찾을 수 없습니다. 시드 문구에서 복원하거나 새 지갑을 생성하세요`,
    create_wallet: `지갑 만들기`,
    already_have_wallet: ` 나에겐 이미 지갑이 있다`,
    buy_send_receive_dogecoin: `Dogecoin 구매, 보내기, 받기`,
    send_doge_tips: `𝕏에서 Doge 팁을 보내고 Doge를 안전하게 보관하고 나만의 은행이 되세요`,
    shop_gift_cards_apparel: `기프트 카드 및 의류 쇼핑`,
    buy_gift_cards: `Dogecoin으로 기프트 카드를 구매하거나 최신 Doge Fashion을 쇼핑하세요.`,
    enter_the_dogeverse: `도지버스에 들어가세요`,
    claim_dogtag: `DogeTag를 요청하고, 친구를 찾고, 링크로 결제를 받고, 밈을 공유하세요`,
    so_much_tip: `팁, 정말 와우!`,
    success: `성공`,
    sent_doge: `당신이 보냈습니다`,
    some_doge: `약간의 총독!`,
    total: `총`,
    done: `완료`,
    shop_with_doge: `Doge와 함께 쇼핑하세요`,
    oops: `이런!`,
    no_comments_yet: `아직 댓글이 없습니다`,
    to_post_a_comment: `댓글을 게시하려면`,
    your_comment: `귀하의 의견`,
    post: `우편`,
    delete: `삭제`,
    enable_push_notifications: `푸시 알림을 활성화하시겠습니까?`,
    get_notifications_for_tips: `팁과 메시지에 대한 알림 받기`,
    no_thanks: `고맙지 만 사양 할게`,
    open_settings: `설정 열기`,
    swipe_for_more: `더 많은 내용을 보려면 위로 스와이프하세요.`,
    transaction_confirmation_alert: `확인하기 전에 항상 누구에게 보내는지 다시 확인하세요. 절대 거래소 출금 주소로 보내지 마세요. Dogecoin 거래는 되돌릴 수 없습니다!`,
    clear_amount: `클리어 금액`,
    set_amount: `설정금액`,
    save_qr: `QR 저장`,
    WALLET_ADDRESS: `지갑 주소`,
    dogetag_link: `도지태그 링크`,
    no_access_camera: `카메라에 접근할 수 없습니다.`,
    enable_camera_access_ios: `MyDoge에 대한 카메라 액세스 활성화`,
    grant_camera_permission_android: `MyDoge에 카메라 권한을 부여해주세요`,
    scan_qr_payment: `결제하려면 QR 코드를 스캔하세요.`,
    select_image: `이미지 선택`,
    find_friends_heading: `MyDoge에서 친구 찾기`,
    find_friends_description: `연락처 액세스를 허용하고 MyDoge에서 친구와 연락처를 쉽게 찾을 수 있도록 하세요.`,
    find_friends_button: `친구를 찾아`,
    later_button: `나중에 할게`,
    own_address_error: `자신의 주소로 보낼 수 없습니다.`,
    invalid_address_error: `잘못된 주소`,
    results_title: `결과`,
    all: `모두`,
    pending: `보류 중`,
    enter_pin: `PIN 입력`,
    enter_pin_to_confirm: `확인하려면 월렛 PIN을 입력하세요.`,
    welcome_back: `돌아온 것을 환영합니다`,
    enter_wallet_pin: `월렛 PIN을 입력하세요.`,
    forgot_pin: `PIN을 잊어버렸습니다`,
    forgot_pin_title: `PIN을 잊어버렸습니다`,
    forgot_pin_body: `생체 인식을 사용하여 지갑을 잠금 해제하시겠습니까?`,
    share: `공유하다`,
    address_copied_to_clipboard: `주소가 클립보드에 복사되었습니다.`,
    follows_you: `당신을 따릅니다`,
    official_mydoge_profile: `공식 MyDoge 프로필`,
    official_mydoge_commerce_profile: `공식 MyDoge 상업 프로필`,
    official_foundation_profile: `공식 재단 프로필`,
    follow_back: `뒤로 팔로우`,
    follow: `따르다`,
    tip: `팁`,
    share_profile: `프로필 공유`,
    unfollow: `언팔로우`,
    unblock: `차단 해제`,
    block_or_report: `차단 또는 신고`,
    copy_profile_url: `프로필 URL 복사`,
    memes_error: `밈을 로드하는 중에 오류가 발생했습니다. 돌아가서 다시 시도해 주세요.`,
    user_profile_hidden: `사용자 프로필이 숨겨져 있습니다.`,
    error_loading_profile: `프로필을 로드하는 중에 오류가 발생했습니다. 돌아가서 다시 시도해 주세요.`,
    uid_not_specified: `오류: uid가 지정되지 않았습니다. 지원팀에 알려주세요.`,
    block_or_report_description: `MyDoge는 당사 지침에 반하는 모든 활동에 대해 보고된 모든 프로필을 검토합니다. 프로필을 차단하여 해당 게시물을 더 이상 볼 수도 없습니다.`,
    nevermind: `괜찮아요`,
    report: `보고서`,
    block: `차단하다`,
    unblock_user: `사용자 차단을 해제하시겠습니까?`,
    unblock_user_description: `이렇게 하면 해당 사용자의 차단이 해제되고 해당 사용자의 게시물을 계속 볼 수 있습니다.`,
    you_have_no_posts_yet: `아직 게시물이 없습니다.`,
    no_posts_yet: `아직 게시물이 없습니다`,
    amount: `양`,
    custom: `관습`,
    add_a_message: `메시지 추가`,
    find_friends: `친구를 찾아`,
    cancel: `취소`,
    i_understand_continue: `이해합니다. 계속하세요.`,
    hey_are_you_sure: `여기요! 확실합니까?`,
    delete_backup_confirmation: `이 백업을 삭제하면 클라우드 백업이 손실되며 이 작업은 취소할 수 없습니다.`,
    all_transactions: `모든 거래 창구`,
    pending_transactions: `보류중인 거래`,
  },
};
