export const pt = {
  translation: {
    en: 'English',
    zh: '简体中文',
    ja: '日本語',
    ko: '한국어',
    fr: 'Français',
    es: 'Español',
    pt: 'Português',
    preference: `Preferência`,
    disable_button_vibration: `Desativar vibração do botão`,
    back: `Voltar`,
    language: `Linguagem`,
    app_theme: `Tema do aplicativo`,
    system: `Sistema`,
    dark: `Escuro`,
    light: `Luz`,
    settings: `Configurações`,
    backup_and_security: `Cópia de segurança e segurança`,
    manage_wallet: `Gerenciar carteira`,
    profile: `Perfil`,
    app_preferences: `Preferências de aplicativos`,
    notifications: `Notificações`,
    help_support: `Ajuda e suporte`,
    about_my_doge: `Sobre Meu Doge`,
    admin: `Administrador`,
    i_cloud: `iCloud`,
    cloud: `nuvem`,
    youve_backed_up_to: `Você fez backup para`,
    you_havent_created_a_cloud_backup: `Você não criou um backup na nuvem`,
    manage: `Gerenciar`,
    backup: `Cópia de segurança`,
    view_seed_phrase: `Ver frase-semente`,
    pin: `ALFINETE`,
    back_up_to: `Fazer backup para`,
    back_up_your_wallet: `Faça backup da sua carteira`,
    back_up_your_wallet_description: `Salve sua carteira na nuvem e proteja-a com uma senha. Você também pode anotar sua frase-semente ou copiá-la para um gerenciador de senhas.`,
    pin_description: `Se você esquecer seu PIN, precisará restaurar sua carteira a partir de um backup.`,
    change_pin: `Alterar PIN`,
    your_pin_is_required: `Seu PIN é necessário para efetuar pagamentos e realizar ações confidenciais.`,
    use_fingerprint: `Usar impressão digital/identificação facial`,
    ask_every_time_i_open_the_app: `Perguntar sempre que eu abrir o aplicativo`,
    this_will_remove_all_wallet: `Isso removerá todos os dados relacionados à carteira do seu dispositivo.`,
    delete_wallet: `Excluir carteira`,
    sign_in_to_the_dogeverse: `Faça login no Dogeverse`,
    dogeverse_intro_description: `Reivindique sua DogeTag, encontre amigos, receba pagamentos com seu link e interaja com o conteúdo do Dogeverse.`,
    sign_in: `Entrar`,
    sign_in_description: `Seu número de telefone é usado apenas para fazer login e não será divulgado.`,
    create_account_description: `Junte-se ao Dogeverse e conecte-se a uma enorme rede de Shibes.`,
    send_verification: `Enviar verificação`,
    verify_your_phone_number: `Verifique seu número de telefone`,
    enter_the_code_sent_to: `Digite o código enviado para`,
    resend_code: `Reenviar código`,
    wrong_number: `Número errado`,
    confirm_code: `Confirmar código`,
    youve_entered_the_verse: `Você digitou o versículo`,
    youre_now_ready_to_explore_the_dogeverse: `Agora você está pronto para explorar o Dogeverse!`,
    lets_go: `Vamos!`,
    edit_profile: `Editar Perfil`,
    social_connect: `Conexão social`,
    profile_privacy: `Privacidade do Perfil`,
    profile_is_public: `O perfil é público`,
    show_wallet_address_and_tip_button: `Mostrar endereço da carteira e botão de gorjeta`,
    preferences: `Preferências`,
    confirm_x_tips: `Confirme 𝕏 Dicas`,
    tips_received: `Dicas recebidas`,
    new_followers: `Novos seguidores`,
    new_memes: `Novos memes`,
    about_mydoge: `Sobre MyDoge`,
    terms_of_use: `Termos de uso`,
    privacy_policy: `política de Privacidade`,
    share_mydoge: `Compartilhe MeuDoge`,
    visit_our_website: `Visite o nosso site`,
    settings_and_support: `Configurações e suporte`,
    connect_twitch: `Conectar Twitch`,
    connect_x: `Conecte 𝕏`,
    create_a_post: `Crie uma postagem`,
    following: `Seguindo`,
    followers: `Seguidores`,
    recent_activity: `Atividade recente`,
    history: `História`,
    price: `Preço`,
    usd: `USD`,
    txs: `TXs`,
    hr: `horas`,
    send: `Enviar`,
    receive: `Receber`,
    buy: `Comprar`,
    scan: `Varredura`,
    from: `De`,
    to: `Para`,
    note: `Observação`,
    timestamp: `Carimbo de data e hora`,
    confirmations: `Confirmações`,
    tx_hash: `Hash TX`,
    tx_hash_copied: `Hash de transação copiado`,
    note_copied: `Nota copiada`,
    address_copied: `Endereço copiado`,
    wallet: `Carteira`,
    dogeverse: `Dogeverse`,
    shop: `Comprar`,
    receive_doge: `Receba Doge`,
    send_doge: `Enviar Doge`,
    confirm_transaction: `Confirmar transação`,
    scan_qr_code: `Digitalize o código QR`,
    new_post: `Nova postagem`,
    send_doge_alert_box_message: `Você pode enviar DOGE para seus amigos, inserir um endereço de carteira ou um nome de usuário MyDoge`,
    wallet_address_or_username: `Endereço da carteira ou nome de usuário`,
    saved_addresses: `Endereços salvos`,
    add_new: `Adicionar novo`,
    sending_to: `Enviando para`,
    save: `Salvar`,
    saved: `Salvou`,
    balance: `Equilíbrio`,
    max: `Máx.`,
    next: `Próximo`,
    network_fee: `Taxa de rede`,
    max_tx_size_warning: `AVISO: O tamanho máximo da transação foi atingido. Este é o máximo que você pode enviar de uma vez.`,
    confirm_transaction_warning: `Sempre verifique para quem você está enviando antes de confirmar. Nunca envie para um endereço de retirada de exchange. As transações Dogecoin não podem ser revertidas!`,
    add_note: `Adicionar nota`,
    wallet_address: `Endereço da carteira`,
    wallet_label: `Etiqueta da carteira`,
    save_changes: `Salvar alterações`,
    save_address: `Salvar endereço`,
    enter_new_PIN: `Insira o novo PIN`,
    confirm_new_pin: `Confirme o novo PIN`,
    enter_new_PIN_description: `Insira seu novo PIN para sua carteira MyDoge`,
    enter_old_PIN: `Insira o PIN antigo`,
    enter_old_PIN_description: `Insira seu PIN antigo para sua carteira MyDoge`,
    forgot_PIN: `Esqueci o PIN`,
    confirm: `confirme`,
    biometrics_confirmation: `Quer usar biometria para desbloquear sua carteira?`,
    use_biometrics: `Use biometria`,
    dismiss: `Liberar`,
    remove_wallet_data_description: ` Isso removerá todos os dados relacionados à carteira do seu dispositivo.`,
    delete_profile_forever: `Exclua seu perfil MyDoge para sempre`,
    sign_out: `Sair`,
    delete_wallet_confirmation: `Ei! Tem certeza?`,
    remove_wallet_description: `Sua carteira atual será removida deste aplicativo, porém sempre existirá no blockchain.`,
    remove_profile_assets_description: `Seu perfil de usuário e ativos serão removidos e excluídos permanentemente. Essa ação não pode ser desfeita.`,
    wallet_recovery_description: ` Você SÓ pode recuperar esta carteira com seu`,
    seed_phrase: `FRASE SEMENTE`,
    no_seed_phrase: `MyDoge não tem sua frase-semente.`,
    understand_continue: `entendi, continue`,
    enter: `Digitar`,
    Delete: `Excluir`,
    erase_wallet: `para apagar sua carteira`,
    and_profile_data: `e dados de perfil`,
    message: `Mensagem`,
    username: `Nome de usuário`,
    edit: `Editar`,
    new_address: `Novo endereço`,
    your_seed_phrase: `Sua frase-semente ✍️`,
    save_seed_phrase_instructions: ` Guarde estas palavras, em ordem. Anote-os e guarde-os em algum lugar seguro ou copie-os para um gerenciador de senhas.`,
    seed_phrase_warning: `Sua Seed Phrase é a chave da sua carteira. Qualquer pessoa com esta frase pode acessar seus fundos. Toque para saber mais`,
    copy: `cópia de`,
    hide: `Esconder`,
    show: `Mostrar`,
    screenshot_detected: `Captura de tela detectada`,
    screenshot_warning: `Capturas de tela ou outras cópias digitais de sua frase-semente podem vazar para terceiros.`,
    okay: `OK`,
    seed_phrase_importance: `Quão importante é minha frase-semente?`,
    seed_phrase_explanation: `Qualquer pessoa com sua Seed Phrase pode acessar seus fundos. Não compartilhe sua frase-semente com ninguém. MyDoge não salva sua frase-semente para você. Caso seu dispositivo seja danificado, perdido ou roubado, ou de outra forma inacessível, sua Seed Phrase é a única maneira de recuperar sua carteira.`,
    send_receive_tips_x: `Envie e receba dicas via 𝕏`,
    read_mydogetip_faq: `Leia as perguntas frequentes do MyDogeTip`,
    connect_with_x: `Conecte-se com 𝕏`,
    start_receive_tips_twitch: `Comece a receber dicas no Twitch`,
    visit_mydogetv_twitch: `Visite MyDogeTV no Twitch para mais informações`,
    connect_with_twitch: `Conecte-se com o Twitch`,
    screen_not_exist: `Esta tela não existe.`,
    go_to_home_screen: `Vá para a tela inicial`,
    gift_cards: `Cartões de presente`,
    backup_wallet: `Faça backup de sua nova carteira`,
    backup_required: `É necessário um backup para proteger seus fundos`,
    why_backups_important: `Por que os backups são importantes?`,
    learn_about_backups: `Toque para saber mais sobre backups`,
    backup_to: `Backup para`,
    save_wallet_to_cloud: ` Salve sua carteira na nuvem e proteja-a com uma senha`,
    write_on_paper: `Escreva no papel`,
    write_down_seed_phrase: `Anote sua frase-semente ou salve-a em um gerenciador de senhas`,
    why_backups_important_description: `A autocustódia significa que ninguém mais pode acessar seus fundos, nem mesmo a equipe MyDoge. Um backup é a única maneira de restaurar sua carteira caso seu dispositivo seja danificado, perdido, roubado ou apagado.`,
    choose_password: `Escolha uma senha`,
    use_memorable_password: `Por favor, use uma senha que você possa lembrar. Senhas mais longas são mais seguras.`,
    more_secure_password: `Por favor, use uma senha que você possa lembrar. Senhas mais longas são mais seguras.`,
    lose_password_lose_backup: `Se você perder essa senha, perderá o backup da sua carteira.`,
    password: `Senha`,
    confirm_password: `Confirme sua senha`,
    confirm_backup: `Confirmar backup`,
    overwrite_backup_title: `Substituir o backup existente?`,
    existing_wallet_overwrite_prompt: `Você tem uma carteira existente com backup prévio na nuvem. Você deseja sobrescrever isso?`,
    overwrite_backup: `Substituir backup`,
    import_existing_wallet: `Importar carteira existente`,
    unknown_cloud_error: `Erro de nuvem desconhecido`,
    unknown_cloud_error_body: `Ocorreu um erro desconhecido ao fazer backup na nuvem.`,
    try_again_or_notify_support: `Tente novamente ou notifique o suporte MyDoge.`,
    enter_recovery_password: `Digite a senha de recuperação`,
    enter_cloud_password_description: `Digite a senha que você usou para armazenar sua frase inicial na nuvem`,
    import_wallet: `Importar carteira`,
    imported_wallet_title: `Você importou sua carteira`,
    imported_wallet_success: `Você importou sua carteira com sucesso!`,
    secure_new_wallet: `Proteja sua nova carteira`,
    set_pin: `Defina um PIN de 6 dígitos`,
    reenter_pin: `Digite novamente o PIN_LENGTH de 6 dígitos`,
    pin_payment_note: `Você precisará do seu PIN para enviar pagamentos`,
    use_biometric: `Usar impressão digital/identificação facial`,
    ask_every_time: `Perguntar sempre que eu abrir o aplicativo`,
    create_pin: `Criar PIN`,
    confirm_pin: `Confirmar PIN`,
    choose_dogeverse_username: `Escolha uma DogeTag`,
    dogeverse_link: `Seu link da web será`,
    continue: `Continuar`,
    dogeverse_entry_title: `Você digitou o versículo`,
    dogeverse_entry_body: `Agora você está pronto para explorar o Dogeverse!`,
    manual_backup_title: `Escreva a frase-semente`,
    save_words_order: `Guarde estas palavras, em ordem. Anote-os e guarde-os em algum lugar seguro ou copie-os para um gerenciador de senhas.`,
    seed_phrase_key: `Sua Seed Phrase é a chave da sua carteira. Qualquer pessoa com esta frase pode acessar seus fundos. Toque para saber mais`,
    written_down: `Eu escrevi isso`,
    screenshot_alert: `Capturas de tela ou outras cópias digitais de sua frase-semente podem vazar para terceiros.`,
    seed_phrase_access: ` Qualquer pessoa com sua Seed Phrase pode acessar seus fundos. Não compartilhe sua frase-semente com ninguém. MyDoge não salva sua frase-semente para você. Caso seu dispositivo seja danificado, perdido ou roubado, ou de outra forma inacessível, sua Seed Phrase é a única maneira de recuperar sua carteira.`,
    icloud_backup: `Backup do iCloud`,
    cloud_backup: `Backup na nuvem`,
    dont_lose_wallet: `Não perca sua carteira!`,
    save_online_backup: `Salve um backup on-line em`,
    icloud: `iCloud`,
    google_drive: `Google Drive`,
    do_this_later: `Farei isso mais tarde`,
    confirm_seed_phrase: `Confirmar frase-semente`,
    select_correct_word: `Selecione a palavra correta em cada posição na lista abaixo.`,
    enter_seed_phrase: `Insira a frase-semente`,
    enter_seed_phrase_instructions: `Digite sua frase inicial de 12 palavras para restaurar sua carteira existente`,
    paste: `Colar`,
    restore_wallet: `Restaurar carteira`,
    wallet_imported: `Carteira importada!`,
    wallet_imported_body: `Sua carteira está pronta para uso.`,
    restore_existing_wallet: `Restaure sua carteira existente`,
    restore_existing_wallet_instructions: ` Então você já tem uma carteira? Vamos trazer isso de volta então!`,
    restore_from: `Restaurar de`,
    restore_from_cloud_description: `Restaure sua carteira do seu`,
    restore_with_seed_phrase: `Restaurar com uma frase-semente`,
    restore_with_seed_phrase_description: `Use sua frase inicial para restaurar uma carteira MyDoge existente`,
    no_cloud_backup: `Sem backup na nuvem`,
    no_cloud_backup_body: `Backup na nuvem não encontrado. Restaure a partir de uma frase inicial ou crie uma nova carteira`,
    create_wallet: `Crie uma carteira`,
    already_have_wallet: ` Eu já tenho uma carteira`,
    buy_send_receive_dogecoin: `Compre, envie e receba Dogecoin`,
    send_doge_tips: `Envie dicas do Doge em 𝕏, guarde seu Doge com segurança e seja seu próprio banco`,
    shop_gift_cards_apparel: `Compre vales-presente e roupas`,
    buy_gift_cards: `Compre cartões-presente com Dogecoin ou compre as últimas novidades da Doge Fashion`,
    enter_the_dogeverse: `Entre no Dogeverse`,
    claim_dogtag: `Reivindique sua DogeTag, encontre amigos, receba pagamentos com seu link e compartilhe memes`,
    so_much_tip: `Então dica, muito uau!`,
    success: `Sucesso`,
    sent_doge: `Você enviou`,
    some_doge: `algum Doge!`,
    total: `Total`,
    done: `Feito`,
    shop_with_doge: `Compre com Doge`,
    oops: `Ops!`,
    no_comments_yet: `Ainda não há comentários`,
    to_post_a_comment: `postar um comentário`,
    your_comment: `Seu comentário`,
    post: `Publicar`,
    delete: `Excluir`,
    enable_push_notifications: `Ativar notificações push?`,
    get_notifications_for_tips: `Receba notificações de dicas e mensagens`,
    no_thanks: `Não, obrigado`,
    open_settings: `Abrir configurações`,
    swipe_for_more: `Deslize para cima para ver mais`,
    transaction_confirmation_alert: `Sempre verifique para quem você está enviando antes de confirmar. Nunca envie para um endereço de retirada de exchange. As transações Dogecoin não podem ser revertidas!`,
    clear_amount: `Limpar valor`,
    set_amount: `Definir valor`,
    save_qr: `Salvar QR`,
    WALLET_ADDRESS: `ENDEREÇO ​​DA CARTEIRA`,
    dogetag_link: `LINK DOGETAG`,
    no_access_camera: `Sem acesso à câmera`,
    enable_camera_access_ios: `Habilite o acesso à câmera para MyDoge`,
    grant_camera_permission_android: `Por favor, conceda permissão de câmera ao MyDoge`,
    scan_qr_payment: `Digitalize o código QR para efetuar um pagamento`,
    select_image: `Selecione a imagem`,
    find_friends_heading: `Encontre amigos no MyDoge`,
    find_friends_description: `Permita o acesso aos contatos e facilite a localização de amigos e contatos no MyDoge.`,
    find_friends_button: `Encontre amigos`,
    later_button: `Farei isso mais tarde`,
    own_address_error: `Você não pode enviar para seu próprio endereço`,
    invalid_address_error: `Endereço inválido`,
    results_title: `Resultados`,
    all: `Todos`,
    pending: `Pendente`,
    enter_pin: `Entrar no pino`,
    enter_pin_to_confirm: `Digite seu PIN da carteira para confirmar`,
    welcome_back: `bem vindo de volta`,
    enter_wallet_pin: `Insira o PIN da sua carteira`,
    forgot_pin: `Esqueci o PIN`,
    forgot_pin_title: `Esqueci o PIN`,
    forgot_pin_body: `Quer usar biometria para desbloquear sua carteira?`,
    share: `Compartilhar`,
    address_copied_to_clipboard: `Endereço copiado para a área de transferência`,
    follows_you: `Segue você`,
    official_mydoge_profile: `Perfil oficial do MyDoge`,
    official_mydoge_commerce_profile: `Perfil oficial de comércio MyDoge`,
    official_foundation_profile: `Perfil Oficial da Fundação`,
    follow_back: `Seguir de volta`,
    follow: `Seguir`,
    tip: `Dica`,
    share_profile: `Compartilhar perfil`,
    unfollow: `Deixar de seguir`,
    unblock: `Desbloquear`,
    block_or_report: `Bloquear ou denunciar`,
    copy_profile_url: `Copiar URL do perfil`,
    memes_error: `Erro ao carregar memes. Por favor volte e tente novamente.`,
    user_profile_hidden: `O perfil do usuário está oculto`,
    error_loading_profile: `Erro ao carregar o perfil. Por favor volte e tente novamente.`,
    uid_not_specified: `Erro: uid não especificado. Por favor, notifique o suporte.`,
    block_or_report_description: `MyDoge analisará todos os perfis relatados para qualquer atividade de acordo com nossas diretrizes. Você também pode bloquear o perfil para parar de ver suas postagens.`,
    nevermind: `Deixa para lá`,
    report: `Relatório`,
    block: `Bloquear`,
    unblock_user: `Desbloquear usuário?`,
    unblock_user_description: `Isso desbloqueará o usuário e você continuará vendo suas postagens.`,
    you_have_no_posts_yet: `Você ainda não tem postagens`,
    no_posts_yet: `Nenhuma postagem ainda`,
    amount: `Quantia`,
    custom: `Personalizado`,
    add_a_message: `Adiciona uma mensagem`,
    find_friends: `Encontre amigos`,
    cancel: `Cancelar`,
    i_understand_continue: `entendi, continue`,
    hey_are_you_sure: `Ei! Tem certeza?`,
    delete_backup_confirmation: `Depois de excluir este backup, você perderá seu backup na nuvem, esta ação não pode ser desfeita`,
    all_transactions: `todas as transacções`,
    pending_transactions: `Transações pendentes`,
  },
};
