// Portuguese translation
export const pt = {
  translation: {
    en: "English",
    zh: "简体中文",
    ja: "日本語",
    ko: "한국어",
    fr: "Français",
    es: "Español",
    pt: "Português",
    de: "Deutsch",
    vn: "Tiếng Việt",
    preference: "Preferência",
    disable_button_vibration: "Desativar a vibração do botão",
    back: "Voltar",
    language: "Idioma",
    app_theme: "Tema",
    system: "Sistema",
    dark: "Escuro",
    light: "Claro",
    settings: "Configurações",
    backup_and_security: "Cópia de segurança e segurança",
    manage_wallet: "Gesão de carteira",
    profile: "Perfil",
    app_preferences: "Definições",
    notifications: "Notificações",
    help_support: "Ajuda e suporte",
    about_my_doge: "Sobre o My Doge",
    admin: "Administrador",
    i_cloud: "iCloud",
    cloud: "nuvem",
    youve_backed_up_to: "Fez um backup para",
    you_havent_created_a_cloud_backup: "Não criou um backup na nuvem",
    manage: "Gerir",
    backup: "Cópia de segurança",
    view_seed_phrase: "Ver seed-phrase",
    pin: "Marcador",
    back_up_to: "Backup para",
    back_up_your_wallet: "Faça o backup da sua carteira",
    back_up_your_wallet_description: "Grave a sua carteira na nuvem e proteja-a com uma palavra passe. Também pode anotar sua frase-semente ou copiá-la para um gerenciador de palavras passe.",
    pin_description: "Se não se lemrar do seu PIN, precisará de restaurar a sua carteira a partir de um backup.",
    change_pin: "Alterar PIN",
    your_pin_is_required: "O PIN é necessário para efetuar pagamentos e realizar ações confidenciais.",
    use_fingerprint: "Utilize a impressão digital e/ou a identificação facial",
    ask_every_time_i_open_the_app: "Perguntar sempre que eu abrir a aplicação",
    this_will_remove_all_wallet: "Irá remover todos os dados relativos à carteira na sua aplicação.",
    delete_wallet: "Apagar carteira",
    sign_in_to_the_dogeverse: "Entre no Dogeverse",
    dogeverse_intro_description: "Reivindique a sua DogeTag, encontre amigos, receba pagamentos com o seu link e interaja com o conteúdo do Dogeverse.",
    sign_in: "Iniciar Sessão",
    sign_in_description: "O seu número de telefone é utilizado apenas para iniciar sessão e não será divulgado.",
    create_account_description: "Junte-se ao Dogeverse e conecte-se a uma enorme rede de Shibes.",
    send_verification: "Enviar Verificação",
    verify_your_phone_number: "Verifique o Seu Número de Telefone",
    enter_the_code_sent_to: "Digite o Código Enviado para",
    resend_code: "Reenviar Código",
    wrong_number: "Número Errado",
    confirm_code: "Confirmar Código",
    youve_entered_the_verse: "Entrou no verse",
    youre_now_ready_to_explore_the_dogeverse: "Agora está pronto para explorar o Dogeverse!",
    lets_go: "Vamos!",
    edit_profile: "Editar Perfil",
    social_connect: "Conexão social",
    profile_privacy: "Privacidade do Perfil",
    profile_is_public: "O perfil é público",
    show_wallet_address_and_tip_button: "Mostrar endereço da carteira e botão de gorjeta",
    preferences: "Preferências",
    confirm_x_tips: "Confirme 𝕏 Dicas",
    tips_received: "Dicas recebidas",
    new_followers: "Novos seguidores",
    new_memes: "Novos memes",
    about_mydoge: "Sobre MyDoge",
    terms_of_use: "Termos de uso",
    privacy_policy: "política de Privacidade",
    share_mydoge: "Compartilhe MyDoge",
    visit_our_website: "Visite o nosso site",
    settings_and_support: "Configurações e suporte",
    connect_twitch: "Conectar Twitch",
    connect_x: "Conecte 𝕏",
    create_a_post: "Crie uma publicação",
    following: "Seguindo",
    followers: "Seguidores",
    recent_activity: "Atividade recente",
    history: "História",
    price: "Preço",
    usd: "USD",
    txs: "TXs",
    hr: "horas",
    send: "Enviar",
    receive: "Receber",
    buy: "Comprar",
    scan: "Verificar",
    from: "De",
    to: "Para",
    note: "Observação",
    timestamp: "Carimbo da data e hora",
    confirmations: "Confirmações",
    tx_hash: "Hash TX",
    tx_hash_copied: "Hash de transação copiado",
    note_copied: "Nota copiada",
    address_copied: "Endereço copiado",
    wallet: "Carteira",
    dogeverse: "Dogeverse",
    shop: "Comprar",
    receive_doge: "Receba Doge",
    send_doge: "Enviar Doge",
    confirm_transaction: "Confirmar transação",
    scan_qr_code: "Ler o código QR",
    new_post: "Nova publicação",
    send_doge_alert_box_message: "Pode enviar DOGE para os seus amigos, inserir um endereço de carteira ou um nome de utilizador MyDoge",
    wallet_address_or_username: "Endereço da carteira ou nome de utilizador",
    saved_addresses: "Endereços gravador",
    add_new: "Adicionar novo",
    sending_to: "Enviando para",
    save: "Gravar",
    saved: "Gravou",
    balance: "Saldo",
    max: "Máx.",
    next: "Seguinte",
    network_fee: "Taxa da rede",
    max_tx_size_warning: "AVISO: O tamanho máximo da transação foi atingido. Este é o máximo que pode enviar de uma vez.",
    confirm_transaction_warning: "Verifique sempre para quem está a enviar antes de confirmar. Nunca envie para um endereço de levantamento de uma exchange. As transações Dogecoin não podem ser revertidas!",
    add_note: "Adicionar nota",
    wallet_address: "Endereço da carteira",
    wallet_label: "Etiqueta da carteira",
    save_changes: "Gravar alterações",
    save_address: "Gravar endereço",
    enter_new_PIN: "Introduza o novo PIN",
    confirm_new_pin: "Confirme o novo PIN",
    enter_new_PIN_description: "Introduza o novo PIN para a sua carteira MyDoge",
    enter_old_PIN: "Introduza o PIN antigo",
    enter_old_PIN_description: "Introduza o PIN antigo para a sua carteira MyDoge",
    forgot_PIN: "Esqueci-me do PIN",
    confirm: "confirmar",
    biometrics_confirmation: "Quer utilizar a biometria para desbloquear a sua carteira?",
    use_biometrics: "Utilizar biometria",
    dismiss: "Dispensar",
    remove_wallet_data_description: " Isso irá remover todos os dados relacionados à carteira do seu dispositivo.",
    delete_profile_forever: "Remover o seu perfil MyDoge para sempre",
    sign_out: "Sair",
    delete_wallet_confirmation: "Ei! Tem certeza?",
    remove_wallet_description: "A sua carteira atual será removida deste aplicativo, porém sempre existirá no blockchain.",
    remove_profile_assets_description: "O seu perfil de utilizador e ativos serão removidos e apagados permanentemente. Essa ação não pode ser revertida.",
    wallet_recovery_description: " Só pode recuperar esta carteira com a sua",
    seed_phrase: "FRASE SEMENTE",
    no_seed_phrase: "MyDoge não tem a sua frase-semente.",
    understand_continue: "entendi, continue",
    enter: "Introduzir",
    Delete: "Apagar",
    erase_wallet: "para apagar a sua carteira",
    and_profile_data: "e dados de perfil",
    message: "Mensagem",
    username: "Nome de utilizador",
    edit: "Editar",
    new_address: "Novo endereço",
    your_seed_phrase: "Sua frase-semente ✍️",
    save_seed_phrase_instructions: " Guarde estas palavras, em ordem. Anote-os e guarde-os em algum lugar seguro ou copie-os para um gerenciador de palavras passe.",
    seed_phrase_warning: "A frase-semente é a chave da sua carteira. Qualquer pessoa com esta frase pode aceder aos seus fundos. Toque para saber mais",
    copy: "cópia de",
    hide: "Esconder",
    show: "Mostrar",
    screenshot_detected: "Captura de ecrã detectada",
    screenshot_warning: "Capturas de ecrã ou outras cópias digitais da sua frase-semente podem parar a terceiros.",
    okay: "OK",
    seed_phrase_importance: "Quão importante é minha frase-semente?",
    seed_phrase_explanation: "Qualquer pessoa com sua Seed Phrase pode acessar seus fundos. Não compartilhe sua frase-semente com ninguém. MyDoge não salva sua frase-semente para você. Caso seu dispositivo seja danificado, perdido ou roubado, ou de outra forma inacessível, sua Seed Phrase é a única maneira de recuperar sua carteira.",
    send_receive_tips_x: "Envie e receba grojetas via 𝕏",
    read_mydogetip_faq: "Leia as perguntas frequentes do MyDogeTip",
    connect_with_x: "Conecte-se com 𝕏",
    start_receive_tips_twitch: "Comece a receber grojetas no Twitch",
    visit_mydogetv_twitch: "Visite o MyDogeTV no Twitch para mais informações",
    connect_with_twitch: "Conecte-se com o Twitch",
    screen_not_exist: "Este ecrã não existe.",
    go_to_home_screen: "Ir para o ecrã inicial",
    gift_cards: "Cartões presente",
    backup_wallet: "Faça backup de sua nova carteira",
    backup_required: "É necessário um backup para proteger seus fundos",
    why_backups_important: "Por que os backups são importantes?",
    learn_about_backups: "Toque para saber mais sobre backups",
    backup_to: "Backup para",
    save_wallet_to_cloud: " Grave a sua carteira na nuvem e proteja-a com uma palavra passe",
    write_on_paper: "Escreva no papel",
    write_down_seed_phrase: "Anote a sua frase-semente ou grave num gestor de palavras passe",
    why_backups_important_description: "A auto-custódia significa que ninguém mais pode aceder ao seu saldo, nem mesmo a equipa MyDoge. Um backup é a única maneira de restaurar a sua carteira caso o seu dispositivo seja danificado, perdido, roubado ou apagado.",
    choose_password: "Escolha uma palavra passe",
    use_memorable_password: "Por favor, utilize uma palavra passe que se possa lembrar. palavras passe mais longas são mais seguras.",
    more_secure_password: "Por favor, utilize uma palavra passe que se possa lembrar. palavras passe mais longas são mais seguras.",
    lose_password_lose_backup: "Se perder essa palavra passe, perderá o backup da sua carteira.",
    password: "palavra passe",
    confirm_password: "Confirme a sua palavra passe",
    confirm_backup: "Confirmar backup",
    overwrite_backup_title: "Substituir o backup existente?",
    existing_wallet_overwrite_prompt: "Tem uma carteira existente com backup prévio na nuvem. Deseja substituir isso?",
    overwrite_backup: "Substituir backup",
    import_existing_wallet: "Importar carteira existente",
    unknown_cloud_error: "Erro de nuvem desconhecido",
    unknown_cloud_error_body: "Ocorreu um erro desconhecido ao fazer backup na nuvem.",
    try_again_or_notify_support: "Tente novamente ou notifique o suporte MyDoge.",
    enter_recovery_password: "Introduza a palavra passe de recuperação",
    enter_cloud_password_description: "Insira a palavra passe que utilizou para gravar a sua frase inicial na nuvem",
    import_wallet: "Importar carteira",
    imported_wallet_title: "Importou a sua carteira",
    imported_wallet_success: "Importou a sua carteira com sucesso!",
    secure_new_wallet: "Proteja a sua nova carteira",
    set_pin: "Defina um PIN de 6 dígitos",
    reenter_pin: "Insira novamente o PIN_LENGTH de 6 dígitos",
    pin_payment_note: "Irá precisar do seu PIN para enviar pagamentos",
    use_biometric: "Utilizar a impressão digital e/ou a identificação facial",
    ask_every_time: "Perguntar sempre que eu abrir a aplicação",
    create_pin: "Criar PIN",
    confirm_pin: "Confirmar PIN",
    choose_dogeverse_username: "Escolha uma DogeTag",
    dogeverse_link: "O seu link da web será",
    continue: "Continuar",
    dogeverse_entry_title: "Digitou o versículo",
    dogeverse_entry_body: "Agora está pronto para explorar o Dogeverse!",
    manual_backup_title: "Escreva a frase-semente",
    save_words_order: "Guarde estas palavras, em ordem. Anote-as e guarde-as em algum lugar seguro ou copie-os para um gestor de palavras passe.",
    seed_phrase_key: "A sua frase-semente é a chave da sua carteira. Qualquer pessoa com esta frase pode aceder ao seu saldo. Toque para saber mais",
    written_down: "Eu apontei",
    screenshot_alert: "Capturas de tela ou outras cópias digitais de sua frase-semente podem permitir o acesso a terceiros.",
    seed_phrase_access: " Qualquer pessoa com a sua frase-semente pode ter acesso ao seu saldo. Não partilhe a sua frase-semente com ninguém. MyDoge não grava a sua frase-semente por si. Caso o seu dispositivo seja danificado, perdido ou roubado, ou de outra forma inacessível, a sua frase-semente é a única maneira de recuperar a sua carteira.",
    icloud_backup: "Backup do iCloud",
    cloud_backup: "Backup na nuvem",
    dont_lose_wallet: "Não perca sua carteira!",
    save_online_backup: "Salve um backup on-line em",
    icloud: "iCloud",
    google_drive: "Google Drive",
    do_this_later: "Farei isso mais tarde",
    confirm_seed_phrase: "Confirmar frase-semente",
    select_correct_word: "Selecione a palavra correta em cada posição na lista abaixo.",
    enter_seed_phrase: "Insira a frase-semente",
    enter_seed_phrase_instructions: "Introduza a sua frase inicial de 12 palavras para restaurar a sua carteira existente",
    paste: "Colar",
    restore_wallet: "Restaurar carteira",
    wallet_imported: "Carteira importada!",
    wallet_imported_body: "A sua carteira está pronta para uso.",
    restore_existing_wallet: "Restaure a sua carteira existente",
    restore_existing_wallet_instructions: " Então já tem uma carteira? Vamos trazer isso de volta então!",
    restore_from: "Restaurar de",
    restore_from_cloud_description: "Restaure a sua carteira do seu",
    restore_with_seed_phrase: "Restaurar com uma frase-semente",
    restore_with_seed_phrase_description: "Utilize a sua frase inicial para restaurar uma carteira MyDoge existente",
    no_cloud_backup: "Sem backup na nuvem",
    no_cloud_backup_body: "Backup na nuvem não encontrado. Restaure a partir de uma frase inicial ou crie uma nova carteira",
    create_wallet: "Crie uma carteira",
    already_have_wallet: " Eu já tenho uma carteira",
    buy_send_receive_dogecoin: "Compre, envie e receba Dogecoin",
    send_doge_tips: "Envie dicas do Doge em 𝕏, guarde seu Doge com segurança e seja seu próprio banco",
    shop_gift_cards_apparel: "Compre vales-presente e roupas",
    buy_gift_cards: "Compre cartões-presente com Dogecoin ou compre as últimas novidades da Doge Fashion",
    enter_the_dogeverse: "Entre no Dogeverse",
    claim_dogtag: "Reivindique a sua DogeTag, encontre amigos, receba pagamentos com o seu link e compartilhe memes",
    so_much_tip: "Tanta Grojeta, uau!",
    success: "Sucesso",
    sent_doge: "Enviou",
    some_doge: "algum Doge!",
    total: "Total",
    done: "Feito",
    shop_with_doge: "Compre com Doge",
    oops: "Ops!",
    no_comments_yet: "Ainda não há comentários",
    to_post_a_comment: "publicar um comentário",
    your_comment: "Seu comentário",
    post: "Publicar",
    delete: "Excluir",
    enable_push_notifications: "Ativar notificações push?",
    get_notifications_for_tips: "Receba notificações de dicas e mensagens",
    no_thanks: "Não, obrigado",
    open_settings: "Abrir configurações",
    swipe_for_more: "Deslize para cima para ver mais",
    transaction_confirmation_alert: "Verifique para quem está a enviar antes de confirmar. Nunca envie para um endereço de envio de uma exchange. As transações Dogecoin não podem ser revertidas!",
    clear_amount: "Limpar valor",
    set_amount: "Definir valor",
    save_qr: "Gravar QR",
    WALLET_ADDRESS: "ENDEREÇO ​​DA CARTEIRA",
    dogetag_link: "LINK DOGETAG",
    no_access_camera: "Sem acesso à câmera",
    enable_camera_access_ios: "Active o acesso à câmera para o MyDoge",
    grant_camera_permission_android: "Por favor, conceda permissão da câmera ao MyDoge",
    scan_qr_payment: "Leia o código QR para efetuar um pagamento",
    select_image: "Selecione a imagem",
    find_friends_heading: "Encontre amigos no MyDoge",
    find_friends_description: "Permita o acesso aos contatos e facilite a localização de amigos e contatos no MyDoge.",
    find_friends_button: "Encontre amigos",
    later_button: "Mais tarde",
    own_address_error: "Não pode enviar para o seu próprio endereço",
    invalid_address_error: "Endereço inválido",
    results_title: "Resultados",
    all: "Todos",
    pending: "Pendente",
    enter_pin: "Entrar no pin",
    enter_pin_to_confirm: "Introduza o seu PIN da carteira para confirmar",
    welcome_back: "bem vindo de volta",
    enter_wallet_pin: "Insira o PIN da sua carteira",
    forgot_pin: "Esqueci-me do PIN",
    forgot_pin_title: "Esqueci-me do PIN",
    forgot_pin_body: "Quer utilizar a biometria para desbloquear a sua carteira?",
    share: "Partilhar",
    address_copied_to_clipboard: "Endereço copiado para a área de transferência",
    follows_you: "Segue-te a ti",
    official_mydoge_profile: "Perfil oficial do MyDoge",
    official_mydoge_commerce_profile: "Perfil oficial do comércio MyDoge",
    official_foundation_profile: "Perfil Oficial da Fundação",
    follow_back: "Seguir de volta",
    follow: "Seguir",
    tip: "Grojeta",
    share_profile: "Partilhar perfil",
    unfollow: "Deixar de seguir",
    unblock: "Desbloquear",
    block_or_report: "Bloquear ou denunciar",
    copy_profile_url: "Copiar o URL do perfil",
    memes_error: "Erro ao carregar memes. Por favor volte e tente novamente.",
    user_profile_hidden: "O perfil do utilizador está oculto",
    error_loading_profile: "Erro ao carregar o perfil. Por favor volte e tente novamente.",
    uid_not_specified: "Erro: uid não especificado. Por favor, notifique o suporte.",
    block_or_report_description: "MyDoge irá analisar todos os perfis reportados para qualquer atividade de acordo com nossas diretrizes. Também pode bloquear o perfil para parar de ver as suas publicações.",
    nevermind: "Deixa para lá",
    report: "Relatório",
    block: "Bloquear",
    unblock_user: "Desbloquear utilizador?",
    unblock_user_description: "Irá desbloquear o utilizador e irá continuar a ver as suas publicações.",
    you_have_no_posts_yet: "Ainda não tem publicações",
    no_posts_yet: "Nenhuma publicação ainda",
    amount: "Valor",
    custom: "Personalizado",
    add_a_message: "Adiciona uma mensagem",
    find_friends: "Encontre amigos",
    cancel: "Cancelar",
    i_understand_continue: "compreendi, continuar",
    hey_are_you_sure: "Tem a certeza?",
    delete_backup_confirmation: "Depois de apagar este backup não poderá recuperar o backup na nuvem, esta ação não pode ser revertida",
    all_transactions: "todas as transacções",
    pending_transactions: "Transações pendentes",
    view_on: "보기", // View on
    invoice_id_copied: "송장 번호가 복사되었습니다.", // Invoice ID copied
    gift_card: "기프트 카드", // Gift Card
    invoice_id: "송장 번호", // Invoice ID
    support: "지원하다", // Support
    phone_number: "전화 번호", // Phone number
    whatsapp_verification_notice:
      "WhatsApp을 통해 인증 코드가 휴대폰으로 전송됩니다.", // A verification code will be sent to your phone via WhatsApp
    via_whatsapp: "WhatsApp을 통해", // via WhatsApp
    you_may_not_have_backed_up_your_wallet:
      "클라우드에 기존 백업이 있지만 현재 지갑을 백업하지 않았을 수 있습니다.", // You have an existing backup on the cloud, but you may not have backed up your current wallet.
    signed_in_as: "로그인되었습니다", // Signed in as
    sign_in_to_restore_backup:
      "백업을 복원하려면 로그인하세요", // Sign in to restore backup
    sign_in_with_google: "Google로 로그인", // Sign in with Google
  },
};
