// Turkish translation
export const tr = {
  translation: {
    en: "İngilizce",
    zh: "简体中文",
    ja: "日本語",
    ko: "한국어",
    fr: "Français",
    es: "Español",
    pt: "Português",
    de: "Deutsch",
    vn: "Tiếng Việt",
    tr: "Türkçe",
    preference: "Tercih",
    disable_button_vibration: "Düğme titreşimini devre dışı bırak",
    back: "Geri",
    language: "Dil",
    app_theme: "Uygulama Teması",
    system: "Sistem",
    dark: "Karanlık",
    light: "Aydınlık",
    settings: "Ayarlar",
    backup_and_security: "Yedekleme ve Güvenlik",
    manage_wallet: "Cüzdanı Yönet",
    profile: "Profil",
    app_preferences: "Uygulama Tercihleri",
    notifications: "Bildirimler",
    help_support: "Yardım ve Destek",
    about_my_doge: "My Doge Hakkında",
    admin: "Yönetici",
    i_cloud: "iCloud",
    cloud: "bulut",
    youve_backed_up_to: "Yedeklediğiniz yer:",
    you_havent_created_a_cloud_backup: "Henüz bir Bulut Yedeklemesi oluşturmadınız",
    manage: "Yönet",
    backup: "Yedekle",
    view_seed_phrase: "Tohum Kelimelerini Görüntüle",
    pin: "PIN",
    back_up_to: "Yedekleme yeri:",
    back_up_your_wallet: "Cüzdanınızı yedekleyin",
    back_up_your_wallet_description:
      "Cüzdanınızı buluta kaydedin ve bir şifre ile koruyun. Ayrıca Tohum Kelimelerinizi yazabilir veya bir şifre yöneticisine kopyalayabilirsiniz.",
    pin_description:
      "PIN kodunuzu unutursanız, cüzdanınızı bir yedekten geri yüklemeniz gerekecektir.",
    change_pin: "PIN Değiştir",
    your_pin_is_required:
      "Ödeme yapmak ve hassas işlemleri gerçekleştirmek için PIN kodunuz gereklidir.",
    use_fingerprint: "Parmak İzi/Yüz Kimliği Kullan",
    ask_every_time_i_open_the_app: "Uygulamayı her açtığımda sor",
    this_will_remove_all_wallet:
      "Bu, cihazınızdan tüm cüzdan ile ilgili verileri kaldıracaktır.",
    delete_wallet: "Cüzdanı Sil",
    sign_in_to_the_dogeverse: "Dogeverse'e Giriş Yap",
    dogeverse_intro_description:
      "DogeTag'inizi alın, arkadaşlarınızı bulun, bağlantınızla ödemeler alın ve Dogeverse'deki içeriklerle etkileşime geçin.",
    sign_in: "Giriş Yap",
    sign_in_description:
      "Telefon numaranız yalnızca giriş yapmak için kullanılır ve halka açık hale getirilmez.",
    create_account_description:
      "Dogeverse'e katılın ve büyük bir Shibe ağına bağlanın.",
    send_verification: "Doğrulama Gönder",
    verify_your_phone_number: "Telefon Numaranızı Doğrulayın",
    enter_the_code_sent_to: "Gönderilen kodu girin:",
    resend_code: "Kodu Yeniden Gönder",
    wrong_number: "Yanlış Numara",
    confirm_code: "Kodu Onayla",
    youve_entered_the_verse: "Verse'e girdiniz",
    youre_now_ready_to_explore_the_dogeverse:
      "Artık Dogeverse'i keşfetmeye hazırsınız!",
    lets_go: "Hadi gidelim!",
    edit_profile: "Profili Düzenle",
    social_connect: "Sosyal Bağlantı",
    profile_privacy: "Profil Gizliliği",
    profile_is_public: "Profil Herkese Açık",
    show_wallet_address_and_tip_button: "Cüzdan adresini ve Bahşiş düğmesini göster",
    preferences: "Tercihler",
    confirm_x_tips: "𝕏 Bahşişlerini Onayla",
    tips_received: "Alınan Bahşişler",
    new_followers: "Yeni Takipçiler",
    new_memes: "Yeni Memeler",
    about_mydoge: "MyDoge Hakkında",
    terms_of_use: "Kullanım Şartları",
    privacy_policy: "Gizlilik Politikası",
    share_mydoge: "MyDoge'u Paylaş",
    visit_our_website: "Web Sitemizi Ziyaret Edin",
    settings_and_support: "Ayarlar ve Destek",
    connect_twitch: "Twitch'e Bağlan",
    connect_x: "𝕏'e Bağlan",
    create_a_post: "Gönderi Oluştur",
    following: "Takip Ediliyor",
    followers: "Takipçiler",
    recent_activity: "Son Aktivite",
    history: "Geçmiş",
    price: "Fiyat",
    usd: "USD",
    txs: "İşlemler",
    hr: "sa",
    send: "Gönder",
    receive: "Al",
    buy: "Satın Al",
    scan: "Tara",
    from: "Gönderen",
    to: "Alıcı",
    note: "Not",
    timestamp: "Zaman Damgası",
    confirmations: "Onaylar",
    tx_hash: "İşlem Hash'i",
    tx_hash_copied: "İşlem hash'i kopyalandı",
    note_copied: "Not kopyalandı",
    address_copied: "Adres kopyalandı",
    wallet: "Cüzdan",
    dogeverse: "Dogeverse",
    shop: "Mağaza",
    receive_doge: "Doge Al",
    send_doge: "Doge Gönder",
    confirm_transaction: "İşlemi Onayla",
    scan_qr_code: "QR Kodu Tara",
    new_post: "Yeni Gönderi",
    send_doge_alert_box_message:
      "Arkadaşlarınıza DOGE gönderebilirsiniz, bir cüzdan adresi veya MyDoge kullanıcı adı girin",
    wallet_address_or_username: "Cüzdan adresi veya kullanıcı adı",
    saved_addresses: "Kayıtlı Adresler",
    add_new: "Yeni Ekle",
    sending_to: "Gönderiliyor:",
    save: "Kaydet",
    saved: "Kaydedildi",
    balance: "Bakiye",
    max: "Maksimum",
    next: "İleri",
    network_fee: "Ağ Ücreti",
    max_tx_size_warning:
      "UYARI: Maksimum işlem boyutuna ulaşıldı. Bu, bir seferde gönderebileceğiniz en yüksek miktardır.",
    confirm_transaction_warning:
      "Onaylamadan önce her zaman kime gönderdiğinizi iki kez kontrol edin. Asla bir borsanın çekim adresine göndermeyin. Dogecoin işlemleri geri alınamaz!",
    add_note: "Not Ekle",
    wallet_address: "Cüzdan Adresi",
    wallet_label: "Cüzdan Etiketi",
    save_changes: "Değişiklikleri Kaydet",
    save_address: "Adresi Kaydet",
    enter_new_PIN: "Yeni PIN girin",
    confirm_new_pin: "Yeni PIN'i onaylayın",
    enter_new_PIN_description: "MyDoge cüzdanınız için yeni PIN'inizi girin",
    enter_old_PIN: "Eski PIN'i girin",
    enter_old_PIN_description: "MyDoge cüzdanınız için eski PIN'inizi girin",
    forgot_PIN: "PIN'i Unuttum",
    confirm: "Onayla",
    biometrics_confirmation:
      "Cüzdanınızın kilidini açmak için biyometriyi kullanmak istiyor musunuz?",
    use_biometrics: "Biyometri Kullan",
    dismiss: "Kapat",
    remove_wallet_data_description:
      "Bu, cihazınızdan tüm cüzdan ile ilgili verileri kaldıracaktır.",
    delete_profile_forever: "MyDoge Profilinizi kalıcı olarak silin",
    sign_out: "Çıkış Yap",
    delete_wallet_confirmation: "Hey! Emin misiniz?",
    remove_wallet_description:
      "Mevcut cüzdanınız bu uygulamadan kaldırılacak, ancak her zaman blok zincirinde var olmaya devam edecektir.",
    remove_profile_assets_description:
      "Kullanıcı profiliniz ve varlıklarınız kaldırılacak ve kalıcı olarak silinecektir. Bu işlem geri alınamaz.",
    wallet_recovery_description: "Bu cüzdanı SADECE şununla kurtarabilirsiniz:",
    seed_phrase: "TOHUM KELİMELERİ",
    no_seed_phrase: "MyDoge, tohum kelimelerinize sahip değildir.",
    understand_continue: "Anlıyorum, devam et",
    enter: "Gir",
    Delete: "Sil",
    erase_wallet: "cüzdanınızı silmek için",
    and_profile_data: "ve profil verilerini",
    message: "Mesaj",
    username: "Kullanıcı Adı",
    edit: "Düzenle",
    new_address: "Yeni Adres",
    your_seed_phrase: "Tohum Kelimeleriniz ✍️",
    save_seed_phrase_instructions:
      "Bu kelimeleri sırasıyla kaydedin. Onları yazın ve güvenli bir yerde saklayın veya bir şifre yöneticisine kopyalayın.",
    seed_phrase_warning:
      "Tohum Kelimeleriniz cüzdanınızın anahtarıdır. Bu kelimeler ile herkes fonlarınıza erişebilir. Daha fazla bilgi için dokunun",
    copy: "Kopyala",
    hide: "Gizle",
    show: "Göster",
    screenshot_detected: "Ekran görüntüsü tespit edildi",
    screenshot_warning:
      "Tohum kelimelerinizin ekran görüntüleri veya diğer dijital kopyaları üçüncü taraflara sızabilir.",
    okay: "Tamam",
    seed_phrase_importance: "Tohum Kelimelerim ne kadar önemli?",
    seed_phrase_explanation:
      "Tohum Kelimelerinize sahip olan herkes fonlarınıza erişebilir. Tohum Kelimelerinizi kimseyle paylaşmayın. MyDoge, Tohum Kelimelerinizi sizin için kaydetmez. Cihazınız hasar görürse, kaybolursa veya çalınırsa ya da başka bir şekilde erişilemez hale gelirse, Tohum Kelimeleriniz cüzdanınızı kurtarmanın tek yoludur.",
    send_receive_tips_x: "𝕏 üzerinden bahşiş gönder ve al",
    read_mydogetip_faq: "MyDogeTip SSS'yi oku",
    connect_with_x: "𝕏 ile bağlan",
    start_receive_tips_twitch: "Twitch'te bahşiş almaya başla",
    visit_mydogetv_twitch: "Daha fazla bilgi için Twitch'te MyDogeTV'yi ziyaret edin",
    connect_with_twitch: "Twitch ile bağlan",
    screen_not_exist: "Bu ekran mevcut değil.",
    go_to_home_screen: "Ana Ekrana Git",
    gift_cards: "Hediye Kartları",
    backup_wallet: "Yeni cüzdanınızı yedekleyin",
    backup_required: "Fonlarınızı güvence altına almak için yedekleme gereklidir",
    why_backups_important: "Yedeklemeler neden önemlidir?",
    learn_about_backups: "Yedeklemeler hakkında bilgi almak için dokunun",
    backup_to: "Yedekleme yeri:",
    save_wallet_to_cloud:
      "Cüzdanınızı buluta kaydedin ve bir şifre ile koruyun",
    write_on_paper: "Kağıda yaz",
    write_down_seed_phrase:
      "Tohum Kelimelerinizi yazın veya bir şifre yöneticisine kaydedin",
    why_backups_important_description:
      "Kendi gözetiminiz, MyDoge ekibi de dahil olmak üzere başka kimsenin fonlarınıza erişemeyeceği anlamına gelir. Yedekleme, cihazınız hasar görürse, kaybolursa veya çalınırsa ya da silinirse cüzdanınızı geri yüklemenin tek yoludur.",
    choose_password: "Bir şifre seçin",
    use_memorable_password: "Lütfen hatırlayabileceğiniz bir şifre kullanın. Daha uzun şifreler daha güvenlidir.",
    more_secure_password: "Lütfen hatırlayabileceğiniz bir şifre kullanın. Daha uzun şifreler daha güvenlidir.",
    lose_password_lose_backup: "Bu şifreyi kaybederseniz, cüzdan yedeklemenizi kaybedersiniz.",
    password: "Şifre",
    confirm_password: "Şifreyi Onayla",
    confirm_backup: "Yedeklemeyi Onayla",
    overwrite_backup_title: "Mevcut yedeklemenin üzerine yazılsın mı?",
    existing_wallet_overwrite_prompt: "Bulutta daha önce kaydedilmiş bir cüzdanınız var. Üzerine yazmak istiyor musunuz?",
    overwrite_backup: "Yedeklemenin Üzerine Yaz",
    import_existing_wallet: "Mevcut Cüzdanı İçe Aktar",
    unknown_cloud_error: "Bilinmeyen Bulut Hatası",
    unknown_cloud_error_body: "Buluta yedekleme sırasında bilinmeyen bir hata oluştu.",
    try_again_or_notify_support: "Lütfen tekrar deneyin veya MyDoge desteğine bildirin.",
    enter_recovery_password: "Kurtarma şifresini girin",
    enter_cloud_password_description: "Tohum Kelimelerinizi bulutta saklamak için kullandığınız şifreyi girin",
    import_wallet: "Cüzdanı İçe Aktar",
    imported_wallet_title: "Cüzdanınızı içe aktardınız",
    imported_wallet_success: "Cüzdanınızı başarıyla içe aktardınız!",
    secure_new_wallet: "Yeni cüzdanınızı güvence altına alın",
    set_pin: "6 haneli bir PIN belirleyin",
    reenter_pin: "6 haneli PIN'i tekrar girin",
    pin_payment_note: "Ödeme göndermek için PIN'inize ihtiyacınız olacak",
    use_biometric: "Parmak İzi/Yüz Kimliği Kullan",
    ask_every_time: "Uygulamayı her açtığımda sor",
    create_pin: "PIN Oluştur",
    confirm_pin: "PIN'i Onayla",
    choose_dogeverse_username: "DogeTag'inizi seçin",
    dogeverse_link: "Web bağlantınız şöyle olacak:",
    continue: "Devam Et",
    dogeverse_entry_title: "Verse'e girdiniz",
    dogeverse_entry_body: "Artık Dogeverse'i keşfetmeye hazırsınız!",
    manual_backup_title: "Tohum Kelimelerini Yaz",
    save_words_order: "Bu kelimeleri sırasıyla kaydedin. Onları yazın ve güvenli bir yerde saklayın veya bir şifre yöneticisine kopyalayın.",
    seed_phrase_key: "Tohum Kelimeleriniz cüzdanınızın anahtarıdır. Bu kelimeler ile herkes fonlarınıza erişebilir. Daha fazla bilgi için dokunun",
    written_down: "Bunu yazdım",
    screenshot_alert: "Tohum kelimelerinizin ekran görüntüleri veya diğer dijital kopyaları üçüncü taraflara sızabilir.",
    seed_phrase_access: "Tohum Kelimelerinize sahip olan herkes fonlarınıza erişebilir. Tohum Kelimelerinizi kimseyle paylaşmayın. MyDoge, Tohum Kelimelerinizi sizin için kaydetmez. Cihazınız hasar görürse, kaybolursa veya çalınırsa ya da başka bir şekilde erişilemez hale gelirse, Tohum Kelimeleriniz cüzdanınızı kurtarmanın tek yoludur.",
    icloud_backup: "iCloud Yedeklemesi",
    cloud_backup: "Bulut Yedeklemesi",
    dont_lose_wallet: "Cüzdanınızı kaybetmeyin!",
    save_online_backup: "Çevrimiçi yedeklemeyi şuraya kaydedin:",
    icloud: "iCloud",
    google_drive: "Google Drive",
    do_this_later: "Bunu daha sonra yapacağım",
    confirm_seed_phrase: "Tohum Kelimelerini Onayla",
    select_correct_word: "Lütfen aşağıdaki listeden her pozisyon için doğru kelimeyi seçin.",
    enter_seed_phrase: "Tohum Kelimelerini Girin",
    enter_seed_phrase_instructions: "Mevcut bir cüzdanı geri yüklemek için 12 kelimelik Tohum Kelimelerinizi girin",
    paste: "Yapıştır",
    restore_wallet: "Cüzdanı Geri Yükle",
    wallet_imported: "Cüzdan içe aktarıldı!",
    wallet_imported_body: "Cüzdanınız kullanıma hazır.",
    restore_existing_wallet: "Mevcut cüzdanınızı geri yükleyin",
    restore_existing_wallet_instructions: "Zaten bir cüzdanınız var mı? Hadi onu geri getirelim!",
    restore_from: "Şuradan geri yükle:",
    restore_from_cloud_description: "Cüzdanınızı şuradan geri yükleyin:",
    restore_with_seed_phrase: "Tohum Kelimeleri ile geri yükle",
    restore_with_seed_phrase_description: "Mevcut bir MyDoge cüzdanını geri yüklemek için Tohum Kelimelerinizi kullanın",
    no_cloud_backup: "Bulut Yedeklemesi Yok",
    no_cloud_backup_body: "Bulut yedeklemesi bulunamadı. Lütfen bir Tohum Kelimesi ile geri yükleyin veya yeni bir cüzdan oluşturun",
    create_wallet: "Bir cüzdan oluştur",
    already_have_wallet: "Zaten bir cüzdanım var",
    buy_send_receive_dogecoin: "Dogecoin Satın Al, Gönder ve Al",
    send_doge_tips: "𝕏'te Doge bahşişleri gönderin, Doge'larınızı güvenle saklayın ve kendi bankanız olun",
    shop_gift_cards_apparel: "Hediye Kartları ve Giyim Alışverişi Yapın",
    buy_gift_cards: "Dogecoin ile hediye kartları satın alın veya en son Doge Modasını keşfedin",
    enter_the_dogeverse: "Dogeverse'e Girin",
    claim_dogtag: "DogeTag'inizi alın, arkadaşlarınızı bulun, bağlantınızla ödemeler alın ve memeler paylaşın",
    so_much_tip: "Çok Bahşiş, Çok Vay!",
    success: "Başarılı",
    sent_doge: "Gönderdiniz:",
    some_doge: "biraz Doge!",
    total: "Toplam",
    done: "Tamam",
    shop_with_doge: "Doge ile Alışveriş Yap",
    oops: "Ups!",
    no_comments_yet: "Henüz yorum yok",
    to_post_a_comment: "yorum yapmak için",
    your_comment: "Yorumunuz",
    post: "Gönder",
    delete: "Sil",
    enable_push_notifications: "Push Bildirimleri Etkinleştirilsin mi?",
    get_notifications_for_tips: "Bahşişler ve Mesajlar için bildirim alın",
    no_thanks: "Hayır, teşekkürler",
    open_settings: "Ayarları Aç",
    swipe_for_more: "Daha fazlası için yukarı kaydırın",
    transaction_confirmation_alert: "Onaylamadan önce her zaman kime gönderdiğinizi iki kez kontrol edin. Asla bir borsanın çekim adresine göndermeyin. Dogecoin işlemleri geri alınamaz!",
    clear_amount: "Miktarı Temizle",
    set_amount: "Miktarı Ayarla",
    save_qr: "QR'ı Kaydet",
    WALLET_ADDRESS: "CÜZDAN ADRESİ",
    dogetag_link: "DOGETAG BAĞLANTISI",
    no_access_camera: "Kameraya erişim yok",
    enable_camera_access_ios: "MyDoge için kamera erişimini etkinleştirin",
    grant_camera_permission_android: "Lütfen MyDoge'a kamera izni verin",
    scan_qr_payment: "Ödeme yapmak için QR kodunu tarayın",
    select_image: "Resim Seç",
    find_friends_heading: "MyDoge'da Arkadaşları Bul",
    find_friends_description: "Kişi erişimine izin verin ve MyDoge'da arkadaşlarınızı ve kişilerinizi kolayca bulun.",
    find_friends_button: "Arkadaşları Bul",
    later_button: "Bunu daha sonra yapacağım",
    own_address_error: "Kendi adresinize gönderemezsiniz",
    invalid_address_error: "Geçersiz adres",
    results_title: "Sonuçlar",
    all: "Tümü",
    pending: "Beklemede",
    enter_pin: "PIN Girin",
    enter_pin_to_confirm: "Onaylamak için Cüzdan PIN'inizi girin",
    welcome_back: "Tekrar hoş geldiniz",
    enter_wallet_pin: "Cüzdan PIN'inizi girin",
    forgot_pin: "PIN'i Unuttum",
    forgot_pin_title: "PIN'i Unuttum",
    forgot_pin_body: "Cüzdanınızın kilidini açmak için biyometriyi kullanmak istiyor musunuz?",
    share: "Paylaş",
    address_copied_to_clipboard: "Adres panoya kopyalandı",
    follows_you: "Sizi Takip Ediyor",
    official_mydoge_profile: "Resmi MyDoge Profili",
    official_mydoge_commerce_profile: "Resmi MyDoge Ticaret Profili",
    official_foundation_profile: "Resmi Vakıf Profili",
    follow_back: "Geri Takip Et",
    follow: "Takip Et",
    tip: "Bahşiş",
    share_profile: "Profili Paylaş",
    unfollow: "Takibi Bırak",
    unblock: "Engeli Kaldır",
    block_or_report: "Engelle veya Bildir",
    copy_profile_url: "Profil URL'sini Kopyala",
    memes_error: "Memeler yüklenirken hata oluştu. Lütfen geri dönün ve tekrar deneyin.",
    user_profile_hidden: "Kullanıcı profili gizli",
    error_loading_profile: "Profil yüklenirken hata oluştu. Lütfen geri dönün ve tekrar deneyin.",
    uid_not_specified: "Hata: uid belirtilmedi. Lütfen desteğe bildirin.",
    block_or_report_description: "MyDoge, bildirilen tüm profilleri yönergelerimize aykırı herhangi bir faaliyet için inceleyecektir. Ayrıca, gönderilerini görmemek için profili engelleyebilirsiniz.",
    nevermind: "Boş ver",
    report: "Bildir",
    block: "Engelle",
    unblock_user: "Kullanıcının Engelini Kaldır?",
    unblock_user_description: "Bu, kullanıcının engelini kaldıracak ve gönderilerini görmeye devam edeceksiniz.",
    you_have_no_posts_yet: "Henüz gönderiniz yok",
    no_posts_yet: "Henüz gönderi yok",
    amount: "Miktar",
    custom: "Özel",
    add_a_message: "Bir mesaj ekle",
    find_friends: "Arkadaşları bul",
    cancel: "İptal",
    i_understand_continue: "Anlıyorum, devam et",
    hey_are_you_sure: "Hey! Emin misiniz?",
    delete_backup_confirmation: "Bu yedeklemeyi sildiğinizde, bulut yedeklemenizi kaybedersiniz, bu işlem geri alınamaz",
    all_transactions: "Tüm İşlemler",
    pending_transactions: "Bekleyen İşlemler",
    view_on: "Görüntüle:",
    invoice_id_copied: "Fatura ID'si kopyalandı",
    gift_card: "Hediye Kartı",
    invoice_id: "Fatura ID",
    support: "Destek",
    phone_number: "Telefon numarası",
    whatsapp_verification_notice: "Bir doğrulama kodu WhatsApp üzerinden telefonunuza gönderilecek",
    via_whatsapp: "WhatsApp üzerinden",
    you_may_not_have_backed_up_your_wallet: "Bulutta mevcut bir yedeklemeniz var, ancak mevcut cüzdanınızı yedeklememiş olabilirsiniz.",
    signed_in_as: "Şu şekilde giriş yapıldı:",
    sign_in_to_restore_backup: "Yedeklemeyi geri yüklemek için giriş yapın",
    sign_in_with_google: "Google ile giriş yap",
  },
};
