// Vietnamese translation
export const vn = {
  translation: {
    en: "English",
    zh: "简体中文",
    ja: "日本語",
    ko: "한국어",
    fr: "Français",
    es: "Español",
    pt: "Português",
    de: "Deutsch",
    vn: "Tiếng Việt",
    ru: "Русский",
    tr: "Türkçe",
    preference: "Tùy chỉnh",
    disable_button_vibration: "Tắt rung",
    back: "Quay lại",
    language: "Ngôn ngữ",
    app_theme: "Chủ đề ứng dụng",
    system: "Hệ thống",
    dark: "Tối",
    light: "Sáng",
    settings: "Cài đặt",
    backup_and_security: "Sao lưu & Bảo mật",
    manage_wallet: "Quản lý Ví",
    profile: "Hồ sơ",
    app_preferences: "Tùy chỉnh ứng dụng",
    notifications: "Thông báo",
    help_support: "Trợ giúp & Hỗ trợ",
    about_my_doge: "Về My Doge",
    admin: "Quản trị viên",
    i_cloud: "iCloud",
    cloud: "đám mây",
    youve_backed_up_to: "Bạn đã sao lưu vào",
    you_havent_created_a_cloud_backup: "Bạn chưa tạo sao lưu đám mây",
    manage: "Quản lý",
    backup: "Sao lưu",
    view_seed_phrase: "Xem Cụm từ khôi phục",
    pin: "PIN",
    back_up_to: "Sao lưu vào",
    back_up_your_wallet: "Sao lưu ví của bạn",
    back_up_your_wallet_description:
      "Lưu ví của bạn lên đám mây và bảo vệ bằng mật khẩu. Bạn cũng có thể ghi lại Cụm từ khôi phục của mình hoặc sao chép nó vào trình quản lý mật khẩu.",
    pin_description:
      "Nếu bạn quên mã PIN của mình, bạn sẽ cần khôi phục ví từ bản sao lưu.",
    change_pin: "Đổi PIN",
    your_pin_is_required:
      "Mã PIN của bạn cần thiết để thực hiện thanh toán và các hành động nhạy cảm.",
    use_fingerprint: "Sử dụng Dấu vân tay/Sinh trắc học",
    ask_every_time_i_open_the_app: "Hỏi mỗi lần tôi mở ứng dụng",
    this_will_remove_all_wallet:
      "Điều này sẽ xóa tất cả dữ liệu liên quan đến ví khỏi thiết bị của bạn.",
    delete_wallet: "Xóa Ví",
    sign_in_to_the_dogeverse: "Đăng nhập vào Dogeverse",
    dogeverse_intro_description:
      "Yêu cầu DogeTag của bạn, tìm bạn bè, nhận thanh toán bằng liên kết của bạn và tương tác với nội dung trong Dogeverse.",
    sign_in: "Đăng nhập",
    sign_in_description:
      "Số điện thoại của bạn chỉ được sử dụng để đăng nhập và sẽ không được công khai.",
    create_account_description:
      "Tham gia Dogeverse và kết nối với một mạng lưới Shibes rộng lớn.",
    send_verification: "Gửi Xác minh",
    verify_your_phone_number: "Xác minh Số điện thoại của bạn",
    enter_the_code_sent_to: "Nhập mã được gửi đến",
    resend_code: "Gửi lại Mã",
    wrong_number: "Sai số",
    confirm_code: "Mã xác nhận",
    youve_entered_the_verse: "Bạn đã vào Verse",
    youre_now_ready_to_explore_the_dogeverse:
      "Bạn đã sẵn sàng khám phá Dogeverse!",
    lets_go: "Đi thôi!",
    edit_profile: "Chỉnh sửa Hồ sơ",
    social_connect: "Kết nối Mạng xã hội",
    profile_privacy: "Hồ sơ riêng tư",
    profile_is_public: "Hồ sơ công khai",
    show_wallet_address_and_tip_button: "Hiển thị địa chỉ ví và nút Tip",
    preferences: "Tùy chỉnh",
    confirm_x_tips: "Xác nhận 𝕏 Mẹo",
    tips_received: "Mẹo đã nhận",
    new_followers: "Người theo dõi mới",
    new_memes: "Memes mới",
    about_mydoge: "Về MyDoge",
    terms_of_use: "Điều khoản Sử dụng",
    privacy_policy: "Chính sách Bảo mật",
    share_mydoge: "Chia sẻ MyDoge",
    visit_our_website: "Thăm Trang web của chúng tôi",
    settings_and_support: "Cài đặt và Hỗ trợ",
    connect_twitch: "Kết nối Twitch",
    connect_x: "Kết nối 𝕏",
    create_a_post: "Tạo một Bài đăng",
    following: "Đang theo dõi",
    followers: "Người theo dõi",
    recent_activity: "Hoạt động Gần đây",
    history: "Lịch sử",
    price: "Giá",
    usd: "USD",
    txs: "Giao dịch",
    hr: "giờ",
    send: "Gửi",
    receive: "Nhận",
    buy: "Mua",
    scan: "Quét",
    from: "Từ",
    to: "Đến",
    note: "Ghi chú",
    timestamp: "Dấu thời gian",
    confirmations: "Xác nhận",
    tx_hash: "Mã băm giao dịch",
    tx_hash_copied: "Mã băm giao dịch đã được sao chép",
    note_copied: "Đã sao chép ghi chú",
    address_copied: "Đã sao chép địa chỉ",
    wallet: "Ví",
    dogeverse: "Dogeverse",
    shop: "Cửa hàng",
    receive_doge: "Nhận Doge",
    send_doge: "Gửi Doge",
    confirm_transaction: "Xác nhận Giao dịch",
    scan_qr_code: "Quét Mã QR",
    new_post: "Bài đăng mới",
    send_doge_alert_box_message:
      "Bạn có thể gửi DOGE cho bạn bè của mình, nhập địa chỉ ví hoặc tên người dùng MyDoge",
    wallet_address_or_username: "Địa chỉ ví hoặc tên người dùng",
    saved_addresses: "Địa chỉ đã lưu",
    add_new: "Thêm mới",
    sending_to: "Đang gửi đến",
    save: "Lưu",
    saved: "Đã lưu",
    balance: "Số dư",
    max: "Tối đa",
    next: "Tiếp theo",
    network_fee: "Phí mạng",
    max_tx_size_warning:
      "CẢNH BÁO: Đã đạt kích thước giao dịch tối đa. Đây là số lượng tối đa bạn có thể gửi trong một lần.",
    confirm_transaction_warning:
      "Luôn kiểm tra kỹ lưỡng người nhận trước khi xác nhận. Không bao giờ gửi đến địa chỉ rút tiền của sàn giao dịch. Các giao dịch Dogecoin không thể đảo ngược!",
    add_note: "Thêm Ghi chú",
    wallet_address: "Địa chỉ Ví",
    wallet_label: "Nhãn Ví",
    save_changes: "Lưu Thay đổi",
    save_address: "Lưu Địa chỉ",
    enter_new_PIN: "Nhập mã PIN mới",
    confirm_new_pin: "Xác nhận mã PIN mới",
    enter_new_PIN_description: "Nhập mã PIN mới cho ví MyDoge của bạn",
    enter_old_PIN: "Nhập mã PIN cũ",
    enter_old_PIN_description: "Nhập mã PIN cũ cho ví MyDoge của bạn",
    forgot_PIN: "Quên PIN",
    confirm: "Xác nhận",
    biometrics_confirmation:
      "Bạn có muốn sử dụng sinh trắc học để mở khóa ví của mình không?",
    use_biometrics: "Sử dụng Sinh trắc học",
    dismiss: "Bỏ qua",
    remove_wallet_data_description:
      " Điều này sẽ xóa tất cả dữ liệu liên quan đến ví khỏi thiết bị của bạn.",
    delete_profile_forever: "Xóa vĩnh viễn Hồ sơ MyDoge của bạn",
    sign_out: "Đăng xuất",
    delete_wallet_confirmation: "Này! Bạn có chắc chắn không?",
    remove_wallet_description:
      "Ví hiện tại của bạn sẽ bị xóa khỏi ứng dụng này, tuy nhiên nó sẽ luôn tồn tại trên blockchain.",
    remove_profile_assets_description:
      "Hồ sơ người dùng và tài sản của bạn sẽ bị xóa và bị xóa vĩnh viễn. Hành động này không thể hoàn tác.",
    wallet_recovery_description: " Bạn chỉ có thể khôi phục ví này bằng",
    seed_phrase: "CỤM TỪ KHÔI PHỤC",
    no_seed_phrase: "MyDoge không có Cụm từ khôi phục của bạn.",
    understand_continue: "Tôi hiểu, tiếp tục",
    enter: "Nhập",
    Delete: "Xóa",
    erase_wallet: "để xóa ví của bạn",
    and_profile_data: "và dữ liệu hồ sơ",
    message: "Tin nhắn",
    username: "Tên người dùng",
    edit: "Chỉnh sửa",
    new_address: "Địa chỉ mới",
    your_seed_phrase: "Cụm từ khôi phục của bạn ✍️",
    save_seed_phrase_instructions:
      "Lưu các từ này theo thứ tự. Viết chúng xuống và giữ chỗ an toàn, hoặc sao chép vào quản lý mật khẩu.",
    seed_phrase_warning:
      "Cụm từ khôi phục là chìa khóa ví của bạn. Bất cứ ai có được cụm từ này đều có thể truy cập vào tài sản của bạn. Nhấn để tìm hiểu thêm",
    copy: "Sao chép",
    hide: "Ẩn",
    show: "Hiện",
    screenshot_detected: "Phát hiện chụp ảnh màn hình",
    screenshot_warning:
      "Chụp ảnh màn hình hoặc lưu trữ kỹ thuật số của Cụm từ khôi phục có thể bị rò rỉ cho bên thứ ba.",
    okay: "Đồng ý",
    seed_phrase_importance: "Cụm từ khôi phục của tôi quan trọng như thế nào?",
    seed_phrase_explanation:
      "Bất cứ ai có Cụm từ khôi phục đều có thể truy cập vào tài sản của bạn. Không chia sẻ Cụm từ khôi phục với bất kỳ ai. MyDoge không lưu trữ Cụm từ khôi phục của bạn. Nếu thiết bị của bạn bị hỏng, bị đánh cắp hoặc không thể truy cập thì Cụm từ khôi phục là cách duy nhất để khôi phục ví của bạn.",
    send_receive_tips_x: "Gửi và nhận tiền Tip qua 𝕏",
    read_mydogetip_faq: "Đọc FAQ MyDogeTip",
    connect_with_x: "Kết nối với 𝕏",
    start_receive_tips_twitch: "Bắt đầu nhận tiền Tip trên Twitch",
    visit_mydogetv_twitch:
      "Ghé thăm MyDogeTV trên Twitch để biết thêm thông tin",
    connect_with_twitch: "Kết nối với Twitch",
    screen_not_exist: "Màn hình này không tồn tại.",
    go_to_home_screen: "Đi đến Màn hình Chính",
    gift_cards: "Thẻ quà tặng",
    backup_wallet: "Sao lưu ví của bạn",
    backup_required: "Yêu cầu sao lưu để bảo vệ tài sản của bạn",
    why_backups_important: "Tại sao sao lưu quan trọng?",
    learn_about_backups: "Nhấn để tìm hiểu về sao lưu",
    backup_to: "Sao lưu đến",
    save_wallet_to_cloud: "Lưu ví của bạn lên đám mây và bảo vệ bằng mật khẩu",
    write_on_paper: "Ghi ra giấy",
    write_down_seed_phrase:
      "Ghi lại cụm từ khôi phục của bạn hoặc lưu nó trong trình quản lý mật khẩu.",
    why_backups_important_description:
      "Tự bảo quản có nghĩa là không ai khác có thể truy cập vào tài sản của bạn, ngay cả nhóm MyDoge. Việc sao lưu là cách duy nhất để khôi phục lại ví nếu thiết bị của bạn bị hỏng, mất mát hoặc bị đánh cắp, hoặc bị xoá.",
    choose_password: "Chọn mật khẩu",
    use_memorable_password:
      "Vui lòng sử dụng mật khẩu bạn có thể nhớ. Mật khẩu dài hơn sẽ an toàn hơn.",
    more_secure_password:
      "Vui lòng sử dụng mật khẩu bạn có thể nhớ. Mật khẩu dài hơn sẽ an toàn hơn.",
    lose_password_lose_backup:
      "Nếu bạn mất mật khẩu này, bạn sẽ mất bản sao lưu của ví của bạn.",
    password: "Mật khẩu",
    confirm_password: "Xác nhận mật khẩu",
    confirm_backup: "Xác nhận sao lưu",
    overwrite_backup_title: "Ghi đè bản sao lưu hiện tại?",
    existing_wallet_overwrite_prompt:
      "Bạn có một ví trước đây đã được sao lưu lên đám mây. Bạn có muốn ghi đè nó không?",
    overwrite_backup: "Ghi đè lên bản sao lưu",
    import_existing_wallet: "Nhập ví hiện có",
    unknown_cloud_error: "Lỗi Đám mây không xác định",
    unknown_cloud_error_body:
      "Đã xảy ra lỗi không xác định khi sao lưu lên đám mây.",
    try_again_or_notify_support:
      "Vui lòng thử lại hoặc thông báo cho hỗ trợ MyDoge.",
    enter_recovery_password: "Nhập mật khẩu phục hồi",
    enter_cloud_password_description:
      "Nhập mật khẩu bạn đã sử dụng để lưu trữ Cụm từ khôi phục của bạn trên đám mây",
    import_wallet: "Nhập ví",
    imported_wallet_title: "Bạn đã nhập ví của mình",
    imported_wallet_success: "Bạn đã nhập ví thành công!",
    secure_new_wallet: "Bảo vệ ví mới của bạn",
    set_pin: "Đặt mã PIN 6 chữ số",
    reenter_pin: "Nhập lại mã PIN 6 chữ số",
    pin_payment_note: "Bạn cần mã PIN của mình để gửi thanh toán",
    use_biometric: "Sử dụng Vân tay/Sinh trắc học",
    ask_every_time: "Hỏi mỗi khi tôi mở ứng dụng",
    create_pin: "Tạo mã PIN",
    confirm_pin: "Xác nhận mã PIN",
    choose_dogeverse_username: "Chọn DogeTag",
    dogeverse_link: "Liên kết web của bạn sẽ là",
    continue: "Tiếp tục",
    dogeverse_entry_title: "Bạn đã bước vào Dogeverse",
    dogeverse_entry_body: "Bạn đã sẵn sàng khám phá Dogeverse!",
    manual_backup_title: "Ghi lại Cụm từ khôi phục",
    save_words_order:
      "Lưu các từ này theo thứ tự. Ghi lại Cụm từ khôi phục và giữ ở chỗ an toàn, hoặc lưu vào trình quản lý mật khẩu.",
    seed_phrase_key:
      "Cụm từ khôi phục là chìa khóa ví của bạn. Bất cứ ai có được cụm từ này đều có thể truy cập vào tài sản của bạn. Nhấn để tìm hiểu thêm",
    written_down: "Tôi đã ghi lại",
    screenshot_alert:
      "Chụp ảnh màn hình hoặc lưu trữ kỹ thuật số Cụm từ khôi phục có thể rò rỉ cho bên thứ ba.",
    seed_phrase_access:
      "Bất cứ ai có Cụm từ khôi phục đều có thể truy cập vào tài sản của bạn. Không chia sẻ Cụm từ khôi phục với bất kỳ ai. MyDoge không lưu trữ Cụm từ khôi phục của bạn. Nếu thiết bị của bạn bị hỏng, bị đánh cắp hoặc không thể truy cập thì Cụm từ khôi phục là cách duy nhất để khôi phục ví của bạn.",
    icloud_backup: "Sao lưu iCloud",
    cloud_backup: "Sao lưu đám mây",
    dont_lose_wallet: "Đừng để mất ví của bạn!",
    save_online_backup: "Lưu bản sao lưu trực tuyến đến",
    icloud: "iCloud",
    google_drive: "Google Drive",
    do_this_later: "Tôi sẽ làm điều này sau",
    confirm_seed_phrase: "Xác nhận Cụm từ khôi phục",
    select_correct_word:
      "Vui lòng chọn từ chính xác ở mỗi vị trí từ danh sách dưới đây.",
    enter_seed_phrase: "Nhập Cụm từ khôi phục",
    enter_seed_phrase_instructions:
      "Nhập 12 từ Cụm từ khôi phục theo thứ tự để xác nhận.",
    incorrect_seed_phrase:
      "Cụm từ khôi phục không chính xác. Vui lòng thử lại.",
    confirm_backup_phrase: "Xác nhận Cụm từ khôi phục của bạn",
    confirm_backup_instructions:
      "Vui lòng nhập lại Cụm từ khôi phục của bạn để xác nhận.",
    backup_successful: "Sao lưu thành công!",
    wallet_restored: "Ví đã khôi phục!",
    restore_failed: "Khôi phục thất bại. Vui lòng thử lại.",
    restore_from: "Khôi phục từ",
    restore_from_cloud_description: "Khôi phục ví của bạn từ",
    restore_with_seed_phrase: "Khôi phục bằng Cụm từ khôi phục",
    restore_with_seed_phrase_description:
      "Sử dụng Cụm từ khôi phục của bạn để khôi phục một ví MyDoge hiện có",
    no_cloud_backup: "Không có Sao lưu đám mây",
    no_cloud_backup_body:
      "Không tìm thấy sao lưu đám mây. Vui lòng khôi phục từ Cụm từ khôi phục, hoặc tạo một ví mới",
    create_wallet: "Tạo một ví",
    already_have_wallet: "Tôi đã có một ví",
    buy_send_receive_dogecoin: "Mua, Gửi & Nhận Dogecoin",
    send_doge_tips:
      "Gửi gợi ý về Doge trên 𝕏, lưu trữ Doge của bạn một cách an toàn, và trở thành ngân hàng của chính bạn.",
    shop_gift_cards_apparel: "Mua Thẻ quà tặng và Trang phục",
    buy_gift_cards:
      "Mua thẻ quà tặng bằng Dogecoin, hoặc mua thời trang Doge mới nhất",
    enter_the_dogeverse: "Nhập vào Dogeverse",
    claim_dogtag:
      "Nhận DogeTag của bạn, tìm bạn bè, nhận thanh toán với liên kết của bạn và chia sẻ meme",
    so_much_tip: "Quá nhiều tiền tip, quá tuyệt vời!",
    success: "Thành công",
    sent_doge: "Bạn đã gửi",
    some_doge: "một ít Doge!",
    total: "Tổng cộng",
    done: "Hoàn thành",
    shop_with_doge: "Mua sắm với Doge",
    oops: "Oops!",
    no_comments_yet: "Chưa có bình luận nào",
    to_post_a_comment: "để đăng một bình luận",
    your_comment: "Bình luận của bạn",
    post: "Đăng",
    delete: "Xóa",
    enable_push_notifications: "Bật thông báo đẩy?",
    get_notifications_for_tips: "Nhận thông báo cho gợi ý và tin nhắn",
    no_thanks: "Không, cảm ơn",
    open_settings: "Mở cài đặt",
    swipe_for_more: "Vuốt lên để xem thêm",
    transaction_confirmation_alert:
      "Luôn kiểm tra kỹ trước khi xác nhận gửi đi. Không bao giờ gửi vào địa chỉ rút tiền từ sàn giao dịch. Các giao dịch Dogecoin không thể đảo ngược!",
    clear_amount: "Xóa Số tiền",
    set_amount: "Đặt Số tiền",
    save_qr: "Lưu mã QR",
    WALLET_ADDRESS: "ĐỊA CHỈ VÍ",
    dogetag_link: "LIÊN KẾT DOGETAG",
    no_access_camera: "Không có quyền truy cập vào máy ảnh",
    enable_camera_access_ios: "Bật quyền truy cập máy ảnh cho MyDoge",
    grant_camera_permission_android:
      "Vui lòng cấp quyền truy cập máy ảnh cho MyDoge",
    scan_qr_payment: "Quét mã QR để thực hiện thanh toán",
    select_image: "Chọn ảnh",
    find_friends_heading: "Tìm bạn bè trên MyDoge",
    find_friends_description:
      "Cho phép truy cập danh bạ và dễ dàng tìm bạn bè và liên lạc trên MyDoge.",
    find_friends_button: "Tìm bạn bè",
    later_button: "Tôi sẽ làm điều này sau",
    own_address_error: "Bạn không thể gửi đến địa chỉ của chính mình",
    invalid_address_error: "Địa chỉ không hợp lệ",
    results_title: "Kết quả",
    all: "Tất cả",
    pending: "Đang chờ xử lý",
    enter_pin: "Nhập PIN",
    enter_pin_to_confirm: "Nhập mã PIN ví của bạn để xác nhận",
    welcome_back: "Chào mừng bạn quay trở lại",
    enter_wallet_pin: "Nhập mã PIN ví của bạn",
    forgot_pin: "Quên mã PIN",
    forgot_pin_title: "Quên mã PIN",
    forgot_pin_body:
      "Bạn có muốn sử dụng tính năng sinh trắc học để mở khóa ví của bạn không?",
    share: "Chia sẻ",
    address_copied_to_clipboard: "Địa chỉ đã được sao chép vào clipboard",
    follows_you: "Theo dõi bạn",
    official_mydoge_profile: "Hồ sơ chính thức của MyDoge",
    official_mydoge_commerce_profile: "Hồ sơ Thương mại của MyDoge",
    official_foundation_profile: "Hồ sơ Quỹ MyDoge",
    follow_back: "Theo dõi lại",
    follow: "Theo dõi",
    tip: "Gợi ý",
    share_profile: "Chia sẻ Hồ sơ",
    unfollow: "Bỏ theo dõi",
    unblock: "Mở chặn",
    block_or_report: "Chặn hoặc Báo cáo",
    copy_profile_url: "Sao chép URL Hồ sơ",
    memes_error: "Lỗi tải memes. Vui lòng quay lại và thử lại.",
    user_profile_hidden: "Hồ sơ người dùng đã ẩn",
    error_loading_profile: "Lỗi tải hồ sơ. Vui lòng quay lại và thử lại.",
    uid_not_specified:
      "Lỗi: uid không được chỉ định. Vui lòng thông báo cho hỗ trợ.",
    block_or_report_description:
      "MyDoge sẽ xem xét tất cả các hồ sơ đã bị báo cáo về bất kỳ hoạt động nào vi phạm hướng dẫn của chúng tôi. Bạn cũng có thể chặn hồ sơ để ngừng nhìn thấy các bài đăng của họ.",
    nevermind: "Thôi",
    report: "Báo cáo",
    block: "Chặn",
    unblock_user: "Mở chặn người dùng?",
    unblock_user_description:
      "Điều này sẽ mở chặn người dùng và bạn sẽ tiếp tục nhìn thấy các bài đăng của họ.",
    you_have_no_posts_yet: "Bạn chưa có bài đăng nào",
    no_posts_yet: "Chưa có bài đăng nào",
    amount: "Số tiền",
    custom: "Tùy chỉnh",
    add_a_message: "Thêm một tin nhắn",
    find_friends: "Tìm bạn bè",
    cancel: "Hủy bỏ",
    i_understand_continue: "Tôi hiểu, tiếp tục",
    hey_are_you_sure: "Xin lỗi! Bạn có chắc chắn không?",
    delete_backup_confirmation:
      "Khi bạn xóa bản sao lưu này, bạn sẽ mất bản sao lưu trên đám mây, hành động này không thể hoàn tác được",
    all_transactions: "Tất cả các giao dịch",
    pending_transactions: "Các giao dịch đang chờ xử lý",
    view_on: "Xem trên", // View on
    invoice_id_copied: "Đã sao chép số hóa đơn", // Invoice ID copied
    gift_card: "Thẻ quà tặng", // Gift Card
    invoice_id: "Số hóa đơn", // Invoice ID
    support: "Ủng hộ", // Support
    phone_number: "Số điện thoại", // Phone number
    whatsapp_verification_notice:
      "Mã xác minh sẽ được gửi đến điện thoại của bạn qua WhatsApp", // A verification code will be sent to your phone via WhatsApp
    via_whatsapp: "qua WhatsApp", // via WhatsApp
    you_may_not_have_backed_up_your_wallet:
      "Bạn hiện có bản sao lưu trên đám mây nhưng có thể bạn chưa sao lưu ví hiện tại của mình.", // You have an existing backup on the cloud, but you may not have backed up your current wallet.
    signed_in_as: "Đăng nhập như", // Signed in as
    sign_in_to_restore_backup:
      "Đăng nhập để khôi phục bản sao lưu", // Sign in to restore backup
    sign_in_with_google: "Đăng nhập với Google", // Sign in with Google
    sign_in_to_backup: "Đăng nhập để sao lưu", // Sign in to backup
  },
};
