export const zh = {
  translation: {
    en: 'English',
    zh: '简体中文',
    ja: '日本語',
    ko: '한국어',
    fr: 'Français',
    es: 'Español',
    pt: 'Português',
    preference: `个性`,
    disable_button_vibration: `禁用按钮振动`,
    back: `后退`,
    language: `语言`,
    app_theme: `应用主题`,
    system: `系统`,
    dark: `夜间模式`,
    light: `日间模式`,
    settings: `设置`,
    backup_and_security: `备份与安全`,
    manage_wallet: `管理钱包`,
    profile: `轮廓`,
    app_preferences: `应用程序偏好设置`,
    notifications: `通知`,
    help_support: `帮助支持`,
    about_my_doge: `关于我的 Doge`,
    admin: `管理员`,
    i_cloud: `iCloud`,
    cloud: `云`,
    youve_backed_up_to: `您已备份至`,
    you_havent_created_a_cloud_backup: `您尚未创建云备份`,
    manage: `管理`,
    backup: `备份`,
    view_seed_phrase: `查看私钥种子短语`,
    pin: `PIN密码`,
    back_up_to: `备份至`,
    back_up_your_wallet: `备份你的钱包`,
    back_up_your_wallet_description: `将钱包保存到云端并用密码保护。您也可以记下种子短语或将其复制到密码管理器中。`,
    pin_description: `如果您忘记了 PIN，您将需要从备份中恢复您的钱包。`,
    change_pin: `更改 PIN`,
    your_pin_is_required: `您需要输入 PIN 码才能付款和执行敏感操作。`,
    use_fingerprint: `使用指纹/面部识别`,
    ask_every_time_i_open_the_app: `每次打开应用程序时询问`,
    this_will_remove_all_wallet: `这将从您的设备中删除所有与钱包相关的数据。`,
    delete_wallet: `删除钱包`,
    sign_in_to_the_dogeverse: `登录 Dogeverse`,
    dogeverse_intro_description: `领取您的 DogeTag、寻找好友、通过您的链接接收付款并参与 Dogeverse 中的内容。`,
    sign_in: `登入`,
    sign_in_description: `您的电话号码仅用于登录，不会公开。`,
    create_account_description: `加入 Dogeverse 并与庞大的 Shibes 网络建立联系。`,
    send_verification: `发送验证`,
    verify_your_phone_number: `验证您的电话号码`,
    enter_the_code_sent_to: `输入发送的代码`,
    resend_code: `重新发送验证码`,
    wrong_number: `错误号码`,
    confirm_code: `确认验证码`,
    youve_entered_the_verse: `你已经进入了诗篇`,
    youre_now_ready_to_explore_the_dogeverse: `您现在就可以探索 Dogeverse 了！`,
    lets_go: `我们走吧！`,
    edit_profile: `编辑个人资料`,
    social_connect: `社交联系`,
    profile_privacy: `个人资料隐私`,
    profile_is_public: `个人资料是公开的`,
    show_wallet_address_and_tip_button: `显示钱包地址和小费按钮`,
    preferences: `优先`,
    confirm_x_tips: `确认𝕏 提示`,
    tips_received: `收到小费`,
    new_followers: `新的关注者`,
    new_memes: `新MEME`,
    about_mydoge: `关于MyDoge`,
    terms_of_use: `使用条款`,
    privacy_policy: `隐私政策`,
    share_mydoge: `分享 MyDoge`,
    visit_our_website: `访问我们的网站`,
    settings_and_support: `设置和支持`,
    connect_twitch: `连接 Twitch`,
    connect_x: `连接𝕏`,
    create_a_post: `创建帖子`,
    following: `下列的`,
    followers: `关注者`,
    recent_activity: `近期活动`,
    history: `历史`,
    price: `价格`,
    usd: `美元`,
    txs: `TX`,
    hr: `时间`,
    send: `发送`,
    receive: `收到`,
    buy: `买`,
    scan: `扫描`,
    from: `从`,
    to: `到`,
    note: `笔记`,
    timestamp: `时间戳`,
    confirmations: `确认`,
    tx_hash: `TX 哈希`,
    tx_hash_copied: `交易哈希已复制`,
    note_copied: `已复制注释`,
    address_copied: `地址已复制`,
    wallet: `钱包`,
    dogeverse: `狗狗宇宙`,
    shop: `店铺`,
    receive_doge: `接收 Doge`,
    send_doge: `发送 Doge`,
    confirm_transaction: `确认交易`,
    scan_qr_code: `扫描二维码`,
    new_post: `最新帖子`,
    send_doge_alert_box_message: `您可以将 DOGE 发送给您的朋友，输入钱包地址或 MyDoge 用户名`,
    wallet_address_or_username: `钱包地址或用户名`,
    saved_addresses: `已保存的地址`,
    add_new: `添新`,
    sending_to: `发送至`,
    save: `节省`,
    saved: `已保存`,
    balance: `平衡`,
    max: `最大限度`,
    next: `下一个`,
    network_fee: `网络费`,
    max_tx_size_warning: `警告：已达到最大交易规模。这是您一次可以发送的最大金额。`,
    confirm_transaction_warning: `确认之前，请务必仔细检查您要发送给谁。切勿发送到交易所提款地址。狗狗币交易无法撤销！`,
    add_note: `添加备注`,
    wallet_address: `钱包地址`,
    wallet_label: `钱包标签`,
    save_changes: `保存更改`,
    save_address: `保存地址`,
    enter_new_PIN: `输入新 PIN`,
    confirm_new_pin: `确认新 PIN`,
    enter_new_PIN_description: `输入你的 MyDoge 钱包的新 PIN 码`,
    enter_old_PIN: `输入旧 PIN 码`,
    enter_old_PIN_description: `输入你的 MyDoge 钱包的旧 PIN 码`,
    forgot_PIN: `忘记密码`,
    confirm: `确认`,
    biometrics_confirmation: `您想使用生物识别技术来解锁您的钱包吗？`,
    use_biometrics: `使用生物识别技术`,
    dismiss: `解雇`,
    remove_wallet_data_description: `这将从您的设备中删除所有与钱包相关的数据。`,
    delete_profile_forever: `永久删除您的 MyDoge 个人资料`,
    sign_out: `登出`,
    delete_wallet_confirmation: `嘿！你确定吗？`,
    remove_wallet_description: `您当前的钱包将从此应用程序中删除，但它将始终存在于区块链上。`,
    remove_profile_assets_description: `您的用户个人资料和资产将被永久移除和删除。此操作无法撤消。`,
    wallet_recovery_description: `您只能通过以下方式恢复此钱包：`,
    seed_phrase: `私钥种子短语`,
    no_seed_phrase: `MyDoge 没有您的私钥种子短语。`,
    understand_continue: `我明白，继续`,
    enter: `进入`,
    Delete: `删除`,
    erase_wallet: `抹去你的钱包`,
    and_profile_data: `和个人资料`,
    message: `信息`,
    username: `用户名`,
    edit: `编辑`,
    new_address: `新地址`,
    your_seed_phrase: `你的私钥种子短语✍️`,
    save_seed_phrase_instructions: `按顺序保存这些单词。写下来并保存在安全的地方，或复制到密码管理器中。`,
    seed_phrase_warning: `您的种子短语是您钱包的钥匙。任何拥有此短语的人都可以访问您的资金。点击以了解更多信息`,
    copy: `复制`,
    hide: `隐藏`,
    show: `展示`,
    screenshot_detected: `检测到屏幕截图`,
    screenshot_warning: `您的私钥种子短语的屏幕截图或其他数字副本可能会泄露给第三方。`,
    okay: `好的`,
    seed_phrase_importance: `我的私钥种子短语有多重要？`,
    seed_phrase_explanation: `任何拥有您的私钥种子短语的人都可以访问您的资金。不要与任何人分享您的种子短语。MyDoge 不会为您保存您的种子短语。如果您的设备损坏、丢失或被盗，或无法访问，您的种子短语是恢复钱包的唯一方法。`,
    send_receive_tips_x: `通过𝕏 发送和接收小费`,
    read_mydogetip_faq: `阅读 MyDogeTip 常见问题解答`,
    connect_with_x: `与𝕏 建立联系`,
    start_receive_tips_twitch: `开始在 Twitch 上接收小费`,
    visit_mydogetv_twitch: `访问 Twitch 上的 MyDogeTV 了解更多信息`,
    connect_with_twitch: `与 Twitch 连接`,
    screen_not_exist: `该屏幕不存在。`,
    go_to_home_screen: `转至主屏幕`,
    gift_cards: `礼品卡`,
    backup_wallet: `备份你的新钱包`,
    backup_required: `需要备份来保障你的资金安全`,
    why_backups_important: `为什么备份很重要？`,
    learn_about_backups: `点按了解备份`,
    backup_to: `备份至`,
    save_wallet_to_cloud: `将钱包保存到云端并使用密码保护`,
    write_on_paper: `在纸上书写`,
    write_down_seed_phrase: `记下你的种子短语或将其保存在密码管理器中`,
    why_backups_important_description: `自我保管意味着其他人都无法访问您的资金，即使是 MyDoge 团队也不行。如果您的设备损坏、丢失、被盗或被清除，备份是恢复钱包的唯一方法。`,
    choose_password: `选择密码`,
    use_memorable_password: `请使用您能记住的密码。密码越长越安全。`,
    more_secure_password: `请使用您能记住的密码。密码越长越安全。`,
    lose_password_lose_backup: `如果您丢失此密码，您将丢失您的钱包备份。`,
    password: `密码`,
    confirm_password: `确认密码`,
    confirm_backup: `确认备份`,
    overwrite_backup_title: `覆盖现有备份吗？`,
    existing_wallet_overwrite_prompt: `您之前已将钱包备份到云端。要覆盖它吗？`,
    overwrite_backup: `覆盖备份`,
    import_existing_wallet: `导入现有钱包`,
    unknown_cloud_error: `未知云错误`,
    unknown_cloud_error_body: `备份到云时出现未知错误。`,
    try_again_or_notify_support: `请重试或通知 MyDoge 支持。`,
    enter_recovery_password: `输入恢复密码`,
    enter_cloud_password_description: `输入你在云端存储私钥种子短语的密码`,
    import_wallet: `导入钱包`,
    imported_wallet_title: `您已导入钱包`,
    imported_wallet_success: `您已成功导入您的钱包！`,
    secure_new_wallet: `保护你的新钱包`,
    set_pin: `设置 6 位 PIN 码`,
    reenter_pin: `重新输入 6 位 PIN_LENGTH`,
    pin_payment_note: `您需要输入 PIN 码才能付款`,
    use_biometric: `使用指纹/面部识别`,
    ask_every_time: `每次打开应用程序时询问`,
    create_pin: `创建 PIN`,
    confirm_pin: `确认 PIN`,
    choose_dogeverse_username: `选择 DogeTag`,
    dogeverse_link: `您的网络链接将`,
    continue: `继续`,
    dogeverse_entry_title: `你已经进入了诗句`,
    dogeverse_entry_body: `您现在就可以探索 Dogeverse 了！`,
    manual_backup_title: `写下私钥种子短语`,
    save_words_order: `按顺序保存这些单词。写下来并保存在安全的地方，或复制到密码管理器中。`,
    seed_phrase_key: `您的种子短语是您钱包的钥匙。任何拥有此短语的人都可以访问您的资金。点击以了解更多信息`,
    written_down: `我记下来了`,
    screenshot_alert: `您的种子短语的屏幕截图或其他数字副本可能会泄露给第三方。`,
    seed_phrase_access: `任何拥有您的种子短语的人都可以访问您的资金。不要与任何人分享您的种子短语。MyDoge 不会为您保存您的种子短语。如果您的设备损坏、丢失或被盗，或无法访问，您的种子短语是恢复钱包的唯一方法。`,
    icloud_backup: `iCloud 备份`,
    cloud_backup: `云备份`,
    dont_lose_wallet: `别丢了你的钱包！`,
    save_online_backup: `保存在线备份至`,
    icloud: `iCloud`,
    google_drive: `Google 云端硬盘`,
    do_this_later: `我稍后会这样做`,
    confirm_seed_phrase: `确认种子短语`,
    select_correct_word: `请从下面的列表中选择每个位置上的正确单词。`,
    enter_seed_phrase: `输入种子短语`,
    enter_seed_phrase_instructions: `输入你的 12 个单词的私钥种子短语来恢复你现有的钱包`,
    paste: `粘贴`,
    restore_wallet: `恢复钱包`,
    wallet_imported: `钱包已进口！`,
    wallet_imported_body: `您的钱包已可以使用。`,
    restore_existing_wallet: `恢复您现有的钱包`,
    restore_existing_wallet_instructions: `你已经有一个钱包了？那我们再来谈谈它吧！`,
    restore_from: `恢复自`,
    restore_from_cloud_description: `从您的`,
    restore_with_seed_phrase: `使用私钥种子短语恢复`,
    restore_with_seed_phrase_description: `使用你的种子短语恢复现有的 MyDoge 钱包`,
    no_cloud_backup: `没有云备份`,
    no_cloud_backup_body: `未找到云备份。请从私钥种子短语恢复，或创建新钱包`,
    create_wallet: `创建钱包`,
    already_have_wallet: `我已经有钱包了`,
    buy_send_receive_dogecoin: `购买、发送和接收狗狗币`,
    send_doge_tips: `在𝕏上发送 Doge 小费，安全存储您的 Doge，成为您自己的银行`,
    shop_gift_cards_apparel: `购买礼品卡和服装`,
    buy_gift_cards: `使用狗狗币购买礼品卡,
    enter_the_dogeverse: `进入 Dogeverse`,
    claim_dogtag: `领取您的 DogeTag、寻找朋友、通过您的链接接收付款并分享表情包`,
    so_much_tip: `所以提示，太棒了！`,
    success: `成功`,
    sent_doge: `您已发送`,
    some_doge: `一些 Doge！`,
    total: `全部的`,
    done: `完毕`,
    shop_with_doge: `与 Doge 一起购物`,
    oops: `哎呀！`,
    no_comments_yet: `暂时没有评论`,
    to_post_a_comment: `发表评论`,
    your_comment: `你的评论`,
    post: `提交`,
    delete: `删除`,
    enable_push_notifications: `启用推送通知吗？`,
    get_notifications_for_tips: `接收提示和消息的通知`,
    no_thanks: `不，谢谢`,
    open_settings: `打开设置`,
    swipe_for_more: `向上滑动查看更多`,
    transaction_confirmation_alert: `确认之前，请务必仔细检查您要发送给谁。切勿发送到交易所提款地址。狗狗币交易无法撤销！`,
    clear_amount: `清除数量`,
    set_amount: `设定金额`,
    save_qr: `保存二维码`,
    WALLET_ADDRESS: `钱包地址`,
    dogetag_link: `DOGETAG 链接`,
    no_access_camera: `无法访问相机`,
    enable_camera_access_ios: `为 MyDoge 启用相机访问权限`,
    grant_camera_permission_android: `请授予 MyDoge 相机权限`,
    scan_qr_payment: `扫描二维码付款`,
    select_image: `选择图像`,
    find_friends_heading: `在 MyDoge 上寻找好友`,
    find_friends_description: `允许联系人访问并轻松在 MyDoge 上查找朋友和联系人。`,
    find_friends_button: `找朋友`,
    later_button: `我稍后会这样做`,
    own_address_error: `您无法发送到您自己的地址`,
    invalid_address_error: `无效地址`,
    results_title: `结果`,
    all: `全部`,
    pending: `待办的`,
    enter_pin: `输入 PIN`,
    enter_pin_to_confirm: `输入您的钱包 PIN 码进行确认`,
    welcome_back: `欢迎回来`,
    enter_wallet_pin: `输入您的钱包 PIN`,
    forgot_pin: `忘记密码`,
    forgot_pin_title: `忘记密码`,
    forgot_pin_body: `您想使用生物识别技术来解锁您的钱包吗？`,
    share: `分享`,
    address_copied_to_clipboard: `地址已复制到剪贴板`,
    follows_you: `跟着你`,
    official_mydoge_profile: `MyDoge 官方简介`,
    official_mydoge_commerce_profile: `MyDoge 商务官方简介`,
    official_foundation_profile: `基金会官方简介`,
    follow_back: `跟着回来`,
    follow: `跟随`,
    tip: `提示`,
    share_profile: `分享简介`,
    unfollow: `取消关注`,
    unblock: `解除封锁`,
    block_or_report: `阻止或报告`,
    copy_profile_url: `复制个人资料网址`,
    memes_error: `加载表情包时出错。请返回并重试。`,
    user_profile_hidden: `用户个人资料已隐藏`,
    error_loading_profile: `加载个人资料时出错。请返回并重试。`,
    uid_not_specified: `错误：未指定 uid。请通知支持人员。`,
    block_or_report_description: `MyDoge 将审查所有被举报的个人资料，看是否有任何违反我们准则的行为。您还可以屏蔽该个人资料，以阻止他们查看帖子。`,
    nevermind: `没关系`,
    report: `报告`,
    block: `堵塞`,
    unblock_user: `解除对用户的屏蔽？`,
    unblock_user_description: `这将解除对该用户的屏蔽，您将继续看到他们的帖子。`,
    you_have_no_posts_yet: `您还没有发布任何帖子`,
    no_posts_yet: `还没有帖子`,
    amount: `数量`,
    custom: `风格`,
    add_a_message: `添加消息`,
    find_friends: `找朋友`,
    cancel: `取消`,
    i_understand_continue: `我明白，继续`,
    hey_are_you_sure: `嘿！你确定吗？`,
    delete_backup_confirmation: `一旦删除此备份，您将丢失云备份，此操作无法撤消`,
    all_transactions: `所有交易`,
    pending_transactions: `等待的交易`,
  },
};
